Repository celestiaorg/celestia-node, pull requests merged in 2021-12, with the labels that each got.

#253 templates: remove Bidon15 as automatic assignee
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/change-request.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: admin

#254 das: Log out square width after sampling
  das/daser.go
  service/block/event_test.go
Labels: no_changelog

#261 fix(cmd): fix repository path handling for Init and Start commands
  cmd/celestia/full.go
  cmd/celestia/light.go
  cmd/celestia/main.go
  cmd/init.go
  cmd/start.go
Labels: no_changelog

#268 codeowners: remove Matthew
  .github/CODEOWNERS
Labels: no_changelog

#264 cmd, cmd/celestia: Remove `dev` mode
  cmd/celestia/dev.go
  cmd/celestia/main.go
  cmd/start.go
  node/config.go
  node/node.go
  node/testing.go
  node/type.go
Labels: area:config, no_changelog

#267 changelog: add v0.1.0
  CHANGELOG.md
Labels: no_changelog

#269 feat(Makefile): add tag parsing to inject version from git
  Makefile
Labels: no_changelog

#244 docs/adr: ADR #003 March 2022 Testnet Design for Celestia Node
  docs/adr/adr-003-march2022-testnet.md
Labels: no_changelog

#270 docs: update readme with installation chapter
  README.md
Labels: documentation

#248 Copy dependabot.yml from celestiaorg/celestia-core
  .github/dependabot.yml
Labels: ci:actions, no_changelog

#316 service/header: Fix `TestSubscriber` flakiness
  service/header/subscription_test.go
Labels: area:header, no_changelog
