Repository celestiaorg/celestia-node, pull requests merged in 2022-08, with the labels that each got.

#968 chore(state): don't import sdk types twice
  service/state/core_access.go
Labels: kind:miscellaneous

#969 feat(Makefile): formatting and linter for markdown
  Makefile
Labels: kind:miscellaneous

#964 fix(ipld/plugin): verify that data written to namespaceHasher has legit size
  ipld/plugin/nmt.go
Labels: kind:bug-fix

#966 fraud: add peer that sent an invalid fraud proof to black list
  fraud/helpers.go
  fraud/service.go
  fraud/service_test.go
  fraud/store.go
Labels: area:fraud, kind:bug-fix

#983 CODEOWNERS: Add vgonkivs and distractedm1nd to code reviewers
  .github/CODEOWNERS
Labels: admin, kind:miscellaneous

#982 swamp/discovery: fix flakiness in restart node discovery test
  node/tests/p2p_test.go
Labels: area:p2p, area:networking, swamp, kind:bug-fix

#939 test: fix daser test
  das/daser_test.go
Labels: area:fraud, testing, kind:bug-fix

#987 testing: fix flakiness
  fraud/service_test.go
  node/tests/p2p_test.go
  node/tests/swamp/swamp.go
  service/share/testing.go
Labels: swamp, kind:bug-fix

#995 chore (cmd/cel-key): add closing bracket to description in cel-key
  cmd/cel-key/node_types.go
Labels: kind:miscellaneous

#970 feat(ipld): concurrent GetSharesByNamespace
  ipld/get.go
  ipld/get_namespaced_shares.go
  ipld/get_shares.go
  ipld/get_test.go
  ipld/helpers.go
  service/share/share.go
Labels: enhancement, area:shares, kind:improvement

#1004 cmd: Drop Env in favour of vanilla context.WithValue wrappers
  cmd/cel-key/main.go
  cmd/cel-shed/main.go
  cmd/celestia/bridge.go
  cmd/celestia/cmd_test.go
  cmd/celestia/full.go
  cmd/celestia/light.go
  cmd/celestia/main.go
  cmd/env.go
  cmd/flags_core.go
  cmd/flags_header.go
  cmd/flags_key.go
  cmd/flags_misc.go
  cmd/flags_node.go
  cmd/flags_p2p.go
  cmd/flags_rpc.go
  cmd/init.go
  cmd/start.go
Labels: area:config, kind:improvement

#1006 dep: update pubsub fork version
  go.mod
  go.sum
Labels: kind:dependencies

#1000 swamp: rework fill blocks
  node/tests/fraud_test.go
  node/tests/reconstruct_test.go
  node/tests/swamp/swamp_tx.go
Labels: swamp, kind:bug-fix

#996 feat (service/state): If account doesn't exist at given height, fail gracefully
  service/state/core_access.go
Labels: area:state, kind:improvement

#922 docs(adr): ADR #010: Incentivized Testnet Monitoring
  docs/adr/adr-010-incentivized-testnet-monitoring.md
  docs/adr/img/incentivized-testnet-monitoring-scenario-a.png
  docs/adr/img/incentivized-testnet-monitoring-scenario-b.png
  docs/adr/img/incentivized-testnet-monitoring-scenario-c.png
Labels: docs:adr, kind:miscellaneous, area:metrics

#984 feat(rpc): Transaction proxy for staking tx types
  cmd/cel-key/main.go
  cmd/celestia/main.go
  service/rpc/endpoints.go
  service/rpc/state.go
  service/state/core_access.go
  service/state/interface.go
  service/state/service.go
Labels: area:state, area:rpc, kind:feature

#979 chore: backport to v0.34.x tendermint
  cmd/cel-key/main.go
  core/client.go
  core/fetcher.go
  core/testing.go
  go.mod
  go.sum
  header/testing.go
  ipld/get_test.go
  ipld/retriever.go
  node/state/keyring.go
  node/testing.go
  node/tests/swamp/config.go
  node/tests/swamp/swamp.go
  service/state/core_access.go
  service/state/interface.go
  service/state/state.go
Labels: area:node, kind:dependencies, T:dependencies

#1031 dep: bump celestia-core version
  go.mod
  go.sum
Labels: kind:dependencies

#894 Add `concurrency` block to cancel previous CI runs
  .github/workflows/docker-build.yml
  .github/workflows/go-ci.yml
  .github/workflows/labels.yml
Labels: ci:actions, kind:improvement

#1036 Revert "chore(deps): bump github.com/ipfs/go-bitswap from 0.8.0 to 0.9.0"
  go.mod
  go.sum
Labels: kind:dependencies

#1001 tracing: Adding traces to `get_shares.go`
  ipld/get_namespaced_shares.go
  ipld/get_shares.go
  ipld/helpers.go
Labels: area:shares, kind:improvement
