Repository celestiaorg/celestia-node, pull requests merged in 2022-04, with the labels that each got.

#575 .gitignore | Makefile: Dump bin in `build/` directory and `gitignore` the directory
  .gitignore
  Makefile
Labels: admin

#583 chore(core): cleanup testing utilities
  core/client_test.go
  core/fetcher_test.go
  core/testing.go
  go.mod
  node/node_bridge_test.go
  node/node_test.go
  node/testing.go
  node/tests/swamp/config.go
  node/tests/swamp/swamp.go
  service/header/core_exchange_test.go
Labels: kind:miscellaneous

#561 feat(params): add new Private network for private/testing setups
  node/node_bridge_test.go
  node/node_light_test.go
  node/testing.go
  node/tests/swamp/swamp.go
  params/bootstrap.go
  params/default.go
  params/genesis.go
  params/network.go
Labels: kind:improvement

#573 node|cmd: Make `StateService` required on node for all node types
  cmd/celestia/bridge.go
  cmd/celestia/full.go
  cmd/celestia/light.go
  node/components.go
  node/node.go
Labels: area:state, area:core_and_app

#562 docs: Add documentation
  README.md
  service/header/doc.go
  service/share/doc.go
  service/share/interface.go
  service/share/light_availability.go
Labels: docs:godocs, kind:improvement

#513 docs/adr: Update state access ADR to include balance verification
  docs/adr/adr-004-state-interaction.md
Labels: docs:adr, kind:miscellaneous

#577 docs/adr: Update March 2022 testnet ADR to clarify bridge node
  docs/adr/adr-003-march2022-testnet.md
Labels: docs:adr

#589 refactor(node): update FX DI
  go.mod
  go.sum
  node/components.go
  node/config_opts.go
  node/core/core.go
  node/init.go
  node/node.go
  node/node_bridge_test.go
  node/node_light_test.go
  node/p2p/p2p.go
  node/services/service.go
  node/settings.go
Labels: kind:miscellaneous

#590 chore(node): move out fxutil into libs
  libs/fxutil/fxutil.go
  node/components.go
  node/core/core.go
  node/fxutil/options.go
  node/fxutil/options_test.go
  node/fxutil/util.go
  node/p2p/bitswap.go
  node/p2p/host.go
  node/p2p/pubsub.go
  node/p2p/routing.go
  node/services/service.go
  node/settings.go
Labels: kind:miscellaneous

#594 chore(das): prevent logging of success on failed sample
  das/daser.go
  service/header/doc.go
Labels: kind:miscellaneous

#595 fix Dockerfile to work with -o build in Makefile
  docker/Dockerfile
Labels: ci:docker, kind:bug-fix

#605 chore: misc readme cleanups
  README.md
Labels: documentation

#607 fix go.mod to use tagged releases
  go.mod
  go.sum
Labels: dependencies

#609 Remove title from bug issue template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: admin

#618 README: Add link to docs site API page and delete `endpoints.md`
  README.md
  service/state/endpoints.md
Labels: documentation

#622 Fix `GetSharesByNamespace` ordering
  service/share/share.go
  service/share/share_test.go
  service/share/testing.go
Labels: kind:bug-fix

#625 ci: add job to check for required labels
  .github/workflows/labels.yml
Labels: kind:feature

#633 github/admin: fix the empty title for bug template
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: admin, kind:bug-fix

#623 shares|ipld: Rework data retrieval
  go.mod
  go.sum
  ipld/read.go
  ipld/read_test.go
  ipld/retriever.go
  ipld/retriever_quadrant.go
  ipld/retriever_test.go
  service/header/core_listener_test.go
  service/share/full_availability.go
  service/share/interface.go
  service/share/light_availability.go
  service/share/share.go
Labels: area:shares, area:ipld, kind:feature

#657 README.md: Add minimum system requirements
  README.md
Labels: documentation, kind:miscellaneous

#659 node: Distinct start node log to distinguish node type info from rest of logs
  node/node.go
Labels: kind:improvement

#626 ipld: Test `GetSharesByNamespace` to check ordering
  ipld/read.go
  service/share/share_test.go
  service/share/testdata/block-825320.json
Labels: area:shares, area:ipld, kind:bug-fix
