Repository celestiaorg/celestia-node, pull requests merged in 2022-12, with the labels that each got.

#1410 fix(header): add extra arg to fix build
  header/p2p/exchange.go
Labels: bug, kind:bug-fix

#1435 fix(share): update proto import path
  share/eds/byzantine/bad_encoding.go
  share/eds/byzantine/pb/share.pb.go
  share/eds/byzantine/share_proof.go
Labels: area:shares, kind:bug-fix

#1363 feat(share): Supplying `eds.Store` to bridge and full nodes
  nodebuilder/module.go
  nodebuilder/node/type.go
  nodebuilder/share/module.go
  nodebuilder/testing.go
  nodebuilder/tests/swamp/swamp.go
  share/eds/store.go
Labels: area:shares, kind:feature

#1359 feat(share): Periodic GC over EDSStore
  nodebuilder/p2p/p2p.go
  share/eds/store.go
  share/eds/store_test.go
Labels: area:shares, kind:feature

#1395 feat(share): eds.Blockstore
  share/eds/accessor_cache.go
  share/eds/blockstore.go
  share/eds/blockstore_test.go
  share/eds/eds.go
  share/eds/eds_test.go
  share/eds/store.go
  share/eds/store_test.go
Labels: area:shares, kind:feature

#1443 refactor(cmd/cel-key): Unify flag names `--node.network` -> `--p2p.network`
  cmd/cel-key/node_types.go
Labels: kind:breaking

#1439 refactor(share/eds): Store methods take `DataHash` instead of `share.Root`
  share/eds/blockstore_test.go
  share/eds/eds.go
  share/eds/eds_test.go
  share/eds/ods_test.go
  share/eds/store.go
  share/eds/store_test.go
  share/share.go
Labels: area:shares, area:block, kind:improvement

#1394 Extract common parsing logic into single function.
  cmd/celestia/bridge.go
  cmd/celestia/full.go
  cmd/celestia/light.go
  cmd/celestia/util.go
Labels: area:config, kind:miscellaneous

#1298 feat(header/p2p): implement gcing for peerTracker
  header/p2p/exchange.go
  header/p2p/exchange_test.go
  header/p2p/options.go
  header/p2p/peer_stats.go
  header/p2p/peer_tracker.go
  header/p2p/peer_tracker_test.go
  nodebuilder/header/module.go
  nodebuilder/header/module_test.go
Labels: area:header, area:p2p, kind:feature

#1460 improvement(share/discovery): send peer to multiple readers
  share/availability/discovery/set.go
Labels: area:shares, kind:improvement

#1400 core: Deprecate/remove StartTestClient in favour of StartTestCoreWithApp
  core/client_test.go
  core/fetcher_test.go
  core/testing.go
  nodebuilder/node_bridge_test.go
Labels: kind:miscellaneous

#1452 feat(share/availability): extend SharesAvailable method with peer param
  nodebuilder/share/constructors.go
  nodebuilder/share/mocks/api.go
  nodebuilder/share/share.go
  share/availability.go
  share/availability/cache/availability.go
  share/availability/cache/availability_test.go
  share/availability/full/availability.go
  share/availability/light/availability.go
Labels: area:shares, kind:feature

#1436 feat(share/blocksync): implementation of ShrEx/Sub
  share/eds/pubsub.go
  share/eds/pubsub_test.go
  share/eds/subscription.go
Labels: area:shares, area:p2p, kind:feature

#1313 feat(nodebuilder/node): Implement `Module`
  Makefile
  api/rpc/client/client.go
  api/rpc_test.go
  docs/adr/adr-009-public-api.md
  nodebuilder/default_services.go
  nodebuilder/module.go
  nodebuilder/node/admin.go
  nodebuilder/node/mocks/api.go
  nodebuilder/node/module.go
  nodebuilder/node/node.go
  nodebuilder/rpc/constructors.go
Labels: area:node, area:rpc, kind:feature, area:api

#1434 chore!(nodebuilder/p2p): Upgrade `mamaki` to `mocha`
  nodebuilder/p2p/bootstrap.go
  nodebuilder/p2p/genesis.go
  nodebuilder/p2p/network.go
Labels: kind:breaking

#1478 chore: bump celestia-app to v0.11.0
  go.mod
  go.sum
Labels: kind:dependencies

#1462 refactor(nodebuilder/p2p): Switch default network from `arabica` to `mocha`
  nodebuilder/p2p/network.go
Labels: area:p2p, kind:breaking

#1484 feat(state)!: Adding fee parameter to `CoreAccessor` operations
  api/gateway/state.go
  docs/adr/adr-009-public-api.md
  nodebuilder/state/mocks/api.go
  nodebuilder/state/state.go
  state/core_access.go
Labels: kind:breaking

#1483 fix(state): Verify the state inclusion proof without splitting keys
  go.mod
  go.sum
  state/core_access.go
  state/integration_test.go
Labels: kind:bug-fix

#1480 chore(markdownlint): disable 'Multiple headings with the same content' rule
  .markdownlint.yaml
Labels: kind:miscellaneous

#1496 feat(nodebuilder/p2p): Enable `InfiniteLimits` for resource manager if bootstrapper
  nodebuilder/p2p/config.go
  nodebuilder/p2p/module.go
Labels: area:config, area:p2p, kind:improvement

#1500 fix(node/p2p)!: remove resource manager and it's API
  go.mod
  nodebuilder/p2p/host.go
  nodebuilder/p2p/mocks/api.go
  nodebuilder/p2p/module.go
  nodebuilder/p2p/p2p.go
  nodebuilder/p2p/p2p_test.go
Labels: kind:breaking, kind:bug-fix

#1507 fix: return a struct instead of a pointer in params creation
  header/p2p/exchange.go
  header/p2p/options.go
  header/p2p/server.go
  header/store/options.go
  header/store/store.go
  nodebuilder/header/config.go
  nodebuilder/header/module.go
Labels: area:header, kind:bug-fix

#1498 fix(eds): WriteEDS thread safety for concurrent writingSessions
  share/eds/eds.go
  share/ipld/namespace_hasher_test.go
  share/ipld/nmt.go
  share/ipld/test_helpers.go
Labels: area:shares, kind:bug-fix

#1402 feat(api/rpc): Implement auth middleware on `Server`
  api/rpc/permissions/permissions.go
  api/rpc/server.go
  go.mod
  go.sum
  nodebuilder/node/auth.go
  nodebuilder/node/module.go
  nodebuilder/rpc/constructors.go
Labels: area:rpc, kind:feature, area:api

#1409 feat(share): Ensure empty CAR exists in eds.Store
  nodebuilder/share/constructors.go
  nodebuilder/share/module.go
  nodebuilder/share/share_test.go
  share/empty.go
Labels: area:shares, kind:feature

#1505 fix: correct spacing of celestia banner
  cmd/celestia/main.go
Labels: kind:bug-fix

#1446 github/CI: Fix over kill of '.gitignore'.
  .gitignore
Labels: kind:miscellaneous

#1482 improvement(cel-key): Network alias check for `--p2p.network` flag
  cmd/cel-key/node_types.go
  nodebuilder/p2p/bootstrap.go
  nodebuilder/p2p/flags.go
  nodebuilder/p2p/genesis.go
  nodebuilder/p2p/network.go
Labels: kind:miscellaneous

#1431 feat(shrex/eds): `Client`/`Server`
  nodebuilder/share/module.go
  share/p2p/shrexeds/client.go
  share/p2p/shrexeds/exchange_test.go
  share/p2p/shrexeds/options.go
  share/p2p/shrexeds/pb/extended_data_square.pb.go
  share/p2p/shrexeds/pb/extended_data_square.proto
  share/p2p/shrexeds/server.go
Labels: area:shares, area:p2p, kind:feature

#1519 share/p2p: move eds sub
  share/p2p/shrexpush/pubsub.go
  share/p2p/shrexpush/pubsub_test.go
  share/p2p/shrexpush/subscription.go
Labels: area:p2p, kind:miscellaneous

#1523 chore(nodebuilder/p2p): Update limani nodekey for arabica
  nodebuilder/p2p/bootstrap.go
Labels: area:p2p, kind:miscellaneous

#1426 feat(api/client): Implement RPC client authentication
  api/rpc/client/client.go
  api/rpc/permissions/permissions.go
  api/rpc/perms/permissions.go
  api/rpc/server.go
  api/rpc_test.go
  nodebuilder/node/mocks/api.go
Labels: area:rpc, kind:feature, area:api

#1530 improvement(header|p2p)!: remove limit status code
  header/p2p/helpers.go
  header/p2p/pb/extended_header_request.pb.go
  header/p2p/pb/extended_header_request.proto
  header/p2p/server.go
Labels: area:header, area:p2p, kind:miscellaneous

#1532 feat(header|p2p): add blacklisting to peerTracker
  header/p2p/exchange.go
  header/p2p/exchange_test.go
  header/p2p/peer_tracker.go
  header/p2p/peer_tracker_test.go
  nodebuilder/header/constructors.go
  nodebuilder/header/module_test.go
Labels: area:header, area:p2p, kind:feature

#1515 refactor: exporting nodebuilder/header.InitStore, moving mock to nodebuilder/header
  header/mocks/store.go
  header/p2p/exchange_test.go
  nodebuilder/header/constructors.go
  nodebuilder/testing.go
Labels: area:node, kind:improvement

#1534 improvement(header|p2p): log the reason on blocking
  header/p2p/peer_tracker.go
  header/p2p/peer_tracker_test.go
Labels: area:header, kind:miscellaneous

#1511 feat(eds/store): `store.GetDAH`
  docs/adr/adr-011-blocksync-overhaul-part-1.md
  share/eds/blockstore.go
  share/eds/blockstore_test.go
  share/eds/store.go
  share/eds/store_test.go
Labels: area:shares, kind:feature

#1477 feat(header/p2p)!: implement retry mechanism for header/p2p session
  header/p2p/exchange.go
  header/p2p/exchange_test.go
  header/p2p/peer_stats.go
  header/p2p/session.go
Labels: area:header, area:p2p, kind:feature

#1429 feat(cmd/celestia): Add `auth` subcommand to bridge, full and light
  cmd/auth.go
  cmd/celestia/bridge.go
  cmd/celestia/full.go
  cmd/celestia/light.go
  docs/adr/adr-009-public-api.md
  nodebuilder/node/auth.go
  nodebuilder/p2p/p2p.go
  nodebuilder/p2p/p2p_test.go
Labels: area:config, area:rpc, kind:feature, area:api

#1539 refactor(nodebuilder/p2p): Add errors for all methods
  docs/adr/adr-009-public-api.md
  nodebuilder/p2p/mocks/api.go
  nodebuilder/p2p/p2p.go
  nodebuilder/p2p/p2p_test.go
Labels: area:p2p, kind:bug-fix, area:api

#1538 refactor(eds/store): store_test.go cleanup
  share/eds/store_test.go
Labels: area:shares, kind:improvement
