Repository celestiaorg/celestia-node, pull requests merged in 2022-01, with the labels that each got.

#241 share: handle rows concurrently
  CHANGELOG-PENDING.md
  Makefile
  service/share/share.go
  service/share/share_test.go
Labels: area:shares

#329 changelog: release v0.1.1
  CHANGELOG.md
Labels: no_changelog

#289 ci: add race detector job
  .github/workflows/test.yml
  CHANGELOG-PENDING.md
  Makefile
Labels: ci:actions

#345 CHANGELOG-PENDING.md: Add `misc` category
  CHANGELOG-PENDING.md
Labels: admin

#367 service/header: remove start/stop from P2PExchange
  CHANGELOG-PENDING.md
  node/services/config.go
  node/services/service.go
  service/header/p2p_exchange.go
  service/header/p2p_exchange_test.go
Labels: area:config, area:header, area:p2p, swamp

#337 docker: Update Docker entrypoint.sh to use new `store.path` flag name
  CHANGELOG-PENDING.md
  docker/Dockerfile
  docker/entrypoint.sh
Labels: ci:docker

#338 ci: Create docker build GH action
  .github/workflows/docker-build.yml
  CHANGELOG-PENDING.md
Labels: ci:actions, ci:docker

#344 core: Retry remote core client three times before failing out
  core/client.go
  core/client_test.go
  go.mod
  go.sum
Labels: area:core_and_app, no_changelog

#342 Fix start order of mocknet
  service/header/subscription_test.go
Labels: no_changelog

#380 core: suppress logging of retry-client
  core/client.go
Labels: no_changelog

#388 tests(ipld): temporary skip a test not to see the race detector complaining
  ipld/read_test.go
Labels: no_changelog

#378 header: fix race in core listener
  das/daser.go
  service/header/core_listener.go
  service/header/core_listener_test.go
Labels: no_changelog

#315 swamp: initial structure of the tool
  .github/workflows/test.yml
  CHANGELOG-PENDING.md
  Makefile
  core/client_test.go
  core/testing.go
  node/tests/README.md
  node/tests/swamp/img/test_swamp.svg
  node/tests/swamp/swamp.go
  node/tests/swamp/sync_test.go
  service/header/service.go
Labels: swamp

#375 node/config: add WithBootstrapPeers option
  node/bridge_test.go
  node/config_opts.go
  node/light_test.go
Labels: no_changelog

#391 CONTRIBUTING.md: Add contributing.md file
  CONTRIBUTING.md
Labels: no_changelog

#334 header: hardening syncing logic
  .gitignore
  CHANGELOG-PENDING.md
  das/daser_test.go
  logs/logs.go
  node/components.go
  node/core/core.go
  node/fxutil/options.go
  node/services/service.go
  service/header/core_exchange.go
  service/header/core_listener.go
  service/header/core_listener_test.go
  service/header/header_serde.go
  service/header/header_verify.go
  service/header/header_verify_test.go
  service/header/interface.go
  service/header/local_exchange.go
  service/header/p2p_exchange.go
  service/header/p2p_subscriber.go
  service/header/service.go
  service/header/store.go
  service/header/store_test.go
  service/header/subscription_test.go
  service/header/sync.go
  service/header/sync_ranges.go
  service/header/sync_test.go
  service/header/testing.go
  service/header/verify.go
  service/header/verify_test.go
Labels: area:header
