Repository celestiaorg/celestia-node, pull requests merged in 2023-08, with the labels that each got.

#2529 fix(share/eds): turn off eds store dagstore gc by default
  share/eds/store.go
Labels: area:shares, area:storage, kind:fix

#2227 feat(share/shrex/nd): add swamp test for shrex nd
  nodebuilder/tests/nd_test.go
  share/p2p/shrexnd/server.go
Labels: area:shares, kind:feat

#2494 feat(share/eds): introduce List method for the Store
  share/eds/store.go
  share/eds/store_test.go
Labels: area:shares, kind:feat

#2520 feat(share/eds)!: upgrade badger to v4
  go.mod
  go.sum
  nodebuilder/store.go
Labels: area:shares, area:storage, kind:break!

#2516 fix(share/eds): print error for stuck register shard
  share/eds/store.go
Labels: area:shares, area:storage, kind:fix

#2508 chore(deps): bump celestia-app to rc10
  go.mod
  go.sum
Labels: kind:deps, external

#2517 fix(share/eds)!: use separate badger for inverted index
  share/eds/inverted_index.go
  share/eds/inverted_index_test.go
  share/eds/store.go
Labels: area:shares, area:storage, kind:break!

#2510 feat(share/proof)!: use nmt definition of Proof
  Makefile
  share/eds/byzantine/bad_encoding.go
  share/eds/byzantine/pb/share.pb.go
  share/eds/byzantine/pb/share.proto
  share/eds/byzantine/share_proof.go
  share/p2p/shrexnd/client.go
  share/p2p/shrexnd/params.go
  share/p2p/shrexnd/pb/share.pb.go
  share/p2p/shrexnd/pb/share.proto
  share/p2p/shrexnd/server.go
Labels: kind:feat, kind:break!, shrex

#2410 feat(share/eds)!: Don't use json.Marshal for inverted index
  share/eds/inverted_index.go
Labels: area:shares, area:storage, kind:feat, kind:break!

#2527 chore: bump app v1.0.0 rc11
  core/client_test.go
  core/exchange_test.go
  core/fetcher_test.go
  core/testing.go
  go.mod
  go.sum
  nodebuilder/tests/blob_test.go
  nodebuilder/tests/reconstruct_test.go
  nodebuilder/tests/swamp/config.go
  nodebuilder/tests/swamp/swamp.go
Labels: kind:deps

#2534 fix(share/p2p): fix race in shrexeds test
  share/p2p/shrexeds/exchange_test.go
Labels: area:shares, area:p2p, kind:fix

#2536 feat(share/store): add eds store metrics
  nodebuilder/settings.go
  nodebuilder/share/opts.go
  share/eds/metrics.go
  share/eds/store.go
Labels: area:storage, kind:feat, area:metrics

#2444 !feat(share/p2p/shrex-nd): rework shrex-nd to serve data in multiple messages
  share/eds/edstest/testing.go
  share/getters/shrex_test.go
  share/p2p/errors.go
  share/p2p/metrics.go
  share/p2p/shrexnd/client.go
  share/p2p/shrexnd/exchange_test.go
  share/p2p/shrexnd/pb/share.pb.go
  share/p2p/shrexnd/pb/share.proto
  share/p2p/shrexnd/server.go
  share/sharetest/testing.go
Labels: area:p2p, kind:feat, kind:break!

#2533 chore: bump libp2p
  go.mod
  go.sum
  nodebuilder/p2p/metrics.go
  nodebuilder/p2p/resources.go
Labels: kind:chore

#2521 feat(cmd): use rpc client instead of `http.Request`
  cmd/celestia/blob.go
  cmd/celestia/rpc.go
Labels: kind:feat, area:api

#2429 feat(eds/store): cache proofs after first eds recompute on sampling
  core/eds.go
  core/exchange.go
  core/listener.go
  nodebuilder/store_test.go
  share/eds/eds.go
  share/eds/eds_test.go
  share/eds/retriever.go
  share/getters/tee.go
  share/ipld/nmt_adder.go
Labels: area:storage, kind:feat

#2545 release!: Breaking release V0.11.0 rc9
  Makefile
  core/eds.go
  core/exchange.go
  core/listener.go
  go.mod
  go.sum
  nodebuilder/store.go
  nodebuilder/store_test.go
  share/eds/byzantine/bad_encoding.go
  share/eds/byzantine/pb/share.pb.go
  share/eds/byzantine/pb/share.proto
  share/eds/byzantine/share_proof.go
  share/eds/eds.go
  share/eds/eds_test.go
  share/eds/edstest/testing.go
  share/eds/inverted_index.go
  share/eds/inverted_index_test.go
  share/eds/retriever.go
  share/eds/store.go
  share/getters/shrex_test.go
  share/getters/tee.go
  share/ipld/nmt_adder.go
  share/p2p/errors.go
  share/p2p/metrics.go
  share/p2p/shrexnd/client.go
  share/p2p/shrexnd/exchange_test.go
  share/p2p/shrexnd/params.go
  share/p2p/shrexnd/pb/share.pb.go
  share/p2p/shrexnd/pb/share.proto
  share/p2p/shrexnd/server.go
  share/sharetest/testing.go
Labels: kind:break!, kind:misc

#2546 misc(metrics)!: split global attributes into two
  nodebuilder/settings.go
Labels: kind:break!, kind:misc

#2515 fix(rpc): fix commands handling
  cmd/celestia/blob.go
  cmd/celestia/rpc.go
  share/getters/cascade.go
Labels: area:rpc, kind:fix

#2551 fix(cmd): fix formatting during submit
  cmd/celestia/blob.go
Labels: area:rpc, kind:fix

#2554 fix(share/eds): don't use in-memory buffer for mount after shard recover
  share/eds/store.go
Labels: area:storage, kind:fix

#2558 fix(header): Only bridge node should panic on data root mismatch in e…
  core/exchange.go
  core/header_test.go
  core/listener.go
  header/header.go
Labels: area:header, kind:fix

#2559 fix(share/eds): dagstore shard restore reflection workaround
  nodebuilder/store_test.go
  share/eds/store.go
Labels: kind:fix

#2570 metrics(runtime): add runtime metrics
  go.mod
  go.sum
  nodebuilder/settings.go
Labels: kind:feat, area:metrics

#2576 fix(nodebuilder): set default log level for bitswap-client
  logs/logs.go
Labels: area:node, kind:fix

#2560 fix: TestShareAvailable_DisconnectedFullNodes
  share/availability/full/reconstruction_test.go
Labels: kind:testing, kind:fix

#2478 chore(deps): bump ipfs networking deps
  go.mod
  go.sum
  nodebuilder/node.go
  nodebuilder/p2p/bitswap.go
  nodebuilder/p2p/ipld.go
  share/availability/test/corrupt_data.go
  share/availability/test/testing.go
  share/eds/adapters.go
  share/eds/adapters_test.go
  share/eds/blockstore.go
  share/eds/eds_test.go
  share/eds/store.go
  share/ipld/get_shares_test.go
  share/ipld/nmt.go
Labels: kind:deps

#2575 fix(share/discovery): discovery should try to connect to empty hosts peers
  share/p2p/discovery/discovery.go
Labels: area:p2p, kind:fix

#2567 feat(eds/store): add eds blockstore cache metrics
  share/eds/accessor_cache.go
  share/eds/metrics.go
Labels: area:storage, kind:feat, area:metrics

#2580 chore: bump to rsmt2d v0.11.0
  go.mod
  go.sum
  share/eds/eds.go
  share/eds/edstest/testing.go
  share/eds/retriever_test.go
  share/getters/getter_test.go
  share/helpers.go
  share/ipld/add.go
  share/ipld/get_shares_test.go
Labels: kind:deps, T:dependencies, external

#2574 fix(share/ipld): Remove proofs from leaked ctx
  core/exchange.go
  core/listener.go
  share/eds/eds.go
  share/getters/tee.go
  share/ipld/nmt_adder.go
Labels: area:storage, kind:fix

#2577 feat(nodebuilder/state): Provide stubbed state module if a core endpoint not provided
  nodebuilder/core/config.go
  nodebuilder/fraud/lifecycle.go
  nodebuilder/module.go
  nodebuilder/node_light_test.go
  nodebuilder/node_test.go
  nodebuilder/settings.go
  nodebuilder/state/core.go
  nodebuilder/state/module.go
  nodebuilder/state/stub.go
  state/core_access.go
Labels: area:node, area:state, kind:feat, area:api

#2581 chore!: update celestia-app to v1.0.0-rc12
  blob/service_test.go
  go.mod
  go.sum
  nodebuilder/tests/nd_test.go
  share/namespace.go
  state/core_access.go
Labels: kind:deps, external

#2589 chore: bump deps + go1.21
  .github/workflows/go-ci.yml
  Dockerfile
  Makefile
  README.md
  go.mod
  go.sum
  share/availability/test/testing.go
  share/eds/byzantine/share_proof.go
  share/eds/eds.go
  share/getter.go
  share/getters/getter_test.go
  share/getters/shrex_test.go
  share/getters/utils_test.go
  share/ipld/get_shares_test.go
  share/p2p/shrexnd/server.go
Labels: kind:chore

#2591 fix(share/eds): scale up inverted_index badger levels
  share/eds/inverted_index.go
Labels: area:storage, kind:fix

#2511 feat(blob): improve gas estimation and track min gas price
  blob/helper.go
  blob/service.go
  state/core_access.go
  state/core_access_test.go
  state/metrics.go
Labels: kind:feat, area:blob

#2600 fix(cmd/blob): fix response
  cmd/celestia/blob.go
Labels: area:rpc, kind:fix

#2598 deps: bump dagstore
  go.mod
  go.sum
Labels: kind:deps

#2596 nodebuilder/core: Set default ports for RPC and GRPC
  nodebuilder/core/config.go
Labels: kind:fix

#2602 chore(deps): bump dagstore
  go.mod
  go.sum
Labels: kind:deps

#2597 refactor: address namespace follow-ups from celestia-app v1.0.0-rc12 bump
  share/namespace.go
  share/namespace_test.go
Labels: kind:refactor, external

#2482 feat(edssser): introduce EDS Store Stresser and cel-shed utility
  cmd/cel-shed/eds_store_stress.go
  cmd/cel-shed/main.go
  libs/edssser/edssser.go
  nodebuilder/init.go
Labels: kind:feat

#2573 feat(share/p2p/discovery): Warning for discovery loop if haven't found wanted peers in 5 minutes
  share/p2p/discovery/discovery.go
Labels: kind:feat, external, kind:chore

#2532 fix(eds/blockstore): Puts on EDSStore Blockstore
  go.mod
  nodebuilder/tests/reconstruct_test.go
  share/eds/blockstore.go
  share/eds/inverted_index.go
  share/eds/retriever.go
  share/eds/store.go
  share/getters/getter_test.go
Labels: area:storage, kind:fix

#2605 fix: fixing panic on GetShare with out of bounds indexes
  share/getter.go
  share/getters/cascade.go
  share/getters/getter_test.go
  share/getters/ipld.go
  share/getters/store.go
Labels: area:shares, kind:fix

#2619 chore: bump go-header and go-fraud
  api/docgen/examples.go
  core/exchange.go
  core/header_test.go
  core/listener.go
  core/listener_test.go
  das/coordinator_test.go
  das/daser.go
  das/daser_test.go
  das/state.go
  das/worker.go
  go.mod
  go.sum
  header/header.go
  header/headertest/testing.go
  header/headertest/verify_test.go
  header/serde.go
  header/verify.go
  nodebuilder/das/constructors.go
  nodebuilder/das/module.go
  nodebuilder/fraud/constructors.go
  nodebuilder/fraud/fraud.go
  nodebuilder/fraud/lifecycle.go
  nodebuilder/fraud/module.go
  nodebuilder/fraud/service.go
  nodebuilder/fraud/unmarshaler.go
  nodebuilder/header/constructors.go
  nodebuilder/header/module.go
  nodebuilder/header/module_test.go
  nodebuilder/header/service.go
  nodebuilder/header/service_test.go
  nodebuilder/module.go
  nodebuilder/p2p/pubsub.go
  nodebuilder/settings.go
  nodebuilder/state/core.go
  nodebuilder/state/module.go
  nodebuilder/testing.go
  nodebuilder/tests/api_test.go
  nodebuilder/tests/sync_test.go
  share/eds/byzantine/bad_encoding.go
  share/eds/byzantine/bad_encoding_test.go
  share/eds/retriever_test.go
  share/p2p/discovery/discovery.go
  share/p2p/peers/manager.go
  share/p2p/peers/manager_test.go
  state/core_access.go
  state/integration_test.go
Labels: kind:chore

#2639 chore(nodebuilder/p2p)!: Bump arabica-10
  nodebuilder/p2p/bootstrap.go
  nodebuilder/p2p/genesis.go
  nodebuilder/p2p/network.go
Labels: kind:break!, external
