Repository celestiaorg/celestia-node, pull requests merged in 2023-12, with the labels that each got.

#2914 test(blob): add submitting equal blobs test case
  nodebuilder/tests/blob_test.go
Labels: kind:testing, area:blob

#2990 ci: configure prerelease-suffix
  .goreleaser.yaml
Labels: external, kind:ci

#2972 pruner: Implement skeleton for pruner package
  das/daser.go
  das/daser_test.go
  das/options.go
  libs/utils/fs.go
  libs/utils/square.go
  logs/logs.go
  nodebuilder/das/constructors.go
  nodebuilder/module.go
  nodebuilder/prune/module.go
  nodebuilder/state/config.go
  pruner/archival/pruner.go
  pruner/archival/window.go
  pruner/light/pruner.go
  pruner/light/window.go
  pruner/pruner.go
  pruner/service.go
  pruner/window.go
Labels: area:storage, kind:feat

#2997 fix(cmd): explicitly set a string representation of the error
  cmd/util.go
Labels: kind:fix

#2993 share: typos fix
  share/getters/getter_test.go
  share/p2p/params.go
  share/p2p/shrexsub/pubsub_test.go
Labels: kind:docs, external

#2963 Revert "fix(modp2p): temporary disable quic (#2837)"
  nodebuilder/p2p/addrs.go
  nodebuilder/p2p/host.go
Labels: area:p2p, kind:fix

#2955 feat(rpc): default binding to localhost vs 0.0.0.0 open to world
  api/gateway/config.go
  nodebuilder/config_test.go
  nodebuilder/gateway/config.go
  nodebuilder/gateway/config_test.go
  nodebuilder/gateway/defaults.go
  nodebuilder/gateway/defaults_test.go
  nodebuilder/gateway/flags.go
  nodebuilder/gateway/flags_test.go
  nodebuilder/rpc/config.go
  nodebuilder/rpc/config_test.go
  nodebuilder/rpc/defaults.go
  nodebuilder/rpc/defaults_test.go
  nodebuilder/rpc/flags.go
  nodebuilder/rpc/flags_test.go
Labels: area:rpc, kind:refactor

#2988 ignore otel patch updates
  .github/dependabot.yml
Labels: kind:ci

#2957 fix(share/byzantine): fix proof collection
  share/eds/byzantine/bad_encoding_test.go
  share/eds/byzantine/byzantine.go
Labels: area:shares, kind:fix

#3005 feat(share/p2p/peer-manager): limit amount of stored pools in peer-manager
  share/getters/shrex.go
  share/p2p/peers/manager.go
  share/p2p/peers/manager_test.go
  share/p2p/peers/metrics.go
  share/p2p/peers/pool.go
Labels: area:p2p, kind:feat

#2883 chore: bump go-libp2p
  go.mod
  go.sum
Labels: kind:deps, kind:chore
