Repository celestiaorg/celestia-node, pull requests merged in 2023-11, with the labels that each got.

#2887 chore(cmd): add a newline after printing token so it doesn't run into shell prompt
  cmd/auth.go
Labels: area:rpc, kind:chore

#2917 chore: increase lint timeout
  .github/workflows/go-ci.yml
Labels: kind:chore, github_actions

#2918 fix(test/daser): stop the eds store before finishing the test
  share/availability/full/testing.go
Labels: kind:testing, kind:fix, flakiness

#2916 chore: update link to node rpc docs
  README.md
Labels: kind:docs, external

#2919 chore(ci): disable fail-fast on matrix tests
  .github/workflows/go-ci.yml
Labels: kind:ci

#2911 fix(blob/service): handle absence proof
  blob/service.go
  blob/service_test.go
  share/eds/utils.go
  share/getters/shrex.go
Labels: kind:fix, area:blob

#2865 (ci) enable optional verbose logging on unit tests and upload artifacts
  .github/workflows/ci_release.yml
  .github/workflows/go-ci.yml
  Makefile
Labels: kind:ci

#2913 chore(ci): remove 'continue-on-error' configuration from flakey tests
  .github/workflows/go-ci.yml
Labels: kind:ci

#2863 feat(core): Enable metrics for core package
  core/exchange.go
  core/exchange_metrics.go
  core/exchange_test.go
  core/listener.go
  core/listener_metrics.go
  core/listener_test.go
  core/option.go
  nodebuilder/core/config.go
  nodebuilder/core/module.go
  nodebuilder/settings.go
  nodebuilder/tests/swamp/swamp.go
Labels: area:core_and_app, kind:feat, area:metrics

#2948 chore: bump celestia-app to v1.4.0
  go.mod
  go.sum
  state/core_access_test.go
Labels: kind:deps, external

#2950 feat(cmd): pass Start options; add WithFlagSet option
  cmd/celestia/bridge.go
  cmd/celestia/full.go
  cmd/celestia/light.go
  cmd/celestia/main.go
  cmd/node.go
  cmd/start.go
  cmd/util.go
Labels: kind:feat, area:cli

#2974 chore(node): tweak pyroscope options
  nodebuilder/settings.go
Labels: area:node, kind:chore

#2975 chore(modheader): lower store cache size for LN
  nodebuilder/header/config.go
Labels: kind:chore

#2973 misc(config): add @ramin to codeowners
  .github/CODEOWNERS
Labels: area:config, kind:misc

#2960 fix(node/store): substantial memory usage improvements
  Makefile
  blob/blob.go
  cmd/node.go
  go.mod
  go.sum
  nodebuilder/fraud/mocks/api.go
  nodebuilder/header/mocks/api.go
  nodebuilder/share/mocks/api.go
  nodebuilder/store.go
  nodebuilder/tests/fraud_test.go
  share/availability/mocks/availability.go
  share/eds/inverted_index.go
  share/mocks/getter.go
Labels: area:node, kind:fix

#2962 refactor(modp2p): decouple Bitswap
  nodebuilder/p2p/bitswap.go
Labels: area:p2p, kind:refactor
