Repository celestiaorg/celestia-node, pull requests merged in 2023-06, with the labels that each got.

#2295 feat(nodebuilder): Add jwt.Signer to Node struct for auth token access
  cmd/auth.go
  libs/authtoken/authtoken.go
  nodebuilder/node.go
  nodebuilder/node_test.go
Labels: area:node, kind:feat

#2290 chore(nodebuilder): decrease lifecycle timeout for LN
  nodebuilder/node.go
  nodebuilder/node_test.go
Labels: kind:fix

#2298 fix!(blob/module): fix api by changing variadic params to a slice
  api/gateway/state.go
  blob/service.go
  blob/service_test.go
  nodebuilder/blob/blob.go
  nodebuilder/blob/mocks/api.go
  nodebuilder/state/mocks/api.go
  nodebuilder/state/state.go
  nodebuilder/tests/api_test.go
  nodebuilder/tests/blob_test.go
  state/core_access.go
Labels: area:state, kind:break!, kind:fix, area:blob

#2302 fix(gateway): remove the GetByHeight hussle and rely on Module's logic
  api/gateway/availability.go
  api/gateway/header.go
  api/gateway/share.go
  nodebuilder/blob/mocks/api.go
Labels: kind:fix, area:gateway

#2306 fix(blob): use default min gas price from core
  blob/service.go
  nodebuilder/tests/blob_test.go
Labels: kind:fix, area:blob

#2308 feat(cmd/rpc): adding blob module to rpc cli and fixing namespace parsing
  cmd/celestia/rpc.go
Labels: kind:feat, area:api

#2310 fix(getter/cascade): cascade getter should return fast on context cancel
  share/getters/cascade.go
  share/getters/cascade_test.go
Labels: area:shares, kind:fix

#2313 fix(nodebuilder): fix parsing url for core.ip
  nodebuilder/core/flags.go
Labels: area:node, kind:fix

#2307 chore(state): extend error handling in core accessor
  go.mod
  state/core_access.go
Labels: area:state, kind:chore

#2299 chore(docs): update open rpc with blob module
  openrpc.json
Labels: kind:chore

#2305 chore: bump celestia-app to v1.0.0-rc2
  blob/blob_test.go
  core/eds.go
  go.mod
  go.sum
  share/eds/eds_test.go
  share/ipld/nmt.go
  share/share.go
Labels: kind:deps, external

#2330 chore: bump common docker ci version pipeline
  .github/workflows/docker-build-publish.yml
Labels: kind:chore, github_actions

#2329 !feat(api/gateway): return txdata from submitPFB if it is present
  api/gateway/state.go
  api/gateway/state_test.go
Labels: kind:feat, kind:break!, area:api

#2340 fix(cmd/rpc): plaintext parsing of data for blob.Submit and state.SubmitPayForBlob
  cmd/celestia/rpc.go
Labels: kind:fix, area:api

#2336 fix(dagstore): changing log level to WARN to shorten startup
  logs/logs.go
Labels: area:storage, kind:misc

#2341 fix(share): left pad nid in NewNamespaceV0 instead of right padding
  share/nid.go
  share/nid_test.go
Labels: area:shares, kind:fix

#2342 fix(daser) don't count recent jobs in total sampled stats
  das/stats.go
Labels: kind:fix, area:das

#2339 fix(state): fixing panic when err != nil but response is nil
  state/core_access.go
Labels: area:state, kind:fix

#2338 fix!(state): use node blob type instead of app type to fix inconsistent unmarshalling
  api/docgen/examples.go
  api/gateway/state.go
  api/gateway/state_test.go
  blob/service.go
  cmd/celestia/rpc.go
  nodebuilder/blob/mocks/api.go
  nodebuilder/das/mocks/api.go
  nodebuilder/fraud/mocks/api.go
  nodebuilder/header/mocks/api.go
  nodebuilder/node/admin.go
  nodebuilder/node/mocks/api.go
  nodebuilder/share/mocks/api.go
  nodebuilder/state/mocks/api.go
  nodebuilder/state/state.go
  share/mocks/getter.go
  state/core_access.go
Labels: kind:break!, kind:fix

#2326 chore: mocha-2 support
  nodebuilder/p2p/bootstrap.go
  nodebuilder/p2p/genesis.go
  nodebuilder/p2p/network.go
Labels: kind:chore

#2332 fix(nodebuilder): Fix dns lookup
  libs/utils/address.go
  libs/utils/address_test.go
  nodebuilder/core/flags.go
Labels: area:node, kind:fix

#2361 fix(rpc/client): stop overwriting existing clients
  api/rpc/client/client.go
Labels: kind:fix, area:api

#2348 fix(state): JSON marshaling for sdk Address wrapper
  api/docgen/examples.go
  api/gateway/state.go
  cmd/celestia/rpc.go
  nodebuilder/state/mocks/api.go
  state/address_test.go
  state/core_access.go
  state/integration_test.go
  state/state.go
Labels: kind:fix, area:api

#2360 chore!(gateway): add deprecation notices
  api/gateway/das.go
  api/gateway/endpoints.go
  api/gateway/state.go
  nodebuilder/gateway/config.go
  nodebuilder/gateway/constructors.go
  nodebuilder/gateway/flags.go
  nodebuilder/gateway/module.go
Labels: kind:break!, area:api

#2362 fix(header): GetByHeight requests for syncer head +1 shouldnt error
  nodebuilder/header/service.go
  nodebuilder/tests/api_test.go
Labels: area:header, kind:fix

#2364 fix(share/eds): fix test flake
  share/eds/store.go
Labels: kind:fix

#2347 feat!(nodbuilder): making lifecycle timeouts configurable
  nodebuilder/config.go
  nodebuilder/node.go
  nodebuilder/node/config.go
Labels: area:config, kind:break!

#2358 fix(swamp): use synchronized map as container for nodes
  go.mod
  nodebuilder/tests/fraud_test.go
  nodebuilder/tests/swamp/swamp.go
  nodebuilder/tests/sync_test.go
Labels: swamp, kind:fix

#2162 chore(nodebuilder/tests): Clean up sync_test tests
  nodebuilder/tests/fraud_test.go
  nodebuilder/tests/p2p_test.go
  nodebuilder/tests/swamp/swamp.go
  nodebuilder/tests/sync_test.go
Labels: swamp, kind:chore

#2242 feat(share): collect absence proof if namespace is not present in merkle tree
  share/get_test.go
  share/getter.go
  share/getters/utils.go
  share/ipld/get.go
  share/ipld/namespace_data.go
  share/ipld/nmt.go
Labels: area:shares, kind:feat

#2359 deps: bump libp2p
  go.mod
  go.sum
  share/p2p/discovery/discovery_test.go
Labels: kind:deps

#2370 feat(node): implement node.AuthVerify and node.AuthNew
  api/rpc/server.go
  libs/authtoken/authtoken.go
  nodebuilder/node.go
  nodebuilder/node/admin.go
  nodebuilder/node/mocks/api.go
  nodebuilder/node/module.go
  nodebuilder/node/node.go
  nodebuilder/node_test.go
  nodebuilder/tests/api_test.go
Labels: kind:feat, area:api

#2325 fix: parseNamespace for <= 10 byte namespace IDs
  cmd/celestia/rpc.go
  cmd/celestia/rpc_test.go
Labels: kind:fix

#2375 add kind:testing label
  .github/workflows/labels.yml
Labels: kind:chore

#2274 feat(libs/pidstore): Implement `PeerIDStore`
  libs/pidstore/pidstore.go
  libs/pidstore/pidstore_test.go
Labels: kind:feat

#2384 Update ci_release.yml
  .github/workflows/ci_release.yml
  .github/workflows/docker-build-publish.yml
Labels: bug, kind:fix, github_actions

#2373 feat(gateway): enabling CORS * on gateway
  api/gateway/middleware.go
  api/gateway/server_test.go
Labels: kind:feat, area:gateway

#2367 share: introduce Namespace type
  share/namespace.go
  share/namespace_test.go
  share/nid.go
Labels: kind:feat

#2138 feat(header): Check app version in eh validation and return err on mismatch
  go.mod
  go.sum
  header/header.go
  header/headertest/verify_test.go
Labels: area:core_and_app, kind:feat

#2371 chore: bump celestia-app rc4
  go.mod
  go.sum
Labels: kind:deps

#2256 feat(share/getter) Add support for Non-inclusion proofs
  blob/service.go
  share/availability/light/availability_test.go
  share/get_test.go
  share/getter.go
  share/getters/cascade.go
  share/getters/getter_test.go
  share/getters/shrex.go
  share/getters/shrex_test.go
  share/getters/store.go
  share/getters/utils.go
  share/ipld/namespace_data.go
  share/p2p/shrexnd/client.go
  share/p2p/shrexnd/exchange_test.go
  share/p2p/shrexnd/pb/share.pb.go
  share/p2p/shrexnd/pb/share.proto
  share/p2p/shrexnd/server.go
Labels: area:shares, kind:feat

#2393 fix(api/gateway): Handle err from tx properly to avoid panic
  api/gateway/state.go
Labels: kind:fix, area:api

#2395 chore: bump celestia-app to v1.0.0-rc5
  go.mod
  go.sum
Labels: kind:deps, external

#2399 deps: bump libp2p
  go.mod
  go.sum
  nodebuilder/blob/mocks/api.go
  nodebuilder/das/mocks/api.go
  nodebuilder/fraud/mocks/api.go
  nodebuilder/header/mocks/api.go
  nodebuilder/node/mocks/api.go
  nodebuilder/share/mocks/api.go
  nodebuilder/state/mocks/api.go
  share/mocks/getter.go
Labels: kind:deps

#2394 fix(libs/utils): Use valid ip4 address
  libs/utils/address.go
Labels: kind:fix

#2404 feat: adding spans to shrex getter
  share/getters/shrex.go
Labels: area:shares, kind:feat

#2405 chore(go.mod): Bump nmt
  go.mod
  go.sum
  share/eds/eds.go
Labels: kind:deps

#2417 chore!: bump arabica-9
  nodebuilder/p2p/bootstrap.go
  nodebuilder/p2p/genesis.go
  nodebuilder/p2p/network.go
Labels: kind:break!, external

#2414 feat: update Go base alpine - add branch in makefile
  Dockerfile
  Makefile
Labels: kind:chore, docker
