Repository celestiaorg/celestia-node, pull requests merged in 2023-02, with the labels that each got.

#1646 deps: temporary replace go-libp2p with the custom fork containing a hotfx
  go.mod
  go.sum
Labels: kind:bug-fix

#1651 refactor(ipld): removing nmt hasher
  go.mod
  go.sum
  share/ipld/namespace_hasher.go
  share/ipld/namespace_hasher_test.go
  share/ipld/nmt.go
Labels: area:ipld, kind:dependencies

#1684 fix(share/discovery): add loop to read events from the channel multiple times
  nodebuilder/tests/p2p_test.go
  share/availability/discovery/discovery.go
Labels: kind:bug-fix

#1679 chore: bump celestia-app to v0.12.0-rc5
  go.mod
  go.sum
  header/pb/extended_header.pb.go
  header/pb/extended_header.proto
  libs/header/p2p/pb/header_request.pb.go
Labels: kind:dependencies

#1673 fix(Makefile): make install should not invoke build
  Makefile
Labels: kind:miscellaneous

#1537 bump(metrics): upgrade otel to the latest version
  cmd/flags_misc.go
  go.mod
  go.sum
  nodebuilder/settings.go
Labels: kind:dependencies, area:metrics

#1686 fix: flake in TestNamespaceHasher_CorruptedData
  share/availability/test/corrupt_data.go
Labels: kind:bug-fix

#1641 feat: using tmjson encoding on `core.Header`
  header/header.go
Labels: kind:improvement

#1688 dep(pubsub): upgrade pubsub version
  go.mod
  go.sum
Labels: kind:dependencies

#1620 feat!: add versioning for pubsub topics in fraud, header packages
  core/listener_test.go
  das/daser_test.go
  fraud/helpers.go
  fraud/requester.go
  fraud/service.go
  fraud/service_test.go
  fraud/sync.go
  fraud/testing.go
  libs/header/p2p/exchange.go
  libs/header/p2p/exchange_test.go
  libs/header/p2p/helpers.go
  libs/header/p2p/options.go
  libs/header/p2p/server.go
  libs/header/p2p/server_test.go
  libs/header/p2p/subscriber.go
  libs/header/p2p/subscription_test.go
  nodebuilder/header/constructors.go
  nodebuilder/header/module.go
  nodebuilder/header/module_test.go
  share/p2p/shrexsub/pubsub.go
Labels: area:header, area:fraud, kind:breaking

#1696 chore(nodebuilder/p2p)!: Upgrade arabica chain ID to `arabica-4`
  nodebuilder/p2p/network.go
Labels: area:p2p, kind:breaking

#1693 feat!: Move Dockerfile to the root of the project
  .github/workflows/ci_release.yml
  .github/workflows/docker-build.yml
  Dockerfile
Labels: ci:docker, kind:miscellaneous

#1689 chore: bump celestia-app v0.12.0-rc6
  go.mod
  go.sum
Labels: area:core_and_app, kind:dependencies

#1701 chore!: bump arabica-4 genesis hash
  nodebuilder/p2p/genesis.go
Labels: kind:breaking

#1700 chore(go.mod): Depend on upstream libp2p (AKA remove hlibp2p)
  go.mod
  go.sum
Labels: kind:dependencies

#1638 feat(node | das | libs/header/sync): add total uptime node metrics + totalSampled das metrics + totalSynced sync metrics
  das/checkpoint.go
  das/coordinator.go
  das/metrics.go
  das/options.go
  das/worker.go
  go.mod
  header/metrics.go
  libs/header/sync/metrics.go
  libs/header/sync/sync.go
  nodebuilder/node/metrics.go
  nodebuilder/node_test.go
  nodebuilder/settings.go
  share/availability/mocks/availability.go
  share/mocks/getter.go
Labels: area:node, kind:improvement, area:das, area:metrics

#1707 feat(share/p2p/peers): Implement peer manager
  das/daser_test.go
  nodebuilder/share/module.go
  share/availability.go
  share/availability/cache/availability.go
  share/availability/cache/availability_test.go
  share/availability/discovery/discovery.go
  share/availability/full/availability.go
  share/availability/light/availability.go
  share/availability/light/testing.go
  share/availability/mocks/availability.go
  share/p2p/peers/manager.go
  share/p2p/peers/manager_test.go
  share/p2p/peers/pool.go
  share/p2p/peers/pool_test.go
Labels: area:shares, area:p2p, kind:feature

#1672 Add cel-key utility to Docker images
  Dockerfile
Labels: ci:docker, kind:miscellaneous

#1719 feat(nodebuilder/p2p): migrate to EDSStore Blockstore for Bitswap for FNs/BNs
  fraud/service_test.go
  fraud/testing.go
  nodebuilder/p2p/bitswap.go
  nodebuilder/p2p/module.go
  nodebuilder/share/module.go
Labels: area:shares, kind:feature

#1717 feat(das) add shrex.Sub integration into DASer
  das/coordinator.go
  das/coordinator_test.go
  das/daser.go
  das/daser_test.go
  das/doc.go
  das/options.go
  das/state.go
  das/worker.go
  nodebuilder/das/constructors.go
  nodebuilder/das/module.go
  nodebuilder/share/module.go
Labels: area:shares, area:p2p, kind:improvement, area:das

#1725 chore(nodebuidler/p2p)!: Upgrade arabica to `arabica-5`
  nodebuilder/p2p/network.go
Labels: area:config, area:p2p, kind:breaking

#1624 feat(share/getters): ShrexGetter retry logic
  share/getters/shrex.go
  share/p2p/shrexeds/client.go
  share/p2p/shrexnd/client.go
Labels: area:shares, kind:feature

#1735 chore!: bump arabica-5 genesis-hash
  nodebuilder/p2p/genesis.go
Labels: kind:breaking

#1724 bugfix(libs/header): store incoming head in syncer
  libs/header/sync/sync.go
  libs/header/sync/sync_head.go
  libs/header/sync/sync_test.go
Labels: area:header, kind:bug-fix

#1736 refactor(das): Don't increment totalSampled if header `isRecent`
  das/metrics.go
  das/worker.go
Labels: kind:bug-fix, area:das, area:metrics

#1723 chore: bump celestia-app to v0.12.0-rc7
  cmd/cel-key/main.go
  core/config.go
  go.mod
  go.sum
Labels: kind:dependencies

#1726 bugfix(swamp): fix fraud tests
  das/daser_test.go
  headertest/testing.go
  nodebuilder/tests/fraud_test.go
  nodebuilder/tests/swamp/swamp_tx.go
  share/eds/retriever_test.go
Labels: swamp, kind:bug-fix

#1741 chore(libs/header/p2p): Fixing some debug logs
  libs/header/p2p/exchange.go
  libs/header/p2p/session.go
Labels: area:header, kind:miscellaneous

#1734 fix(share/shrex/peer_manager): peer manager needs to do soft delete on synced pool instead of hard one
  share/p2p/peers/manager.go
  share/p2p/peers/manager_test.go
Labels: area:shares, area:p2p, kind:bug-fix

#1727 improvement(nodebuilder/p2p): Turn on PEX by default for bridges and fulls
  nodebuilder/config.go
  nodebuilder/p2p/config.go
Labels: area:p2p, kind:improvement

#1739 refactor(core): `CoreListener` broadcasts EDS hash before it broadcasts `ExtendedHeader`
  core/listener.go
Labels: kind:improvement

#1737 feat: Use common Docker Build Pipeline
  .github/workflows/docker-build-common.yml
Labels: ci:docker, kind:miscellaneous

#1738 feat(share/shrex/peer_manager): add debug logs to peer manager
  share/p2p/peers/manager.go
Labels: area:shares, area:p2p, kind:improvement

#1732 feat(share/shrex/peer_manager): add backoff in peer manager
  go.mod
  share/getters/shrex.go
  share/p2p/peers/manager.go
  share/p2p/peers/manager_test.go
  share/p2p/peers/pool.go
  share/p2p/peers/pool_test.go
  share/p2p/peers/timedqueue.go
  share/p2p/peers/timedqueue_test.go
Labels: area:shares, area:p2p, kind:feature

#1740 fix(getters/shrex): removing implicit context assumption
  share/getters/shrex.go
Labels: area:shares, kind:bug-fix

#1753 feat(nodebuilder/gateway): Add warn log if gateway is enabled so users know to use with caution
  nodebuilder/gateway/module.go
Labels: kind:miscellaneous, area:gateway

#1706 improvement(libs/header): Check for requested height before fetching it from the store
  libs/header/interface.go
  libs/header/mocks/store.go
  libs/header/p2p/exchange_test.go
  libs/header/p2p/server.go
  libs/header/store/store.go
Labels: kind:improvement

#1729 feat(share): Integrate rearchitectured blocksync into fx
  nodebuilder/share/constructors.go
  nodebuilder/share/module.go
  share/getters/shrex.go
  share/getters/shrex_test.go
  share/p2p/shrexnd/server.go
Labels: area:shares, kind:feature

#1745 feat(share/shrex): add Rate limit middleware for shrex servers
  share/p2p/middleware.go
  share/p2p/shrexeds/client.go
  share/p2p/shrexeds/exchange_test.go
  share/p2p/shrexeds/options.go
  share/p2p/shrexeds/pb/extended_data_square.pb.go
  share/p2p/shrexeds/pb/extended_data_square.proto
  share/p2p/shrexeds/server.go
  share/p2p/shrexnd/client.go
  share/p2p/shrexnd/exchange_test.go
  share/p2p/shrexnd/options.go
  share/p2p/shrexnd/pb/share.pb.go
  share/p2p/shrexnd/pb/share.proto
  share/p2p/shrexnd/server.go
Labels: area:shares, kind:feature

#1761 refactor(share/getters): cleaning up error logs, wrapping cascadegetter with teegetter
  nodebuilder/share/constructors.go
  share/availability/full/availability.go
  share/getters/shrex.go
  share/getters/store.go
  share/p2p/peers/manager.go
  share/p2p/shrexeds/options.go
  share/p2p/shrexnd/options.go
Labels: area:shares, kind:improvement

#1762 fix(das | share): handle `ErrByzantine` from `multierr`s when found with `context.Canceled`
  das/daser.go
  nodebuilder/tests/fraud_test.go
  share/availability/full/availability.go
Labels: area:shares, kind:bug-fix

#1760 chore(nodebuilder/p2p)!: Upgrade arabica chainID for shrex upgrade
  nodebuilder/p2p/network.go
Labels: area:p2p, kind:breaking

#1751 feat(share): allow LNs to GetSharesByNamespace and GetEDS over shrex
  nodebuilder/share/constructors.go
  nodebuilder/share/module.go
Labels: area:shares, kind:feature

#1770 fix(nodebuilder/share): Revert providing `shrex.Getter` and its associated components to light node
  nodebuilder/share/constructors.go
  nodebuilder/share/module.go
Labels: area:shares, kind:bug-fix

#1772 chore(nodebuilder/p2p)!: Update genesis hash
  nodebuilder/p2p/genesis.go
Labels: area:p2p, kind:miscellaneous

#1783 das: Add timeout log for how long failed sampling routine took
  das/worker.go
Labels: kind:miscellaneous, area:das

#1565 refactor(nodebuilder): Allow setting keyring backend `file` with `--keyring.backend` flag
  cmd/auth.go
  cmd/cel-key/node_types.go
  cmd/cel-shed/header.go
  cmd/flags_node.go
  cmd/start.go
  libs/keystore/fs_keystore.go
  libs/keystore/fs_keystore_test.go
  libs/keystore/keystore.go
  libs/keystore/map_keystore.go
  nodebuilder/init.go
  nodebuilder/module.go
  nodebuilder/state/config.go
  nodebuilder/state/flags.go
  nodebuilder/state/keyring.go
  nodebuilder/state/module.go
  nodebuilder/store.go
  nodebuilder/store_test.go
  nodebuilder/testing.go
  nodebuilder/tests/swamp/swamp.go
Labels: area:config, area:state, kind:feature

#1788 fix(eds): don't commit reconstructed EDS in Retriever
  share/eds/retriever.go
Labels: area:shares, kind:bug-fix

#1793 fix(header): add timeout for the head retrieval
  header/metrics.go
Labels: area:header, kind:bug-fix

#1787 swamp: rename Components to Config
  nodebuilder/tests/swamp/config.go
  nodebuilder/tests/swamp/swamp.go
Labels: kind:miscellaneous

#1789 refactor(share/p2p): Discovery controls `ensurePeers` lifecycle
  nodebuilder/share/module.go
  share/availability/discovery/discovery.go
  share/p2p/peers/manager.go
  share/p2p/peers/manager_test.go
Labels: area:shares, area:p2p, kind:improvement

#1800 deps: bump libp2p and all supporting libs
  go.mod
  go.sum
  nodebuilder/p2p/bitswap.go
  share/availability/test/corrupt_data.go
  share/availability/test/testing.go
  share/eds/adapters.go
  share/eds/adapters_test.go
  share/eds/blockstore.go
  share/ipld/nmt.go
  share/p2p/peers/options.go
  share/p2p/shrexsub/pubsub.go
Labels: kind:dependencies

#1769 chore(.github): Add @walldiss to codeowners
  .github/CODEOWNERS
Labels: kind:miscellaneous

#1765 refactor(modp2p): Introduce String method for Network and use it everywhere
  cmd/flags_node.go
  nodebuilder/fraud/constructors.go
  nodebuilder/header/module.go
  nodebuilder/p2p/network.go
  nodebuilder/share/module.go
Labels: kind:improvement

#1778 fix(nodebuilder/share): Only provide necessary components to Bridge
  nodebuilder/share/constructors.go
  nodebuilder/share/module.go
Labels: area:config, area:shares, kind:improvement

#1766 feat(libhead): introduce peer scoring params for HeaderSub topic
  libs/header/p2p/gossip_score.go
  libs/header/p2p/helpers.go
  libs/header/p2p/subscriber.go
Labels: kind:feature

#1767 feat(libfraud): introduce peer scoring params for FraudSub topic
  fraud/gossip_score.go
  fraud/helpers.go
  fraud/registry.go
Labels: kind:feature

#1805 feat(fraud): String for FraudType
  fraud/helpers.go
  fraud/proof.go
Labels: area:fraud, kind:feature

#1773 chore(modp2p): update blocktime to match core
  nodebuilder/header/module.go
  nodebuilder/p2p/network.go
Labels: area:p2p, kind:miscellaneous

#1791 refactor(das|share): Cleanup timeouts through sampling stack
  das/options.go
  nodebuilder/das/config.go
  nodebuilder/share/constructors.go
  share/availability.go
  share/availability/full/availability.go
  share/availability/light/availability.go
  share/getters/cascade.go
  share/getters/cascade_test.go
  share/getters/shrex.go
  share/getters/utils.go
Labels: area:shares, kind:improvement, area:das

#1809 feat(modp2p): add whitelist for ResourceManager, as eclipse protection
  nodebuilder/p2p/module.go
Labels: area:p2p, kind:feature

#1748 feat(nodebuilder/header)!: Implement remainder of `header.Module`
  api/gateway/header.go
  api/gateway/share.go
  api/rpc_test.go
  docs/adr/adr-009-public-api.md
  libs/header/sync/sync.go
  libs/header/sync/sync_test.go
  nodebuilder/header/header.go
  nodebuilder/header/mocks/api.go
  nodebuilder/header/service.go
Labels: kind:breaking, area:api

#1808 feat!(p2p): put networkID as the first sub-string in protocolID
  core/listener_test.go
  das/daser_test.go
  fraud/helpers.go
  fraud/service.go
  libs/header/p2p/exchange.go
  libs/header/p2p/exchange_test.go
  libs/header/p2p/helpers.go
  libs/header/p2p/options.go
  libs/header/p2p/server.go
  libs/header/p2p/server_test.go
  libs/header/p2p/subscriber.go
  libs/header/p2p/subscription_test.go
  nodebuilder/header/constructors.go
  nodebuilder/header/module.go
  nodebuilder/share/module.go
  share/p2p/shrexeds/client.go
  share/p2p/shrexeds/options.go
  share/p2p/shrexeds/server.go
  share/p2p/shrexnd/client.go
  share/p2p/shrexnd/options.go
  share/p2p/shrexnd/server.go
  share/p2p/shrexsub/pubsub.go
Labels: area:p2p, kind:breaking

#1756 feat(modp2p): tune GossipSub
  fraud/gossip_score.go
  libs/header/p2p/gossip_score.go
  nodebuilder/header/mocks/api.go
  nodebuilder/p2p/pubsub.go
  share/p2p/shrexsub/pubsub.go
Labels: area:p2p, kind:feature

#1810 fix: fix protocolID representation
  fraud/helpers.go
  libs/header/p2p/helpers.go
  share/p2p/shrexeds/options.go
  share/p2p/shrexnd/options.go
Labels: kind:bug-fix

#1815 feat(das): Don't sample recent jobs twice
  das/checkpoint.go
  das/coordinator.go
  das/daser_test.go
  das/metrics.go
  das/state.go
  das/stats.go
  das/worker.go
Labels: kind:improvement, area:das

#1814 perf(share): don't broadcast datahash of empty EDS
  nodebuilder/p2p/pubsub.go
  share/empty.go
  share/p2p/peers/manager.go
  share/p2p/shrexsub/pubsub.go
  share/share.go
Labels: area:shares, kind:improvement

#1819 perf(share/full): avoid loading EDS for subsequent availability checks
  share/availability/full/availability.go
  share/availability/full/testing.go
Labels: area:shares, kind:improvement

#1794 feat: add libheader exchange metrics
  libs/header/p2p/exchange.go
  libs/header/p2p/metrics.go
  nodebuilder/header/opts.go
  nodebuilder/settings.go
Labels: area:header, kind:feature, area:metrics

#1823 improvement(cmd): Auth cmd generates new priv key for jwt if not yet found in node store
  cmd/auth.go
Labels: area:config, area:rpc, kind:improvement

#1816 refactor(share/p2p/shrexeds): Increase ODS write deadline to block time and add hash to log
  share/p2p/shrexeds/options.go
  share/p2p/shrexeds/server.go
Labels: area:shares, kind:miscellaneous
