Repository celestiaorg/celestia-node, pull requests merged in 2023-05, with the labels that each got.

#2142 fix(gateway): deescalating log in gateway's writeErr
  api/gateway/util.go
Labels: kind:fix, area:api

#2125 chore(nodebuilder): timeouts, errors and logs
  nodebuilder/node.go
Labels: area:node, kind:fix

#2113 fix(cmd/rpc): parsing JSON for all parameters, and adding handler to GetSharesByNamespace
  cmd/celestia/rpc.go
Labels: kind:fix, area:api

#2154 fix(nodebuilder/tests): Add dummy trusted peers to satisfy fx
  nodebuilder/tests/reconstruct_test.go
  nodebuilder/tests/swamp/swamp.go
Labels: swamp, kind:fix

#2117 fix(share/discovery)!: revamp Discovery
  nodebuilder/share/config.go
  nodebuilder/share/constructors.go
  nodebuilder/tests/p2p_test.go
  share/availability/discovery/backoff.go
  share/availability/discovery/backoff_test.go
  share/availability/discovery/discovery.go
  share/availability/discovery/discovery_test.go
  share/availability/discovery/set.go
  share/availability/discovery/set_test.go
  share/availability/full/testing.go
  share/getters/shrex_test.go
  share/p2p/peers/manager_test.go
Labels: bug, area:shares, kind:break!, kind:fix

#2095 feat(shrex): metrics
  nodebuilder/settings.go
  nodebuilder/share/config.go
  nodebuilder/share/opts.go
  share/getters/shrex.go
  share/p2p/metrics.go
  share/p2p/middleware.go
  share/p2p/shrexeds/client.go
  share/p2p/shrexeds/exchange_test.go
  share/p2p/shrexeds/params.go
  share/p2p/shrexeds/server.go
  share/p2p/shrexnd/client.go
  share/p2p/shrexnd/exchange_test.go
  share/p2p/shrexnd/params.go
  share/p2p/shrexnd/server.go
Labels: kind:feat, area:metrics

#2160 fix(nodebuilder): fix error log and shut the fx
  logs/logs.go
  nodebuilder/node.go
Labels: kind:fix

#2163 fix(share/discovery): fixes from Advertise logic audit
  share/availability/discovery/discovery.go
Labels: area:shares, kind:fix

#2164 deps: Bump celestia-app version to 0.13.0
  core/testing.go
  go.mod
  go.sum
Labels: area:core_and_app, kind:deps

#1798 feat(share)!: add functional options to share pkg
  nodebuilder/config.go
  nodebuilder/share/config.go
  nodebuilder/share/constructors.go
  nodebuilder/share/module.go
  share/availability.go
  share/availability/cache/availability.go
  share/availability/discovery/discovery.go
  share/availability/discovery/discovery_test.go
  share/availability/discovery/options.go
  share/availability/full/availability.go
  share/availability/full/testing.go
  share/availability/light/availability.go
  share/availability/light/options.go
  share/availability/light/sample.go
  share/getters/shrex_test.go
  share/p2p/peers/manager_test.go
Labels: enhancement, area:config, area:shares, kind:feat, kind:break!, area:api

#2177 fix(share/p2p/shrexeds): return correct err on context error
  share/p2p/shrexeds/client.go
Labels: area:shares, kind:fix

#2179 fix(discovery): race in discovery tests
  share/availability/discovery/discovery_test.go
Labels: area:shares, kind:fix

#2178 fix(daser): do not spawn retry job twice
  das/state.go
Labels: kind:fix, area:das

#2185 fix(daser): persist retry count after restart
  das/checkpoint.go
  das/coordinator_test.go
  das/state.go
  das/worker.go
Labels: kind:fix, area:das

#2173 refactor(header/service): ensure that the requested height is less or equal than the network head
  nodebuilder/header/service.go
Labels: kind:refactor

#2190 fix(share/discovery): deadlock in limitedSet
  share/availability/discovery/discovery.go
  share/availability/discovery/set.go
Labels: area:shares, kind:fix

#2194 Fix Makefile docstrings and phony targets.
  Makefile
Labels: kind:fix, kind:chore

#2195 Remove docstring for removed function IsBefore.
  header/header.go
Labels: kind:doc, kind:chore

#2052 feat(blob): add blob service
  blob/blob.go
  blob/blob_test.go
  blob/helper.go
  blob/service.go
  blob/service_test.go
  header/headertest/testing.go
Labels: kind:feat, area:blob

#2197 refactor(shrex/server): add warn logs to shrex server
  share/availability/discovery/discovery.go
  share/p2p/shrexeds/server.go
  share/p2p/shrexnd/server.go
Labels: area:shares, area:p2p, kind:refactor

#2201 feat(nodebuilder/header): Add `WaitForHeight` endpoint
  docs/adr/adr-009-public-api.md
  nodebuilder/header/header.go
  nodebuilder/header/service.go
Labels: area:header, kind:feat, area:api

#2207 feat(share/discovery): Discard method
  share/availability/discovery/discovery.go
Labels: area:shares, kind:feat

#2215 fix(header): check that Commit corresponds to Header
  header/header.go
  nodebuilder/tests/fraud_test.go
Labels: area:header, kind:fix

#2209 chore(das): improve logging
  das/subscriber.go
  das/worker.go
Labels: kind:fix, area:das

#2219 fix(header): fix testing utilities and tests
  header/header.go
  header/headertest/testing.go
Labels: area:header, kind:fix

#2221 Makefile: fix docstring for cel-key target.
  Makefile
Labels: kind:chore

#2212 feat(share/discovery): add backoff metrics
  share/availability/discovery/backoff.go
  share/availability/discovery/discovery.go
  share/availability/discovery/metrics.go
Labels: area:shares, kind:feat

#2230 fix(share/p2p)!: share.ErrNamespaceNotFound and integration into shrex-nd
  share/availability/light/availability_test.go
  share/getter.go
  share/getters/cascade.go
  share/getters/getter_test.go
  share/getters/shrex.go
  share/getters/shrex_test.go
  share/getters/store.go
  share/getters/utils.go
  share/p2p/shrexnd/client.go
  share/p2p/shrexnd/exchange_test.go
  share/p2p/shrexnd/params.go
  share/p2p/shrexnd/pb/share.pb.go
  share/p2p/shrexnd/pb/share.proto
  share/p2p/shrexnd/server.go
Labels: area:shares, kind:break!, kind:fix

#2226 improvement(test/swamp): set core IP and Port to nodes
  nodebuilder/tests/swamp/swamp.go
Labels: swamp, kind:misc, e2e

#2105 feat(share/p2p/peer-manager): use shrexSub peers as full nodes
  share/p2p/peers/manager.go
  share/p2p/peers/metrics.go
  share/p2p/peers/pool.go
  share/p2p/shrexeds/client.go
Labels: area:shares, area:p2p, kind:feat

#2229 refactor(nodebuilder/share): don't wrap store getter with tee getter
  nodebuilder/share/constructors.go
Labels: area:node, area:shares, kind:refactor

#2228 fix(utils): splitCtx return original timeout when it is less than min timeout
  share/getters/utils.go
Labels: kind:fix

#2239 share/discovery: moving the package closer to shrex
  nodebuilder/share/config.go
  nodebuilder/share/constructors.go
  nodebuilder/share/module.go
  nodebuilder/share/opts.go
  share/availability/full/availability.go
  share/availability/full/testing.go
  share/getters/shrex_test.go
  share/p2p/discovery/backoff.go
  share/p2p/discovery/backoff_test.go
  share/p2p/discovery/discovery.go
  share/p2p/discovery/discovery_test.go
  share/p2p/discovery/metrics.go
  share/p2p/discovery/options.go
  share/p2p/discovery/set.go
  share/p2p/discovery/set_test.go
  share/p2p/peers/manager.go
  share/p2p/peers/manager_test.go
Labels: external, kind:chore

#2249 chore(.github): Fix coverage run to separate unit test and coverage upload to codecov
  .github/workflows/go-ci.yml
  Makefile
Labels: kind:fix

#2231 refactor(share/shrex-nd): blacklist peers that send invalid data
  share/getters/shrex.go
  share/p2p/shrexnd/client.go
Labels: area:p2p, kind:refactor

#2257 fix: bump to celestia-app v0.13.3
  api/gateway/share_test.go
  api/gateway/testdata/sharesBase64.json
  go.mod
  go.sum
Labels: area:core_and_app, kind:fix, external

#2253 feat!: bump app v1.0.0-rc0
  api/gateway/share.go
  api/gateway/share_test.go
  core/eds.go
  core/eds_test.go
  core/exchange_test.go
  core/testing.go
  core/testing_grpc.go
  das/coordinator_test.go
  das/daser_test.go
  das/metrics.go
  das/worker.go
  go.mod
  go.sum
  nodebuilder/tests/swamp/config.go
  nodebuilder/tests/swamp/swamp.go
  nodebuilder/tests/swamp/swamp_tx.go
  share/availability/cache/availability_test.go
  share/availability/light/availability.go
  share/availability/light/availability_test.go
  share/availability/light/testdata/sample-block.json
  share/eds/byzantine/bad_encoding.go
  share/eds/byzantine/bad_encoding_test.go
  share/eds/byzantine/byzantine.go
  share/eds/byzantine/share_proof_test.go
  share/eds/eds.go
  share/eds/eds_test.go
  share/eds/retriever.go
  share/eds/retriever_quadrant.go
  share/eds/retriever_test.go
  share/eds/store.go
  share/eds/testdata/example-root.json
  share/eds/testdata/example.car
  share/empty.go
  share/get_test.go
  share/getter.go
  share/getters/getter_test.go
  share/getters/ipld.go
  share/getters/shrex_test.go
  share/getters/store.go
  share/getters/utils.go
  share/ipld/nmt.go
  share/ipld/nmt_test.go
  share/p2p/shrexnd/exchange_test.go
  share/share.go
  share/test_helpers.go
  state/integration_test.go
Labels: kind:deps

#2255 refactor(misc): pretty print namespace.iD and peer.ID
  das/daser.go
  share/empty.go
  share/getter.go
  share/getters/cascade.go
  share/getters/ipld.go
  share/getters/shrex.go
  share/getters/store.go
  share/getters/tee.go
  share/getters/utils.go
  share/p2p/discovery/discovery.go
  share/p2p/peers/manager.go
  share/p2p/shrexeds/client.go
  share/p2p/shrexeds/server.go
  share/p2p/shrexnd/server.go
Labels: kind:misc, kind:refactor

#2271 test: delete `Test_dataFromSharesBSR`
  api/gateway/share_test.go
  api/gateway/testdata/sharesBase64.json
Labels: testing, kind:misc, external

#2269 chore(blob): adapt changes
  blob/blob.go
  blob/blob_test.go
  blob/blobtest/testing.go
  blob/helper.go
  blob/service.go
  blob/service_test.go
  nodebuilder/tests/blob_test.go
  share/nid.go
Labels: kind:chore

#2263 fix(share/discovery): timeout FindPeers operation
  share/p2p/discovery/discovery.go
  share/p2p/discovery/metrics.go
Labels: area:shares, kind:fix

#2272 feat(blob): register on the client and doc gen
  Makefile
  api/rpc/client/client.go
  api/rpc_test.go
  nodebuilder/default_services.go
  nodebuilder/rpc/constructors.go
Labels: kind:feat, area:blob

#2273 feat!(blob): blob module
  Makefile
  api/gateway/state.go
  api/rpc/client/client.go
  api/rpc_test.go
  blob/blob.go
  blob/blob_test.go
  blob/blobtest/testing.go
  blob/helper.go
  blob/service.go
  blob/service_test.go
  header/headertest/testing.go
  nodebuilder/blob/blob.go
  nodebuilder/blob/mocks/api.go
  nodebuilder/blob/module.go
  nodebuilder/default_services.go
  nodebuilder/module.go
  nodebuilder/node.go
  nodebuilder/node/admin.go
  nodebuilder/rpc/constructors.go
  nodebuilder/state/mocks/api.go
  nodebuilder/state/state.go
  nodebuilder/tests/blob_test.go
  share/nid.go
  state/core_access.go
Labels: kind:feat, kind:break!, area:blob

#2281 chore!: bump arabica testnet params
  nodebuilder/p2p/bootstrap.go
  nodebuilder/p2p/genesis.go
  nodebuilder/p2p/network.go
Labels: kind:break!, external

#2277 feat(nodebuilder): add ip resolving capabilities to core.ip
  nodebuilder/core/flags.go
Labels: area:config, kind:feat, external

#2284 chore(share/ipld): pretify error
  share/ipld/namespace_data.go
Labels: area:shares, kind:chore
