Repository celestiaorg/celestia-node, pull requests merged in 2023-04, with the labels that each got.

#2001 fix(eds/share): replacing fsmount with filemount registration
  share/eds/store.go
Labels: area:shares, kind:fix

#1795 feat(p2p): add native libp2p debug metrics
  cmd/flags_misc.go
  go.mod
  nodebuilder/p2p/config.go
  nodebuilder/p2p/metrics.go
  nodebuilder/p2p/module.go
  nodebuilder/settings.go
Labels: kind:feat, area:metrics

#1969 ci(.github): Fix kind label for dependabot
  .github/dependabot.yml
Labels: ci:actions, kind:misc, T:dependencies

#2022 fix: updating broken link in README.md
  README.md
Labels: area:repository, kind:doc

#1963 refactoring!(state): extend SubmitPayForBlob method
  api/gateway/state.go
  nodebuilder/node/admin.go
  nodebuilder/state/mocks/api.go
  nodebuilder/state/state.go
  state/core_access.go
Labels: area:state, kind:break!, kind:refactor

#2005 feat: pin version of common workflows and actions
  .github/workflows/ci_release.yml
  .github/workflows/docker-build-publish.yml
Labels: kind:misc

#2015 chore(deps): Upgrading to go 1.20
  .github/workflows/go-ci.yml
  Dockerfile
  README.md
  cmd/celestia/main.go
  cmd/start.go
  das/state_test.go
  das/worker.go
  go.mod
  header/headertest/testing.go
  nodebuilder/p2p/p2p_test.go
  nodebuilder/store.go
  nodebuilder/tests/swamp/swamp.go
  share/availability/full/availability_test.go
  share/availability/light/availability_test.go
  share/availability/test/corrupt_data.go
  share/eds/adapters_test.go
  share/eds/retriever_test.go
  share/get_test.go
  share/getters/cascade.go
  share/getters/cascade_test.go
  share/getters/shrex.go
  share/getters/shrex_test.go
  share/getters/utils_test.go
  share/ipld/nmt_test.go
  share/ipld/test_helpers.go
  share/p2p/peers/options.go
  share/test_helpers.go
Labels: kind:deps, kind:chore

#1925 !refactor(share/p2p/peers): expose peer manager params to nodebuilder
  nodebuilder/share/config.go
  nodebuilder/share/module.go
  share/p2p/peers/manager.go
  share/p2p/peers/manager_test.go
  share/p2p/peers/options.go
Labels: area:node, area:shares, kind:feat, kind:break!

#1971 das/share: Change log from DAH.Hash() to DAH.String()
  das/worker.go
  share/availability/full/availability.go
  share/availability/light/availability.go
  share/eds/retriever.go
Labels: external

#2023 refactoring(share/p2p): remove TTL in pubsub
  share/p2p/shrexsub/pubsub.go
Labels: area:shares, area:p2p, kind:refactor

#2048 refactor(share/eds): add ErrNotFound to eds store and shrex server
  share/eds/store.go
  share/eds/store_test.go
  share/p2p/shrexnd/server.go
Labels: area:shares, kind:refactor

#1951 fix(swamp): fixing p2p_test and reconstruct_test
  nodebuilder/p2p/bootstrap.go
  nodebuilder/p2p/pubsub.go
  nodebuilder/tests/p2p_test.go
  nodebuilder/tests/reconstruct_test.go
  nodebuilder/tests/sync_test.go
Labels: swamp, kind:fix

#2002 chore(log): Suppress pubsub logs to WARN and net/identify to ERROR
  logs/logs.go
Labels: kind:misc, external

#2039 refactor(libs/fraud): fraud tests overhaul
  das/daser_test.go
  go.mod
  go.sum
  header/headertest/testing.go
  libs/fraud/fraudserv/gossip_score.go
  libs/fraud/fraudserv/helpers.go
  libs/fraud/fraudserv/pb/proof.pb.go
  libs/fraud/fraudserv/pb/proof.proto
  libs/fraud/fraudserv/requester.go
  libs/fraud/fraudserv/service.go
  libs/fraud/fraudserv/service_test.go
  libs/fraud/fraudserv/store.go
  libs/fraud/fraudserv/store_test.go
  libs/fraud/fraudserv/subscription.go
  libs/fraud/fraudserv/sync.go
  libs/fraud/fraudtest/dummy_proof.go
  libs/fraud/fraudtest/dummy_service.go
  libs/fraud/interface.go
  libs/fraud/metrics.go
  libs/fraud/proof.go
  libs/fraud/service_test.go
  libs/fraud/testing.go
  nodebuilder/fraud/constructors.go
  nodebuilder/p2p/pubsub.go
  nodebuilder/testing.go
  share/eds/retriever_test.go
  share/eds/store.go
Labels: area:header, area:fraud, kind:refactor

#2026 feat: include function signatures in rpc cli autocompletions
  cmd/celestia/cmd_test.go
  cmd/celestia/rpc.go
Labels: kind:misc, area:api

#2054 fix: adding traces to pyroscope dashboard
  cmd/flags_misc.go
Labels: area:repository, kind:fix

#2064 chore: migrate to go-fraud
  api/docgen/examples.go
  das/daser.go
  das/daser_test.go
  go.mod
  go.sum
  libs/fraud/fraudserv/gossip_score.go
  libs/fraud/fraudserv/helpers.go
  libs/fraud/fraudserv/pb/proof.pb.go
  libs/fraud/fraudserv/pb/proof.proto
  libs/fraud/fraudserv/requester.go
  libs/fraud/fraudserv/service.go
  libs/fraud/fraudserv/service_test.go
  libs/fraud/fraudserv/store.go
  libs/fraud/fraudserv/store_test.go
  libs/fraud/fraudserv/subscription.go
  libs/fraud/fraudserv/sync.go
  libs/fraud/fraudtest/dummy_proof.go
  libs/fraud/fraudtest/dummy_service.go
  libs/fraud/interface.go
  libs/fraud/metrics.go
  libs/fraud/proof.go
  libs/fraud/registry.go
  nodebuilder/das/constructors.go
  nodebuilder/das/module.go
  nodebuilder/fraud/constructors.go
  nodebuilder/fraud/fraud.go
  nodebuilder/fraud/lifecycle.go
  nodebuilder/fraud/mocks/api.go
  nodebuilder/fraud/module.go
  nodebuilder/fraud/service.go
  nodebuilder/header/module.go
  nodebuilder/header/module_test.go
  nodebuilder/p2p/pubsub.go
  nodebuilder/settings.go
  nodebuilder/state/module.go
  share/eds/byzantine/bad_encoding.go
Labels: area:fraud, kind:chore

#2030 chore: Make use of common adr template
  Makefile
  docs/adr/README.md
  docs/adr/adr-template.md
Labels: kind:chore

#2053 fix(share/eds): add custom inverted index for badger as storage backend
  share/eds/inverted_index.go
  share/eds/inverted_index_test.go
  share/eds/store.go
Labels: area:storage, kind:fix

#2071 fix(eds/store): use `Path` instead of `Host` in `FileMount` serialization/deserialization
  go.mod
  go.sum
Labels: area:storage, kind:fix

#2050 feat(share/getter): add support for ErrNotFound in IPLD/Store getters
  share/availability/light/availability_test.go
  share/eds/adapters_test.go
  share/eds/blockstore.go
  share/eds/blockstore_test.go
  share/getter.go
  share/getters/getter_test.go
  share/getters/ipld.go
  share/getters/store.go
  share/getters/utils.go
  share/ipld/get.go
  share/ipld/nmt.go
Labels: area:shares, kind:feat

#2070 feat(cli): adding unsafe-reset-store command
  cmd/celestia/bridge.go
  cmd/celestia/full.go
  cmd/celestia/light.go
  cmd/reset_store.go
  nodebuilder/init.go
  nodebuilder/store.go
Labels: area:node, kind:feat

#2069 feat: if NODE_STORE is set use it in custom init command
  docker/entrypoint.sh
Labels: kind:feat, external

#2074 feat(share/getter): add support for ErrNotFound in shrex getter implementation
  share/eds/inverted_index_test.go
  share/eds/store_test.go
  share/getters/shrex.go
  share/getters/shrex_test.go
  share/p2p/errors.go
  share/p2p/peers/manager.go
  share/p2p/peers/manager_test.go
  share/p2p/shrexeds/client.go
  share/p2p/shrexeds/exchange_test.go
  share/p2p/shrexeds/pb/extended_data_square.pb.go
  share/p2p/shrexeds/pb/extended_data_square.proto
  share/p2p/shrexeds/server.go
  share/p2p/shrexnd/client.go
  share/p2p/shrexnd/exchange_test.go
  share/p2p/shrexnd/server.go
Labels: area:shares, kind:refactor

#2078 fix(modp2p): fix libp2p metrics
  cmd/flags_misc.go
  nodebuilder/init.go
  nodebuilder/p2p/config.go
  nodebuilder/p2p/host.go
  nodebuilder/p2p/metrics.go
  nodebuilder/p2p/module.go
  nodebuilder/p2p/module_test.go
  nodebuilder/p2p/resources.go
  nodebuilder/settings.go
  nodebuilder/store.go
Labels: area:p2p, kind:fix, kind:refactor

#2079 refactor(share/shrex): cleanup shrex logs
  logs/logs.go
  share/p2p/shrexeds/client.go
  share/p2p/shrexeds/params.go
  share/p2p/shrexeds/server.go
  share/p2p/shrexnd/client.go
  share/p2p/shrexnd/server.go
Labels: area:shares, kind:refactor

#2081 fix(modp2p): fix(modp2p): use Infof
  nodebuilder/p2p/metrics.go
Labels: kind:fix

#2084 refactor(nodebuilder): Use `my_celes_key` as default if no `--keyring.accname` is specified
  nodebuilder/init.go
  nodebuilder/state/keyring.go
Labels: kind:refactor

#2082 fix(modp2p): disable metrics on libp2p by default
  nodebuilder/p2p/host.go
Labels: area:p2p, kind:fix

#2075 fix: removing skip from shrexeds tests and updating them to current logic
  share/p2p/shrexeds/exchange_test.go
Labels: area:shares, kind:fix

#2088 deps: bump go-header
  go.mod
  go.sum
Labels: area:header, kind:deps

#2068 feat(cmd): Add `config-remove` and `config-update` commands to CLI
  cmd/celestia/bridge.go
  cmd/celestia/full.go
  cmd/celestia/light.go
  cmd/config.go
  go.mod
  go.sum
  nodebuilder/config.go
  nodebuilder/config_test.go
Labels: area:config, kind:feat

#2091 refactor(nodebuiler): introduce ServiceBreaker and update FX
  go.mod
  go.sum
  nodebuilder/das/constructors.go
  nodebuilder/das/module.go
  nodebuilder/fraud/lifecycle.go
  nodebuilder/header/constructors.go
  nodebuilder/header/module.go
  nodebuilder/node.go
  nodebuilder/state/core.go
  nodebuilder/state/module.go
Labels: kind:deps, kind:refactor

#1860 feat(daser): introduce retry logic for daser
  api/docgen/exampledata/samplingStats.json
  das/checkpoint.go
  das/checkpoint_test.go
  das/coordinator.go
  das/coordinator_test.go
  das/daser_test.go
  das/metrics.go
  das/state.go
  das/state_test.go
  das/stats.go
  das/worker.go
Labels: kind:feat, area:das

#2101 refactor(share/shrex): improve shrex logging
  go.mod
  share/getters/shrex.go
  share/p2p/middleware.go
  share/p2p/peers/manager.go
  share/p2p/peers/pool.go
  share/p2p/shrexeds/client.go
  share/p2p/shrexeds/server.go
  share/p2p/shrexnd/client.go
  share/p2p/shrexnd/server.go
Labels: area:shares, kind:refactor

#2108 refactor(api/gateway) return error from gateway if header is not synced yet
  api/gateway/availability.go
  api/gateway/header.go
  api/gateway/share.go
Labels: area:api, kind:refactor

#2124 fix(share/eds): pass correct context to DagStore
  share/eds/store.go
Labels: area:shares, kind:fix

#2093 feat(core): Add span for handle-new-signed-block in listener
  core/listener.go
Labels: area:core_and_app, kind:misc, area:metrics

#2114 refactor(share/p2p/shrex): use default timeout for shrex-eds client
  share/p2p/shrexeds/client.go
  share/p2p/shrexnd/client.go
Labels: area:p2p, kind:refactor

#2115 fix(share/shrex): hotfixes for shrex getter respecting context
  share/getters/shrex.go
  share/getters/shrex_test.go
Labels: bug, area:shares, kind:fix

#2103 feat(das): add backoff to retry jobs
  das/backoff.go
  das/backoff_test.go
  das/state.go
  das/state_test.go
Labels: kind:feat, area:das

#2139 fix(modp2p): increase ConnMgr defaults for Full and Bridge
  nodebuilder/p2p/config.go
  nodebuilder/p2p/misc.go
Labels: kind:fix

#2140 deps: bump go-header
  go.mod
  go.sum
  nodebuilder/header/module_test.go
  nodebuilder/testing.go
Labels: kind:deps

#2134 fix(nodebuilder/header): Cancel subscription when done
  nodebuilder/header/service.go
  nodebuilder/tests/api_test.go
Labels: area:header, area:rpc, kind:fix
