Repository celestiaorg/celestia-node, pull requests merged in 2023-10, with the labels that each got.

#2762 feat(cmd/rpc): add node store flag
  cmd/auth.go
  cmd/celestia/rpc.go
  cmd/flags_node.go
  cmd/rpc.go
Labels: area:rpc, kind:feat

#2764 refactor(gateway): remove deprecated endpoints
  api/gateway/das.go
  api/gateway/endpoints.go
  api/gateway/state.go
  api/gateway/state_test.go
  nodebuilder/gateway/config.go
  nodebuilder/gateway/constructors.go
  nodebuilder/gateway/flags.go
  nodebuilder/gateway/module.go
  nodebuilder/state/cmd/state.go
Labels: area:gateway, kind:refactor

#2778 test(share/eds/cache): benchmark eds cache eviction performance
  share/eds/store_test.go
  share/getters/getter_test.go
Labels: area:storage, kind:testing

#2795 chore(deps): fix dependabot otel grouping
  .github/dependabot.yml
Labels: kind:deps

#2665 fix(tests)!: fix FraudProofHandling test
  nodebuilder/fraud/fraud.go
  nodebuilder/fraud/mocks/api.go
  nodebuilder/tests/fraud_test.go
Labels: swamp, kind:break!, kind:fix

#2797 chore(share/availability)!: Remove `ProbabilityOfAvailability` endpoint
  .github/workflows/issue-label-automation.yml
  api/gateway/availability.go
  nodebuilder/share/mocks/api.go
  nodebuilder/share/share.go
  share/availability.go
  share/availability/full/availability.go
  share/availability/light/availability.go
Labels: area:shares, kind:break!, area:api

#2801 chore: bump celestia-app, celestia-core, and the cosmos-sdk
  go.mod
  go.sum
Labels: kind:deps

#2812 refactoring!(rpc/cmd): rework rpc commands
  api/gateway/das.go
  api/gateway/endpoints.go
  api/gateway/state.go
  api/gateway/state_test.go
  cmd/auth.go
  cmd/celestia/bridge.go
  cmd/celestia/cmd_test.go
  cmd/celestia/full.go
  cmd/celestia/light.go
  cmd/celestia/logs.go
  cmd/celestia/rpc.go
  cmd/celestia/util.go
  cmd/flags_node.go
  cmd/rpc.go
  cmd/util.go
  cmd/util_test.go
  nodebuilder/blob/cmd/blob.go
  nodebuilder/das/cmd/das.go
  nodebuilder/gateway/config.go
  nodebuilder/gateway/constructors.go
  nodebuilder/gateway/flags.go
  nodebuilder/gateway/module.go
  nodebuilder/header/cmd/header.go
  nodebuilder/node/cmd/node.go
  nodebuilder/p2p/cmd/p2p.go
  nodebuilder/share/cmd/share.go
  nodebuilder/state/cmd/state.go
Labels: area:rpc, kind:break!, kind:refactor

#2798 (chore) ensure all dependency group PRs get the default label
  .github/dependabot.yml
Labels: kind:ci

#2813 deps: bump go-header
  go.mod
  go.sum
Labels: kind:deps

#2816 fix: openrpc.json remove output line from generation of json
  openrpc.json
Labels: area:api, kind:docs, external

#2817 fix(share/peer-manager): use mutex for peer-manager pool cleanup
  share/p2p/peers/manager.go
  share/p2p/peers/pool.go
Labels: area:p2p, kind:fix

#2730 feat(discovery): discover peers by tag
  nodebuilder/share/config.go
  nodebuilder/share/constructors.go
  nodebuilder/share/module.go
  nodebuilder/tests/p2p_test.go
  share/availability/full/testing.go
  share/getters/shrex_test.go
  share/p2p/discovery/discovery.go
  share/p2p/discovery/discovery_test.go
  share/p2p/discovery/metrics.go
  share/p2p/discovery/options.go
  share/p2p/peers/manager.go
  share/p2p/peers/manager_test.go
Labels: area:p2p, kind:feat

#2826 fix(docs): fix GetVerifiedRange doc
  docs/adr/adr-009-public-api.md
  nodebuilder/header/header.go
Labels: docs:godocs, kind:fix

#2832 chore(share/ipld): obliterate expensive ipld getter tracing
  share/ipld/get.go
  share/ipld/get_shares.go
  share/ipld/namespace_data.go
  share/ipld/nmt.go
Labels: area:shares, kind:chore

#2835 fix(share/p2p/peer-manager) fix race for hasPeerCh pointer read
  share/p2p/peers/pool.go
Labels: area:p2p, kind:fix

#2831 chore: bump to the official v1.0.0 tag of celestia-app
  go.mod
  go.sum
Labels: kind:deps, external

#2834 fix(share/eds): fix races in cache tests
  share/eds/blockstore.go
  share/eds/cache/accessor_cache_test.go
  share/eds/metrics.go
  share/eds/store.go
  share/eds/store_test.go
Labels: kind:testing, kind:fix

#2837 fix(modp2p): temporary disable quic
  nodebuilder/p2p/addrs.go
  nodebuilder/p2p/host.go
Labels: kind:fix

#2840 chore: adding mainnet chain id and setting as default
  nodebuilder/p2p/bootstrap.go
  nodebuilder/p2p/genesis.go
  nodebuilder/p2p/network.go
Labels: area:p2p, kind:chore

#2845 bug: fix duplicate docker build stages
  .github/workflows/docker-build-publish.yml
Labels: bug, kind:fix, external, github_actions

#2841 fix: removing chainid from default store name for mainnet
  cmd/flags_node.go
Labels: area:p2p, kind:fix

#2844 deps!: Bumps go-header
  core/exchange.go
  core/exchange_test.go
  core/listener_test.go
  das/daser_test.go
  docs/adr/adr-009-public-api.md
  go.mod
  go.sum
  nodebuilder/header/config.go
  nodebuilder/header/constructors.go
  nodebuilder/header/header.go
  nodebuilder/header/mocks/api.go
  nodebuilder/header/module.go
  nodebuilder/header/opts.go
  nodebuilder/header/service.go
  nodebuilder/settings.go
Labels: kind:deps, kind:break!

#2846 fix(share/getters): short-circuit on empty root in ShrexGetter
  share/getters/shrex.go
Labels: area:shares, kind:fix

#2853 fix(blob): properly wrap error in GetAll method
  blob/service.go
Labels: kind:fix, external

#2852 fix(core): Increase listener timeout to 3x block time
  core/listener.go
Labels: area:core_and_app, kind:fix

#2805 override organization pull_request_template.md
  .github/pull_request_template.md
Labels: kind:ci

#2855 (ci) matrix tests for different OS
  .github/workflows/go-ci.yml
  blob/service_test.go
Labels: kind:ci

#2868 update golangci-lint
  .github/workflows/go-ci.yml
  share/availability/test/corrupt_data.go
  share/eds/cache/metrics.go
Labels: kind:ci

#2870 fix(docgen): fix das naming for the openrpc spec
  nodebuilder/default_services.go
Labels: kind:fix

#2871 chore(nodebuilder/das): change daser module name to das
  nodebuilder/das/module.go
Labels: kind:chore

#2864 tests(share/byzantine): extend befp tests
  share/eds/byzantine/bad_encoding.go
  share/eds/byzantine/bad_encoding_test.go
Labels: kind:testing, kind:chore

#2869 signed binaries for goreleaser
  .github/workflows/ci_release.yml
  .goreleaser.yaml
Labels: kind:misc, kind:ci

#2877 chore: bump go-header
  go.mod
  go.sum
Labels: kind:deps, kind:chore

#2876 fix(core/listener): make listener to retry subscribing on errors
  core/listener.go
Labels: area:core_and_app, kind:fix

#2881 chore(deps): Bumps app to v1.3.0
  core/listener_test.go
  go.mod
  go.sum
Labels: kind:deps

#2806 (ci) update github actions ci to use a single GO_VERSION variable
  .github/workflows/ci_release.yml
  .github/workflows/go-ci.yml
Labels: kind:ci

#2872 refactor(nodebuilder/share/cmd)!: Take block height instead of `ExtendedHeader` as argument for share cmds
  nodebuilder/share/cmd/share.go
Labels: kind:break!, kind:refactor, external, area:cli

#2888 feat: celestia mainnet bootstrappers
  nodebuilder/p2p/bootstrap.go
Labels: kind:misc, external

#2889 feat(nodebuilder/p2p): Add mainnet genesis hash
  nodebuilder/p2p/genesis.go
Labels: area:p2p, kind:misc
