Repository celestiaorg/celestia-node, pull requests merged in 2023-07, with the labels that each got.

#2418 doc(share/p2p/shrexnd): Improve accuracy of RequestND description
  share/p2p/shrexnd/client.go
Labels: kind:doc, external

#2432 chore(nodebuilder/p2p)! Upgrade to mocha-3
  nodebuilder/p2p/genesis.go
  nodebuilder/p2p/network.go
Labels: kind:break!, external

#2435 fix: update the header hash in mocha-3 to be for height 15045
  nodebuilder/p2p/genesis.go
Labels: kind:fix, external

#2436 deps: bump go-header
  go.mod
  go.sum
Labels: kind:deps

#2434 chore: bump celestia-app to v1.0.0-rc8
  blob/helper.go
  core/eds.go
  core/eds_test.go
  core/exchange.go
  core/header_test.go
  core/listener.go
  go.mod
  go.sum
  nodebuilder/p2p/genesis.go
Labels: kind:deps, external

#2447 feat: use context in the common pipeline
  .github/workflows/docker-build-publish.yml
Labels: ci:actions, ci:docker, kind:fix, docker

#2456 fix(header): temporary disable skipping verification
  header/headertest/verify_test.go
  header/verify.go
  nodebuilder/p2p/genesis.go
Labels: area:header, kind:fix

#2408 share/befp: rework collecting and verifying the BEFP
  share/eds/byzantine/bad_encoding.go
  share/eds/byzantine/byzantine.go
  share/eds/byzantine/share_proof.go
Labels: area:shares, area:fraud, kind:misc

#2458 chore: bump celestia app v1.0.0-rc9
  core/eds_test.go
  go.mod
  go.sum
  header/header.go
  header/headertest/testing.go
  nodebuilder/share/constructors.go
  nodebuilder/share/share_test.go
  nodebuilder/tests/swamp/config.go
  share/availability/light/availability_test.go
  share/availability/test/testing.go
  share/eds/byzantine/bad_encoding_test.go
  share/eds/byzantine/share_proof_test.go
  share/eds/eds.go
  share/eds/eds_test.go
  share/eds/ods_test.go
  share/eds/retriever.go
  share/eds/retriever_test.go
  share/eds/store_test.go
  share/empty.go
  share/getters/getter_test.go
  share/getters/shrex_test.go
  share/getters/testing.go
  share/ipld/add.go
  share/ipld/get_shares_test.go
  share/ipld/nmt_test.go
  share/p2p/shrexeds/exchange_test.go
  share/p2p/shrexnd/exchange_test.go
Labels: kind:deps

#2467 fix(lint): fix importing
  share/getters/testing.go
Labels: kind:fix

#2469 cmd: rpc.go fix error parsing height message
  cmd/celestia/rpc.go
Labels: external, kind:chore, area:cli

#2466 fix(nodebuilder): fix nil pointer exception and simplify synchronization
  nodebuilder/store.go
Labels: kind:fix

#2473 chore(share/p2p/discovery): demote disc peers log to debug
  share/p2p/discovery/discovery.go
Labels: kind:chore

#2472 chore(deps): bump otel, go-header, and go-fraud
  cmd/flags_misc.go
  das/metrics.go
  go.mod
  go.sum
  nodebuilder/node/metrics.go
  nodebuilder/settings.go
  share/getters/shrex.go
  share/p2p/discovery/metrics.go
  share/p2p/metrics.go
  share/p2p/peers/metrics.go
  state/metrics.go
Labels: kind:deps, area:metrics

#2468 chore: move versioning outside the main package
  Makefile
  cmd/celestia/util.go
  cmd/celestia/version.go
  cmd/env.go
  cmd/flags_misc.go
  nodebuilder/node/buildInfo.go
  nodebuilder/node_test.go
  nodebuilder/settings.go
Labels: kind:misc

#2475 refactor(share/availability): don't log error canceled operation
  share/availability/full/availability.go
  share/availability/light/availability.go
Labels: area:shares, kind:refactor

#2477 feat(nodebuilder): Invoke traces from fx
  cmd/flags_misc.go
  nodebuilder/node_test.go
  nodebuilder/settings.go
Labels: kind:feat, area:metrics

#2483 fix: remove root from traces
  share/eds/retriever.go
  share/eds/store.go
  share/getters/cascade.go
  share/getters/ipld.go
  share/getters/shrex.go
  share/getters/store.go
  share/getters/tee.go
  share/getters/utils.go
  share/ipld/namespace_data.go
Labels: kind:fix

#2383 feat(share/byzantine): handle additional cases in befp validation
  share/eds/byzantine/bad_encoding.go
Labels: area:shares, area:fraud, kind:feat

#2504 fix(nodebuilder/tests/swamp): Bump timeout
  nodebuilder/tests/swamp/swamp.go
Labels: swamp, kind:fix

#2509 dep: update nmt version
  go.mod
  go.sum
Labels: kind:deps

#2464 feat: new metrics - deployment dashboard
  nodebuilder/node/metrics.go
Labels: enhancement, kind:misc, area:metrics

#2445 fix(share/availability): update availability ErrNotAvailable handling logic
  share/availability/full/availability.go
  share/availability/full/availability_test.go
Labels: area:shares, kind:fix

#2514 fix: check for namespace version 0
  share/namespace.go
  share/namespace_test.go
Labels: kind:fix, external

#2518 fix(share/eds): remove Has() and Sync() badger calls in inverted index
  share/eds/inverted_index.go
  share/eds/inverted_index_test.go
Labels: area:shares, area:storage, kind:fix
