Repository celestiaorg/celestia-node, pull requests merged in 2023-09, with the labels that each got.

#2641 chore(deps): bump golanci-lint workflow
  .github/workflows/go-ci.yml
  .golangci.yml
  cmd/celestia/rpc.go
  nodebuilder/config.go
  state/core_access.go
Labels: kind:deps, kind:chore

#2642 feat(share/eds) add dagstore shards status metric
  share/eds/metrics.go
Labels: area:shares, area:storage, kind:feat

#2633 refactor(share)!: have NamespacedShares fields use snake_case in JSON
  share/getter.go
Labels: area:shares, kind:refactor

#2584 tests(swamp): befp testing
  das/daser_test.go
  header/headertest/fraud/testing.go
  header/headertest/testing.go
  nodebuilder/fraud/lifecycle.go
  nodebuilder/p2p/opts.go
  nodebuilder/tests/fraud_test.go
  nodebuilder/tests/swamp/swamp.go
  share/eds/edstest/testing.go
  share/getters/cascade.go
  share/getters/ipld.go
Labels: swamp, kind:fix

#2296 feat: local docker telemetry infra
  Makefile
  README.md
  docker/telemetry/docker-compose.yml
  docker/telemetry/grafana/datasources/config.yml
  docker/telemetry/loki/config.yml
  docker/telemetry/otel-collector/config.yml
  docker/telemetry/prometheus/prometheus.yml
  docker/telemetry/promtail/config.yml
Labels: area:repository, kind:feat

#2599 feat(cmd/rpc): add commands for the p2p module
  cmd/celestia/blob.go
  cmd/celestia/p2p.go
  cmd/celestia/rpc.go
Labels: area:rpc, kind:feat

#2646 chore!: bump celestia-app to v1.0.0-rc13
  go.mod
  go.sum
Labels: kind:deps, kind:break!

#2648 fix(blob): typo, sumitter -> submitter
  blob/service.go
Labels: area:node, kind:fix, area:blob

#2166 chore(nodebuilder/tests): Clean up integration tests in `p2p_test`
  nodebuilder/tests/p2p_test.go
  nodebuilder/tests/sync_test.go
Labels: swamp, kind:chore

#2652 refactor(blob): removing jsonProof
  blob/blob.go
  blob/service_test.go
Labels: kind:fix, area:blob

#2651 feat(rpc): add daser cmd
  cmd/celestia/das.go
  cmd/celestia/rpc.go
Labels: area:rpc, kind:feat

#2595 chore(deps): migrate to boxo
  Makefile
  blob/service_test.go
  das/daser_test.go
  go.mod
  go.sum
  header/headertest/fraud/testing.go
  nodebuilder/node.go
  nodebuilder/p2p/ipld.go
  nodebuilder/p2p/module.go
  nodebuilder/share/constructors.go
  share/availability/cache/availability_test.go
  share/availability/cache/testing.go
  share/availability/full/testing.go
  share/availability/light/testing.go
  share/availability/test/testing.go
  share/eds/adapters.go
  share/eds/byzantine/bad_encoding_test.go
  share/eds/byzantine/byzantine.go
  share/eds/byzantine/share_proof.go
  share/eds/byzantine/share_proof_test.go
  share/eds/retriever.go
  share/eds/retriever_test.go
  share/getters/getter_test.go
  share/getters/ipld.go
  share/getters/utils.go
  share/ipld/add.go
  share/ipld/blockserv.go
  share/ipld/get.go
  share/ipld/get_shares.go
  share/ipld/get_shares_test.go
  share/ipld/namespace_data.go
  share/ipld/nmt.go
  share/ipld/nmt_adder.go
Labels: kind:chore

#2657 chore(go.mod): bump go-header
  go.mod
  go.sum
Labels: kind:deps

#2507 feat(nodebuilder/header): Bootstrap from previously seen peers
  go.mod
  go.sum
  libs/pidstore/pidstore.go
  libs/pidstore/pidstore_test.go
  nodebuilder/header/constructors.go
  nodebuilder/header/module.go
  nodebuilder/header/module_test.go
  nodebuilder/p2p/misc.go
Labels: area:p2p, kind:feat

#2660 feat(modp2p): listen on WebTransport by default
  nodebuilder/p2p/config.go
Labels: kind:feat

#2613 fix(share/eds): skip concurrent writes on edsstore Put
  share/eds/store.go
  share/eds/store_test.go
Labels: area:storage, kind:fix

#2640 chore(lint/sort-imports): fix absolute path for sort-imports
  Makefile
Labels: kind:fix

#2481 chore: cleanup usage of `share.Root`(DAH)
  core/eds_test.go
  core/header_test.go
  core/listener_test.go
  das/coordinator_test.go
  das/daser_test.go
  header/header.go
  header/headertest/testing.go
  nodebuilder/share/share_test.go
  share/availability.go
  share/availability/cache/availability.go
  share/availability/cache/availability_test.go
  share/availability/light/availability_test.go
  share/availability/test/testing.go
  share/eds/byzantine/bad_encoding_test.go
  share/eds/eds.go
  share/eds/eds_test.go
  share/eds/edstest/testing.go
  share/eds/store.go
  share/eds/store_test.go
  share/empty.go
  share/getters/getter_test.go
  share/getters/shrex_test.go
  share/getters/testing.go
  share/p2p/shrexeds/exchange_test.go
  share/p2p/shrexnd/exchange_test.go
Labels: area:shares, kind:chore

#2630 improvement!(blob/service): add options to submit
  blob/service.go
  cmd/celestia/blob.go
  nodebuilder/blob/blob.go
  nodebuilder/blob/mocks/api.go
  nodebuilder/node/admin.go
  nodebuilder/tests/api_test.go
  nodebuilder/tests/blob_test.go
Labels: kind:break!, kind:misc, area:blob

#2668 chore!: bump mocha chain with new bootstrappers and genesis hash
  nodebuilder/p2p/bootstrap.go
  nodebuilder/p2p/genesis.go
  nodebuilder/p2p/network.go
Labels: kind:misc, external

#2644 feat(headertest): Validate exact error types in header tests
  header/header.go
  header/headertest/verify_test.go
Labels: errors, kind:testing, external

#2662 chore: bump celestia-app to v1.0.0-rc14
  go.mod
  go.sum
Labels: kind:deps

#2676 chore: bump libp2p
  go.mod
  go.sum
Labels: kind:chore

#2677 fix(modshare): start peer manager after Syncer
  nodebuilder/share/module.go
Labels: kind:fix

#2669 feat(cmd/blob): add fee and gasLimit flags
  cmd/celestia/blob.go
Labels: area:rpc, kind:feat

#2671 chore(docs): add submit options for blob.Submit
  openrpc.json
Labels: kind:docs

#2692 chore(nodebuilder/p2p): BlockTime from 15 sec --> 10 sec
  das/options.go
  nodebuilder/p2p/network.go
Labels: kind:chore

#2678 refactor(nodebuilder/header): get rid of `InitStore`
  nodebuilder/header/constructors.go
  nodebuilder/header/module.go
  nodebuilder/header/module_test.go
  nodebuilder/testing.go
Labels: kind:misc

#2693 chore: fix unknown in ghcr registry
  Dockerfile
Labels: ci:docker, kind:misc, external

#2696 chore: bump docker ci to v0.2.3
  .github/workflows/docker-build-publish.yml
Labels: ci:actions, ci:docker, external, kind:ci

#2667 Stale issue github workflow
  .github/workflows/stale.yml
Labels: kind:chore

#2664 feat(rpc): add share cmd
  cmd/celestia/rpc.go
  cmd/celestia/share.go
Labels: area:rpc, kind:feat

#2699 refactor(swamp): use RPC client instead of service pointers
  nodebuilder/node.go
  nodebuilder/tests/api_test.go
  nodebuilder/tests/blob_test.go
  nodebuilder/tests/fraud_test.go
  nodebuilder/tests/nd_test.go
  nodebuilder/tests/p2p_test.go
  nodebuilder/tests/reconstruct_test.go
  nodebuilder/tests/sync_test.go
Labels: kind:testing, swamp

#2661 Goreleaser
  .github/workflows/ci_release.yml
  .goreleaser.yaml
  .yamllint.yml
  Makefile
Labels: external, kind:ci

#2705 fix(shrexeds): close stream
  share/p2p/shrexeds/client.go
Labels: area:shares, area:p2p, kind:fix

#2701 feat(rpc): add admin cmd
  cmd/celestia/admin.go
  cmd/celestia/logs.go
  cmd/celestia/rpc.go
Labels: area:rpc, kind:feat

#2691 feat(rpc): add state cmd
  cmd/celestia/rpc.go
  cmd/celestia/state.go
Labels: area:rpc, kind:feat

#2612 feat(share/eds): Rework accessor cache
  go.mod
  nodebuilder/store_test.go
  share/eds/accessor_cache.go
  share/eds/blockstore.go
  share/eds/blockstore_test.go
  share/eds/cache/accessor_cache.go
  share/eds/cache/accessor_cache_test.go
  share/eds/cache/cache.go
  share/eds/cache/metrics.go
  share/eds/cache/noop.go
  share/eds/metrics.go
  share/eds/ods_test.go
  share/eds/store.go
  share/eds/store_test.go
  share/eds/utils.go
  share/getters/store.go
  share/p2p/shrexeds/server.go
Labels: area:storage, kind:feat

#2656 feat(share/store/cache): Split accessor cache into recent and blockstore
  share/eds/blockstore.go
  share/eds/cache/doublecache.go
  share/eds/store.go
  share/eds/store_test.go
  share/eds/utils.go
Labels: area:shares, area:storage, kind:feat

#2717 openrpc.json: Detect drift in openrpc spec
  .github/workflows/ci_release.yml
  .github/workflows/docs.yml
  Makefile
  openrpc.json
Labels: documentation, ci:actions, kind:ci, github_actions

#2722 chore(dependabot): add otel group to dependabot
  .github/dependabot.yml
Labels: kind:deps

#2008 docs: Add share p2p documentation
  blob/service.go
  share/p2p/doc.go
  share/p2p/peers/doc.go
  share/p2p/shrexeds/doc.go
  share/p2p/shrexnd/doc.go
  share/p2p/shrexsub/doc.go
Labels: kind:misc, kind:docs

#2723 feat(share/eds/cache): Add accessor cache refs counter
  das/options.go
  nodebuilder/blob/mocks/api.go
  share/eds/cache/accessor_cache.go
  share/eds/cache/accessor_cache_test.go
  share/eds/cache/metrics.go
  share/eds/cache/noop.go
  share/eds/store.go
  share/eds/store_test.go
Labels: area:shares, kind:feat

#2724 feat(share/eds/store): expose eds store params
  core/exchange_test.go
  libs/edssser/edssser.go
  nodebuilder/share/config.go
  nodebuilder/share/module.go
  nodebuilder/share/share_test.go
  nodebuilder/store_test.go
  nodebuilder/tests/fraud_test.go
  nodebuilder/tests/swamp/swamp.go
  share/eds/store.go
  share/eds/store_options.go
  share/eds/store_test.go
  share/getters/getter_test.go
  share/getters/shrex_test.go
  share/p2p/peers/options.go
  share/p2p/shrexeds/exchange_test.go
  share/p2p/shrexnd/exchange_test.go
Labels: area:shares, kind:feat

#2728 deps!: bump nmt, breaking JSON RPC return types including nmt Proofs
  go.mod
  go.sum
Labels: kind:deps, kind:break!

#2726 refactoring(full/availability): removing TeeGetter, storing via SharesAvailable
  das/daser_test.go
  nodebuilder/share/constructors.go
  nodebuilder/tests/nd_test.go
  share/availability/cache/testing.go
  share/availability/full/availability.go
  share/availability/full/availability_test.go
  share/availability/full/testing.go
  share/getters/getter_test.go
  share/getters/store.go
  share/getters/tee.go
  share/ipld/corrupted_data_test.go
Labels: area:storage, kind:refactor

#2746 fix(full/availability): short-circuiting SharesAvailable on empty DAH
  share/availability/full/availability.go
Labels: area:shares, kind:fix

#2752 fix: improve ErrNoStateAccess message
  nodebuilder/state/stub.go
Labels: kind:fix, area:api

#2706 refactor(cmd): extract rpc cmds
  cmd/celestia/bridge.go
  cmd/celestia/cmd_test.go
  cmd/celestia/das.go
  cmd/celestia/full.go
  cmd/celestia/light.go
  cmd/celestia/rpc.go
  cmd/celestia/util.go
  cmd/rpc.go
  cmd/util.go
  cmd/util_test.go
  nodebuilder/blob/cmd/blob.go
  nodebuilder/das/cmd/das.go
  nodebuilder/header/cmd/header.go
  nodebuilder/node/cmd/node.go
  nodebuilder/p2p/cmd/p2p.go
  nodebuilder/share/cmd/share.go
  nodebuilder/state/cmd/state.go
Labels: area:rpc, kind:chore

#2741 refactor(availability): merging cache.ShareAvailability and light.ShareAvailability
  nodebuilder/share/constructors.go
  nodebuilder/share/module.go
  share/availability/cache/availability.go
  share/availability/cache/availability_test.go
  share/availability/cache/testing.go
  share/availability/light/availability.go
  share/availability/light/availability_test.go
  share/availability/light/testing.go
Labels: area:shares, kind:refactor

#2758 refactor(share/discovery): decrease default Advertisement interval
  share/p2p/discovery/options.go
Labels: area:p2p, kind:refactor

#2753 chore!: bump core and app
  go.mod
  go.sum
Labels: kind:deps, kind:break!, external

#2755 refactor(rpc/blob) extend docs in blob
  nodebuilder/blob/cmd/blob.go
Labels: documentation, area:rpc, kind:refactor

#2761 fix(share/p2p/peers): Prevent making pools for nil DataHash
  share/p2p/peers/manager_test.go
  share/p2p/shrexsub/pubsub.go
  share/p2p/shrexsub/pubsub_test.go
Labels: area:shares, area:p2p, kind:fix

#2763 ignore dependabot in issue-label-automation/automate-labels workflow
  .github/workflows/issue-label-automation.yml
Labels: ci:actions, kind:ci, github_actions
