Repository celestiaorg/celestia-node, pull requests merged in 2024-10, with the labels that each got.

#3732 fix(blob): add fixes along with the fuzzers that discovered them
  blob/blob.go
  blob/blob_fuzz_test.go
  blob/commitment_proof.go
  blob/repro_test.go
  blob/testdata/fuzz-corpus/verify-626c6f627320746861742074616b65203220736861726573.json
  blob/testdata/fuzz-corpus/verify-626c6f627320746861742074616b65206c657373207468616e2061207368617265.json
  blob/testdata/fuzz-corpus/verify-626c6f627320746861742074616b65207e313020736861726573.json
  blob/testdata/fuzz-corpus/verify-6c6172676520626c6f6273207e31303020736861726573.json
  blob/testdata/fuzz-corpus/verify-6c6172676520626c6f6273207e31353020736861726573.json
  blob/testdata/fuzz-corpus/verify-6c6172676520626c6f6273207e33303020736861726573.json
  blob/testdata/fuzz-corpus/verify-76657279206c6172676520626c6f6273207e3135303020736861726573.json
  blob/testdata/fuzz/FuzzCommitmentProofVerify/582528ddfad69eb5
  blob/testdata/fuzz/FuzzCommitmentProofVerify/6a2b4b982dc67bf9
  blob/testdata/fuzz/FuzzCommitmentProofVerify/8093511184ad3e25
  blob/testdata/fuzz/FuzzCommitmentProofVerify/c23296029c66526c
  blob/testdata/fuzz/FuzzCommitmentProofVerify/ea1afcc1fa86d415
  blob/testdata/fuzz/FuzzCommitmentProofVerify/fa5be9420bbacd9a
  blob/testdata/fuzz/FuzzProofEqual/8093511184ad3e25
Labels: kind:testing, external

#3790 fix: remove godebug asynctimerchan=1
  go.mod
Labels: kind:fix

#3787 .github/workflows: docker build publish on anything with a version `v`
  .github/workflows/docker-build-publish.yml
Labels: ci:actions, ci:docker, kind:misc, kind:ci

#3633 feat: keep using the namespace proof for GetBlob and GetAll
  blob/blob.go
  blob/parser.go
  blob/service.go
  blob/service_test.go
Labels: kind:feat, external

#3780 feat(cel-shed/p2p): bootstrapper probe tool
  Dockerfile
  cmd/cel-shed/p2p.go
  nodebuilder/fraud/constructors.go
  nodebuilder/fraud/module.go
  nodebuilder/p2p/network.go
Labels: area:p2p, kind:feat, external

#3635 test(nodebuilder): disable TestArchivalBlobSync
  nodebuilder/tests/prune_test.go
Labels: kind:testing

#3750 feat(nodebuilder/da): implement go-da v0.6.1 changes
  go.mod
  go.sum
  nodebuilder/da/da.go
  nodebuilder/da/service.go
  nodebuilder/tests/da_test.go
Labels: kind:feat, external

#3797 ci: fix linter
  blob/service_test.go
Labels: kind:ci

#3664 Fix start with chain id mismatch
  nodebuilder/state/core.go
  share/shwap/p2p/shrex/error.go
  state/core_access.go
  state/core_access_test.go
  state/integration_test.go
  store/file/file.go
Labels: kind:feat, external

#3748 chore(ci): group updates
  .github/dependabot.yml
Labels: kind:ci

#3580 feat(cmd): adding timeout flag
  cmd/rpc.go
Labels: kind:feat, external

#3794 chore(.github): Remove ryan from CODEOWNERS
  .github/CODEOWNERS
Labels: kind:misc

#3811 chore: bump p2p deps
  go.mod
  go.sum
Labels: area:p2p, kind:chore

#3808 fix(docker): set addr flags to 0.0.0.0 in entrypoint file
  docker/entrypoint.sh
Labels: kind:fix, external

#3789 fix(modshare): ensure Bitswap Getter is started
  nodebuilder/share/constructors.go
  nodebuilder/share/module.go
Labels: kind:fix, shwap

#3788 fix(shwap/store): avoid double cache check
  store/store.go
  store/store_cache.go
Labels: kind:fix, shwap

#3818 chore(logs): increase verbosity for bitswap log
  logs/logs.go
Labels: kind:chore

#3831 fix(share/p2p/bitswap): lower bitswap log severity
  share/shwap/p2p/bitswap/block_fetch.go
Labels: kind:fix

#3826 chore(go.mod): Bump celestia-app to v2.2.0 release in main
  go.mod
  go.sum
Labels: kind:deps

#3844 fix(store): check if link exists on write
  store/store.go
  store/store_test.go
Labels: area:storage, kind:fix

#3810 chore: remove some TODOs
  nodebuilder/da/da.go
  nodebuilder/das/das.go
  nodebuilder/fraud/fraud.go
  nodebuilder/header/header.go
  nodebuilder/header/service.go
  nodebuilder/p2p/p2p.go
  nodebuilder/share/config.go
  nodebuilder/share/p2p_constructors.go
  nodebuilder/share/share.go
  nodebuilder/state/state.go
  share/availability/light/availability.go
  share/availability/light/options.go
  share/share.go
  share/shwap/p2p/shrex/peers/manager_test.go
  share/shwap/p2p/shrex/peers/options.go
  share/shwap/p2p/shrex/shrex_getter/shrex_test.go
Labels: kind:break!, kind:chore

#3860 fix(eds/cache): Fix prealloc for proof nodes
  share/ipld/nmt_adder.go
Labels: kind:fix

#3838 feat(modp2p): close peer connections after successful blocking
  nodebuilder/p2p/p2p.go
  nodebuilder/p2p/p2p_test.go
Labels: area:p2p, kind:fix, external

#3813 feat(shwap/bitswap): use new option for optimized Has check
  share/shwap/p2p/bitswap/bitswap.go
  share/shwap/p2p/bitswap/block_fetch_test.go
  share/shwap/p2p/bitswap/block_store.go
Labels: kind:feat, shwap

#3847 feat(store): Test all put funcs
  store/store_test.go
Labels: area:storage, kind:feat

#3861 feat(store): use use relative path for empty blocks symlinks
  store/store.go
Labels: area:storage, kind:feat

#3857 fix(store/cache): unstick cache metrics names
  store/cache/metrics.go
Labels: area:storage, kind:fix, area:metrics

#3848 fix(docs) update txResponse in docs
  api/docgen/exampledata/txResponse.json
Labels: kind:docs

#3863 refactor(store): write actual share size to ods
  store/file/ods.go
Labels: area:storage, kind:refactor

#3865 fix(store/file): wait for q4 to be written before returning
  store/file/ods_q4.go
Labels: area:storage, kind:fix

#3855 fix(ci,release): run on any new tag or trigger manually
  .github/workflows/ci_release.yml
  .goreleaser.yaml
Labels: kind:ci

#3866 chore(ci): remove release tracking epic ci
  .github/workflows/create_release_tracking_epic.yml
Labels: external, kind:ci

#3867 fix(share/ipld): use bits.Len64 instead of math.Log2 in newProofCollector
  share/ipld/proof_collector.go
Labels: kind:fix, external

#3872 chore(go.mod): bump header
  core/exchange.go
  go.mod
  go.sum
Labels: kind:deps

#3875 fix(nodebuilder/p2p): lint
  nodebuilder/p2p/misc.go
Labels: kind:fix

#3868 refactor(nodebuilder): add archival flag
  cmd/util.go
  nodebuilder/pruner/flags.go
  nodebuilder/pruner/module.go
Labels: kind:refactor

#3869 refactor(api): add gateway deprecation notice
  nodebuilder/gateway/flags.go
  nodebuilder/gateway/flags_test.go
  nodebuilder/gateway/module.go
Labels: kind:refactor

#3870 !refactor(api/share): use height in share module
  api/gateway/availability.go
  api/gateway/share.go
  nodebuilder/node_test.go
  nodebuilder/share/cmd/share.go
  nodebuilder/share/mocks/api.go
  nodebuilder/share/share.go
  nodebuilder/tests/nd_test.go
  nodebuilder/tests/prune_test.go
  nodebuilder/tests/reconstruct_test.go
  nodebuilder/tests/sync_test.go
Labels: kind:break!, area:api, kind:refactor

#3877 fix(ci): GH_TOKEN for upload-docs
  .github/workflows/ci_release.yml
Labels: kind:fix, kind:ci

#3885 fix: wrong network error
  state/core_access.go
Labels: errors, kind:fix, external

#3828 fix(pruner): fix find algo so that it does not pass a malformed range into `GetRangeByHeight` call
  pruner/find.go
Labels: kind:fix

#3893 chore(share): remove unused ShareWithProof
  share/share.go
Labels: kind:chore

#3888 fix(share/availability): propagate errors from light availability properly
  share/availability/light/availability.go
Labels: kind:fix

#3882 fix(ci): do not version_bump
  .github/workflows/ci_release.yml
Labels: kind:ci

#3897 fix(shwap/shrex): enable recovery middleware in shrex server
  share/shwap/p2p/shrex/shrexeds/server.go
  share/shwap/p2p/shrex/shrexnd/server.go
Labels: kind:fix

#3898 chore: remove unused code
  api/gateway/state.go
  header/serde.go
  share/eds/validation.go
  share/empty.go
  share/ipld/nmt.go
  share/ipld/test_helpers.go
  share/ipld/utils.go
  share/root.go
Labels: kind:chore

#3889 fix(DASer): Log sampling errors in DASer
  das/worker.go
  share/availability/light/availability.go
Labels: kind:fix, area:das

#3895 refactor(share/availability): simplify light availability
  share/availability/full/availability.go
  share/availability/light/availability.go
  share/availability/light/availability_test.go
  share/availability/light/sample.go
  share/availability/light/sample_test.go
Labels: kind:break!, kind:refactor

#3883 fix(availability): prevent parallel availability calls
  libs/utils/sessions.go
  libs/utils/sessions_test.go
  share/availability/light/availability.go
  share/availability/light/availability_test.go
Labels: kind:fix
