Repository celestiaorg/celestia-node, pull requests merged in 2024-04, with the labels that each got.

#3289 deps: Bump libp2p dependencies
  go.mod
  go.sum
Labels: kind:deps

#3290 deps: bump go-header
  go.mod
  go.sum
Labels: kind:deps

#3294 fix(nodebuilder/share/cmd): Fix parsing of uint for height in `share` rpc CLI commands
  nodebuilder/share/cmd/share.go
Labels: area:rpc, kind:fix, area:cli

#3291 feat(ci): call reusable workflow to track the release deployments and notify devops
  .github/workflows/create_release_tracking_epic.yml
Labels: kind:feat, external, kind:ci

#3280 fix(p2p/discovery): Unregister metrics callback on close
  share/p2p/discovery/discovery.go
  share/p2p/discovery/metrics.go
Labels: kind:fix

#3297 fix(nodebuilder): return fx error if theres an error getting keystore or constructing signer
  nodebuilder/module.go
  nodebuilder/testing.go
Labels: area:node, kind:fix

#3304 feat(state): enable fee granting
  cmd/util.go
  nodebuilder/state/cmd/state.go
  nodebuilder/state/config.go
  nodebuilder/state/core.go
  nodebuilder/state/flags.go
  nodebuilder/state/mocks/api.go
  nodebuilder/state/module.go
  nodebuilder/state/state.go
  nodebuilder/state/stub.go
  state/core_access.go
Labels: area:state, kind:feat

#3312 chore(deps): bump .github version for release tracking epic
  .github/workflows/create_release_tracking_epic.yml
Labels: kind:deps

#3305 feat(share/eds): Store nmt nodes on failed reconstruction
  share/eds/retriever.go
Labels: area:p2p, kind:feat

#3246 feat(cmd/rpc): Automatically detect running node for RPC requests
  cmd/cel-key/node_types.go
  cmd/flags_node.go
  cmd/rpc.go
  nodebuilder/node/type.go
  nodebuilder/p2p/flags.go
  nodebuilder/p2p/network.go
  nodebuilder/rpc/config.go
  nodebuilder/store.go
  nodebuilder/store_test.go
Labels: kind:feat, external

#3315 fix(core): Unsubscribe from new block event on Stop in listener
  core/listener.go
Labels: area:core_and_app, kind:fix

#3298 feat(state): Integrate new Signer for concurrent tx submission
  go.mod
  go.sum
  nodebuilder/module.go
  nodebuilder/state/core.go
  nodebuilder/state/keyring.go
  nodebuilder/state/module.go
  nodebuilder/state/opts.go
  nodebuilder/testing.go
  nodebuilder/tests/blob_test.go
  nodebuilder/tests/swamp/swamp.go
  state/core_access.go
  state/core_access_test.go
  state/integration_test.go
Labels: area:state, kind:feat, external

#3328 feat(share/p2p/shrex): add recovery middleware to shrex-nd and shrex-eds servers
  share/p2p/recovery.go
  share/p2p/shrexeds/server.go
  share/p2p/shrexnd/server.go
Labels: kind:feat

#3327 feat(share/p2p/shrexsub): add recovery to shrexSub
  share/p2p/shrexsub/pubsub.go
Labels: kind:feat

#3326 deps: bump go-header and go-fraud
  das/daser_test.go
  go.mod
  go.sum
  nodebuilder/fraud/constructors.go
  nodebuilder/header/constructors.go
  nodebuilder/header/module.go
  nodebuilder/header/service.go
Labels: kind:deps

#3316 deps: bump celestia-app
  go.mod
  go.sum
Labels: kind:deps

#3281 fix(metrics): Unregister callback on stop for several metrics implementations
  das/daser.go
  das/metrics.go
  nodebuilder/node/metrics.go
  nodebuilder/settings.go
  share/eds/cache/accessor_cache.go
  share/eds/cache/cache.go
  share/eds/cache/doublecache.go
  share/eds/cache/metrics.go
  share/eds/cache/noop.go
  share/eds/metrics.go
  share/eds/store.go
  share/p2p/discovery/discovery.go
  share/p2p/peers/manager.go
  share/p2p/peers/metrics.go
  state/metrics.go
Labels: kind:fix, area:metrics

#3306 fix!(share/byzantine): use any available axis for befp nmt proofs construction
  share/eds/byzantine/bad_encoding.go
  share/eds/byzantine/bad_encoding_test.go
  share/eds/byzantine/byzantine.go
  share/eds/byzantine/pb/share.pb.go
  share/eds/byzantine/pb/share.proto
  share/eds/byzantine/share_proof.go
  share/eds/byzantine/share_proof_test.go
  share/eds/retriever.go
  share/eds/retriever_test.go
Labels: area:shares, kind:break!, kind:fix

#3330 refactor(share/sha-256): Consolidate SHA-256 Hash Function Usage
  blob/service_test.go
  share/eds/byzantine/bad_encoding_test.go
  share/eds/byzantine/share_proof.go
  share/eds/eds.go
  share/getter.go
  share/ipld/get_shares_test.go
  share/ipld/nmt.go
  share/share.go
Labels: kind:refactor, external

#3332 chore(fmt/linters): enable nilerr, nilnil, nolintlint and fix related issues
  .golangci.yml
  core/eds.go
  core/eds_test.go
  das/daser_test.go
  nodebuilder/fraud/lifecycle.go
  nodebuilder/node/metrics.go
  share/eds/blockstore.go
  share/p2p/discovery/discovery.go
  state/core_access.go
Labels: kind:chore

#3334 chore(linters): add errorlint
  .golangci.yml
  api/gateway/availability.go
  blob/service.go
  cmd/rpc.go
  das/subscriber.go
  nodebuilder/blob/cmd/blob.go
  nodebuilder/header/cmd/header.go
  nodebuilder/header/service.go
  nodebuilder/p2p/addrs.go
  nodebuilder/p2p/config.go
  nodebuilder/state/cmd/state.go
  pruner/checkpoint.go
  share/eds/ods.go
  share/eds/store.go
  share/p2p/shrexeds/client.go
  share/p2p/shrexnd/client.go
Labels: kind:chore

#3333 chore(linter): add 6 more linteres
  .golangci.yml
  api/docgen/examples.go
  api/docgen/openrpc.go
  blob/blob.go
  cmd/cel-shed/p2p.go
  das/coordinator_test.go
  nodebuilder/fraud/lifecycle.go
  share/eds/retriever_no_race_test.go
  share/getters/shrex_test.go
  share/p2p/discovery/discovery_test.go
  share/p2p/peers/timedqueue_test.go
  state/core_access.go
Labels: kind:chore

#3338 chore: Update Tendermint Telemetry Broken Link
  docs/adr/adr-010-incentivized-testnet-monitoring.md
Labels: external, kind:chore
