Repository celestiaorg/celestia-node, pull requests merged in 2024-09, with the labels that each got.

#3704 feat: mocha bootstrapper now with dnsaddr
  nodebuilder/p2p/bootstrap.go
Labels: external, kind:chore

#3706 feat(chore): Add the Pops.one bootstrapper to the Mocha test network
  nodebuilder/p2p/bootstrap.go
Labels: external, kind:chore

#3708 Add Qubelabs Bootstrapper for Mocha
  nodebuilder/p2p/bootstrap.go
Labels: external, kind:chore

#3712 chore(swamp): skip fraud test until a better day
  Makefile
  nodebuilder/tests/fraud_test.go
Labels: kind:chore

#3714 chore(go.mod): use toolchain version in go.mod
  go.mod
Labels: kind:chore

#3713 fix(logs): bitswap logger names broke in latest version bump, updated
  logs/logs.go
Labels: kind:fix

#3672 chore(p2p/shrexsub) increase timeout for flaky shrexsub test
  share/p2p/shrexsub/pubsub_test.go
Labels: kind:fix

#3700 chore(ci): run unit-tests in parallel with lint
  .github/workflows/go-ci.yml
Labels: kind:ci

#3616 feat(shwap): Add discovery version
  nodebuilder/p2p/config.go
  nodebuilder/p2p/module.go
  nodebuilder/p2p/routing.go
  nodebuilder/share/p2p_constructors.go
  nodebuilder/tests/helpers_test.go
  share/shwap/p2p/discovery/dht.go
  share/shwap/p2p/discovery/discovery.go
  share/shwap/p2p/discovery/discovery_test.go
  share/shwap/p2p/shrex/peers/manager_test.go
Labels: kind:feat, shwap

#3722 fix(shwap/bitswap): correct protocol id
  share/shwap/p2p/bitswap/bitswap.go
Labels: kind:break!, kind:fix, shwap

#3680 feat(shwap/store): Add q4 trimming support in store
  pruner/full/pruner.go
  store/metrics.go
  store/store.go
  store/store_test.go
Labels: kind:feat, shwap

#3735 fix(store/odsq4): fix order of opened flag stored
  store/file/ods_q4.go
Labels: kind:fix, shwap

#3736 fix(store/ods): fix full ods caching
  store/file/ods.go
Labels: kind:fix, shwap

#3739 feat(nodebuilder): Blockstore cache params
  nodebuilder/share/bitswap.go
  nodebuilder/share/config.go
  nodebuilder/share/module.go
  store/store_cache.go
Labels: kind:feat, shwap

#3738 refactor(shwap): Remove new_eds folder
  blob/service_test.go
  share/eds/accessor.go
  share/eds/axis_half.go
  share/eds/axis_half_test.go
  share/eds/close_once.go
  share/eds/close_once_test.go
  share/eds/nd.go
  share/eds/nd_test.go
  share/eds/proofs_cache.go
  share/eds/proofs_cache_test.go
  share/eds/read.go
  share/eds/rsmt2d.go
  share/eds/rsmt2d_test.go
  share/eds/share_reader.go
  share/eds/share_reader_test.go
  share/eds/testing.go
  share/eds/validation.go
  share/eds/validation_test.go
  share/shwap/p2p/bitswap/block.go
  share/shwap/p2p/bitswap/block_fetch_test.go
  share/shwap/p2p/bitswap/block_store.go
  share/shwap/p2p/bitswap/block_test.go
  share/shwap/p2p/bitswap/row_block.go
  share/shwap/p2p/bitswap/row_namespace_data_block.go
  share/shwap/p2p/bitswap/sample_block.go
  share/shwap/p2p/shrex/shrexeds/client.go
  share/shwap/p2p/shrex/shrexeds/server.go
  share/shwap/p2p/shrex/shrexnd/server.go
  share/shwap/row_namespace_data_test.go
  share/shwap/sample_test.go
  store/cache/accessor_cache.go
  store/cache/accessor_cache_test.go
  store/cache/cache.go
  store/cache/doublecache.go
  store/cache/noop.go
  store/file/ods.go
  store/file/ods_q4.go
  store/file/ods_q4_test.go
  store/file/ods_test.go
  store/file/q4.go
  store/file/square.go
  store/getter.go
  store/store.go
  store/store_cache.go
Labels: kind:refactor, shwap

#3737 refactor(share/eds): various accessor testing suite improvements
  share/eds/testing.go
  store/file/ods_q4_test.go
  store/file/ods_test.go
Labels: kind:refactor, shwap

#3740 fix(core): fix flaky generateNonEmptyBlocks
  core/exchange_test.go
Labels: kind:fix, shwap

#3742 fix(blob/service): return error from GetProof if it appears
  blob/service.go
  blob/service_test.go
Labels: kind:fix, area:blob

#3746 fix(blob): fix blobsub subscription cancellation test
  blob/service_test.go
Labels: kind:fix, shwap

#3747 fix(store): use symlinks for empty blocks heighs
  store/store.go
Labels: kind:fix, shwap

#3723 chore: use sync/atomic types
  das/daser.go
  das/daser_test.go
  das/metrics.go
  share/eds/retriever.go
  share/ipld/get.go
Labels: kind:chore

#3754 chore(shwap/bitswap): prevent not found error logging
  share/shwap/p2p/bitswap/block_store.go
Labels: kind:break!, kind:chore, shwap

#3755 chore(shwap/bitswap): add getter tracing
  share/shwap/p2p/bitswap/getter.go
Labels: kind:chore, shwap

#3751 feat(share/availability): Dont store q4 on archival
  core/eds.go
  header/headertest/fraud/testing.go
  libs/edssser/edssser.go
  share/availability/full/availability.go
  share/availability/full/availability_test.go
  share/shwap/p2p/shrex/shrex_getter/shrex_test.go
  share/shwap/p2p/shrex/shrexeds/exchange_test.go
  share/shwap/p2p/shrex/shrexnd/exchange_test.go
  store/getter_test.go
  store/metrics.go
  store/store.go
  store/store_cache_test.go
  store/store_test.go
Labels: kind:feat, shwap

#3757 feat(store/cache): add Has methods
  store/cache/accessor_cache.go
  store/cache/accessor_cache_test.go
  store/cache/cache.go
  store/cache/doublecache.go
  store/cache/noop.go
  store/store_cache.go
  store/store_cache_test.go
Labels: kind:feat, shwap

#3760 Add bootsrapper for mainnet by Qubelabs
  nodebuilder/p2p/bootstrap.go
Labels: external

#3749 Add bootstrapper mainnet P-OPS
  nodebuilder/p2p/bootstrap.go
Labels: external, kind:chore

#3761 Chore(fix): set asynctimerchan=1 on build
  go.mod
Labels: kind:fix

#3752 fix(ci): Run pruning integration test separately in ci
  .github/workflows/integration-tests.yml
  nodebuilder/tests/prune_test.go
Labels: kind:fix, kind:ci

#3725 log(das): clarify that square width is for EDS
  das/worker.go
Labels: kind:misc

#3753 fix(nodebuilder/host): Ensure libp2p metrics are collected to prometheus
  cmd/flags_misc.go
  nodebuilder/p2p/host.go
  nodebuilder/p2p/metrics.go
Labels: kind:fix

#3763 fix(nodebuilder/p2p/metrics): enforce init order for bitswap metrics
  go.mod
  nodebuilder/p2p/bitswap.go
  nodebuilder/p2p/metrics.go
Labels: kind:fix

#3759 fix(node): fixup CELESTIA_HOME
  cmd/cel-key/node_types.go
  cmd/flags_node.go
  nodebuilder/store.go
  nodebuilder/store_test.go
Labels: kind:fix

#3765 feat: add network-specific tags to ci container workflow
  .github/workflows/docker-build-publish.yml
Labels: external, kind:ci

#3766 chore(ci): add workflow dispath to docker ci to manually trigger
  .github/workflows/docker-build-publish.yml
Labels: external

#3768 fix(nodebuidlder/p2p) Use semver for discovery prefix
  nodebuilder/share/p2p_constructors.go
Labels: kind:fix, shwap

#3767 chore(mocks): update generated mocks
  nodebuilder/blob/mocks/api.go
  nodebuilder/node/mocks/api.go
  nodebuilder/share/mocks/api.go
  nodebuilder/state/mocks/api.go
Labels: kind:chore, shwap

#3775 fix(core/listener): wait listener to shutdown before exit
  core/listener.go
Labels: kind:fix

#3776 chore(backport): backport changes from main to v0.16.1 release branch
  core/listener.go
  go.mod
  go.sum
  header/header.go
Labels: kind:chore

#3778 chore(shwap/discovery): prefix -> suffix
  nodebuilder/share/p2p_constructors.go
  share/shwap/p2p/discovery/discovery.go
Labels: kind:chore

#3781 fix(modshare): discovery leftover from #3777
  nodebuilder/share/p2p_constructors.go
Labels: kind:fix

#3786 chore(deps): upgrade to v2.2.0-mocha
  go.mod
  go.sum
Labels: kind:deps, external
