Repository celestiaorg/celestia-node, pull requests merged in 2024-12, with the labels that each got.

#3912 nodebuilder/pruner: Enforce light pruning
  nodebuilder/pruner/module.go
Labels: kind:feat

#3949 feat(availability): env var to disable pruning
  share/availability/window.go
Labels: kind:feat

#3821 feat!: unify the blob.Proof and the CommitmentProof
  blob/blob.go
  blob/blob_fuzz_test.go
  blob/commitment_proof.go
  blob/repro_test.go
  blob/service.go
  blob/service_test.go
  go.mod
  go.sum
  nodebuilder/blob/blob.go
  nodebuilder/blob/mocks/api.go
  nodebuilder/share/mocks/api.go
  nodebuilder/share/share.go
Labels: kind:feat, external

#3988 fix(share/availability): add missing protection for autobatch
  share/availability/light/availability.go
Labels: kind:fix

#3957 refactor(share/availability/light | share/availability/full): Availability implementations are aware of sampling window, removed from DASer
  core/eds.go
  core/exchange.go
  core/exchange_test.go
  core/listener.go
  core/option.go
  das/daser.go
  das/daser_test.go
  das/options.go
  das/worker.go
  nodebuilder/das/constructors.go
  nodebuilder/pruner/module.go
  share/availability/full/availability.go
  share/availability/full/availability_test.go
  share/availability/full/options.go
  share/availability/light/availability.go
  share/availability/light/availability_test.go
  share/availability/light/options.go
  share/availability/window.go
Labels: area:shares, kind:refactor

#3994 fix(api): add time.Duration and rsmt2d.Axis types
  api/docgen/examples.go
Labels: kind:fix, kind:docs

#3954 feat(core): added support of the TLS certificates along with x-token authorisation token for the gRPC connection
  nodebuilder/core/config.go
  nodebuilder/core/flags.go
  nodebuilder/core/tls.go
  nodebuilder/state/core.go
  state/core_access.go
Labels: area:config, area:core_and_app, kind:feat

#4003 fix(cmd/blob): fix namespace parsing in cli
  nodebuilder/blob/cmd/blob.go
Labels: kind:fix, area:cli

#3992 chore/make: add celestia-node make file for arabica testnet
  Makefile
  README.md
  celestia-node.mk
Labels: kind:misc, external

#3990 fix(sync/test): fix TestSyncStartStopLightWithBridge
  nodebuilder/tests/sync_test.go
Labels: kind:fix

#3999 refactor(core): unify grpc clients
  core/client.go
  core/exchange_test.go
  core/fetcher.go
  core/fetcher_no_race_test.go
  core/fetcher_test.go
  core/header_test.go
  core/testing.go
  nodebuilder/core/constructors.go
  nodebuilder/core/module.go
  nodebuilder/core/opts.go
  nodebuilder/core/tls.go
  nodebuilder/module.go
  nodebuilder/node_bridge_test.go
  nodebuilder/state/core.go
  nodebuilder/state/module.go
  nodebuilder/testing.go
  nodebuilder/tests/swamp/swamp.go
  state/core_access.go
  state/core_access_test.go
  state/integration_test.go
Labels: area:core_and_app, kind:misc

#4005 perf(shwap): cache Both Row sides
  share/eds/rsmt2d.go
  share/shwap/row.go
  share/shwap/row_test.go
Labels: kind:misc, shwap

#3997 refactor(docgen): simplify init
  api/docgen/examples.go
  api/docgen/openrpc.go
Labels: kind:refactor
