Repository celestiaorg/celestia-node, pull requests merged in 2024-01, with the labels that each got.

#2935 chore(share|das|libs/utils): DRY context resetting in the event of an error for metrics
  core/exchange_metrics.go
  core/listener_metrics.go
  das/metrics.go
  libs/utils/resetctx.go
  share/eds/metrics.go
  share/getters/shrex.go
  share/p2p/discovery/metrics.go
  share/p2p/metrics.go
  share/p2p/peers/metrics.go
Labels: kind:misc, external

#3052 chore(go.mod): bump go-header
  go.mod
  go.sum
  nodebuilder/header/constructors.go
  share/eds/byzantine/byzantine.go
Labels: kind:deps

#3004 chore(p2p/flags): Handle empty p2p.network flag.
  nodebuilder/p2p/flags.go
  nodebuilder/p2p/flags_test.go
Labels: kind:misc, external, area:cli

#3066 chore(nodebuilder/p2p)!: add arabica-11
  nodebuilder/p2p/bootstrap.go
  nodebuilder/p2p/genesis.go
  nodebuilder/p2p/network.go
Labels: kind:misc, external

#3067 chore(go.mod): Bump header to latest release
  go.mod
  go.sum
Labels: kind:deps, kind:chore

#2991 feat(nodebuilder/prune)!: Enable sampling window for light nodes
  das/daser.go
  das/daser_test.go
  nodebuilder/prune/module.go
  pruner/light/window.go
Labels: kind:feat, kind:break!, area:das

#3068 chore(deps): update otel group
  go.mod
  go.sum
Labels: kind:deps

#3051 test: cleanup of PR 2998 to simplify
  libs/utils/address.go
  libs/utils/address_test.go
Labels: kind:testing

#3077 fix(core): Use `Verify` from go-header pkg in `CoreExchange`
  core/exchange.go
Labels: area:core_and_app, kind:fix

#2912 chore(modstate): Remove IsStopped endpoint from StateModule
  api/gateway/middleware.go
  nodebuilder/state/mocks/api.go
  nodebuilder/state/state.go
  nodebuilder/state/stub.go
  state/core_access.go
Labels: area:state, kind:break!, kind:refactor

#3091 chore(deps): Bump deps
  go.mod
  go.sum
Labels: kind:deps, kind:chore

#3096 chore(deps): Bump go-header
  go.mod
  go.sum
Labels: kind:deps, libs:header

#3100 ci: add continue-on-error temporarily
  .github/workflows/go-ci.yml
Labels: kind:ci

#3090 fix: clarifying blob.GetAll godoc
  nodebuilder/blob/blob.go
Labels: docs:godocs, kind:fix, area:blob

#3103 chore: cleanup go.mod file require sections
  go.mod
Labels: kind:deps, external

#3089 feat(nodebuilder): log node version on start
  nodebuilder/node.go
Labels: kind:misc, external

#3086 fix(core): Do not propagate blocks if subscribed to blocks from incorrect chain
  core/exchange_test.go
  core/listener.go
  core/listener_test.go
  core/option.go
  libs/utils/resetctx.go
  nodebuilder/core/module.go
  nodebuilder/tests/swamp/swamp.go
Labels: area:core_and_app, kind:fix

#3110 chore: unfork badger and ds-badger4
  go.mod
  go.sum
  nodebuilder/store.go
  share/eds/inverted_index.go
  share/eds/store_test.go
  share/getters/getter_test.go
Labels: kind:chore

#3108 fix(tests/befp): fix panic in befp test
  share/eds/byzantine/bad_encoding_test.go
Labels: kind:testing, kind:fix, flakiness

#3072 chore(nodebuilder/state): SubmitTx endpoint takes read-level permissions
  api/rpc_test.go
  nodebuilder/state/state.go
Labels: external, kind:chore

#2939 test(gateway): slight refactor of some presentation and add some endpoint registration tests
  api/gateway/bindings.go
  api/gateway/bindings_test.go
  api/gateway/endpoints.go
  api/gateway/health.go
  api/gateway/server.go
  api/gateway/util.go
  api/gateway/util_test.go
  cmd/celestia/cmd_test.go
Labels: kind:testing

#3116 feat(blob/service): cover getByCommitment with benchmark
  blob/service_test.go
  header/headertest/testing.go
Labels: kind:testing, kind:feat

#3114 chore: make CI green
  .github/workflows/go-ci.yml
  .github/workflows/integration-tests.yml
  Makefile
  core/fetcher_no_race_test.go
  core/fetcher_test.go
  core/listener_no_race_test.go
  core/listener_test.go
  nodebuilder/node_test.go
  nodebuilder/store_test.go
  nodebuilder/tests/api_test.go
  nodebuilder/tests/blob_test.go
  nodebuilder/tests/fraud_test.go
  nodebuilder/tests/helpers_test.go
  nodebuilder/tests/nd_test.go
  nodebuilder/tests/p2p_test.go
  nodebuilder/tests/reconstruct_test.go
  nodebuilder/tests/sync_test.go
  share/eds/retriever_no_race_test.go
  share/eds/retriever_test.go
  share/p2p/discovery/discovery_test.go
  state/core_access_test.go
Labels: kind:testing, kind:ci

#3132 fix(libs/pidstore): Detect corruption on startup and reset pidstore
  libs/pidstore/pidstore.go
  libs/pidstore/pidstore_test.go
Labels: area:p2p, kind:fix

#3094 refactor(blob)!: replace SubmitOptions with a GasPrice parameter
  blob/service.go
  nodebuilder/blob/blob.go
  nodebuilder/blob/cmd/blob.go
  nodebuilder/blob/mocks/api.go
  nodebuilder/das/mocks/api.go
  nodebuilder/fraud/mocks/api.go
  nodebuilder/header/mocks/api.go
  nodebuilder/node/mocks/api.go
  nodebuilder/share/mocks/api.go
  nodebuilder/state/mocks/api.go
  nodebuilder/tests/api_test.go
  nodebuilder/tests/blob_test.go
  share/availability/mocks/availability.go
  share/mocks/getter.go
Labels: kind:break!, area:blob

#3118 feat(rpc/node): readiness check
  nodebuilder/module.go
  nodebuilder/node/admin.go
  nodebuilder/node/node.go
  nodebuilder/tests/api_test.go
Labels: area:rpc, kind:feat

#3142 chore(spelling): fix all stray typos across comments and tests
  libs/pidstore/pidstore_test.go
  nodebuilder/p2p/cmd/p2p.go
  nodebuilder/tests/api_test.go
  nodebuilder/tests/swamp/swamp.go
  share/getters/shrex_test.go
  share/ipld/corrupted_data_test.go
  share/p2p/peers/manager.go
  state/core_access.go
Labels: kind:misc

#3113 feat(blob/trace): cover blob service with traces
  blob/service.go
Labels: kind:feat, area:blob
