Repository celestiaorg/celestia-node, pull requests merged in 2024-06, with the labels that each got.

#3454 fix(share/getters)!: return nil shares from all getters in non-inclusion case
  share/getter.go
  share/getters/getter_test.go
  share/getters/shrex_test.go
  share/ipld/get_shares.go
Labels: area:shares, kind:break!, kind:fix

#3455 fix(share/pruner) enable Light node pruner service
  cmd/util.go
  nodebuilder/pruner/module.go
Labels: kind:fix

#3452 refactor(shwap): Extract eds interface
  share/new_eds/accessor.go
  share/new_eds/axis_half.go
  share/new_eds/nd.go
  share/new_eds/nd_test.go
  share/new_eds/rsmt2d.go
  share/new_eds/rsmt2d_test.go
  share/shwap/namespace_data.go
  share/shwap/row.go
  share/shwap/row_namespace_data.go
  share/shwap/row_namespace_data_test.go
  share/shwap/row_test.go
  share/shwap/sample.go
  share/shwap/sample_test.go
  share/store/file/eds_file.go
  share/store/file/mem_file.go
  share/store/file/mem_file_test.go
Labels: kind:refactor, shwap

#3467 feat(share/pruner): disallow converting pruned node to archival
  blob/parser.go
  blob/service_test.go
  nodebuilder/pruner/module.go
  nodebuilder/tests/fraud_test.go
  nodebuilder/tests/prune_test.go
  nodebuilder/tests/swamp/swamp.go
  pruner/checkpoint.go
  pruner/checkpoint_test.go
  share/eds/byzantine/share_proof.go
Labels: kind:feat, v0.14.0

#3463 chore(swamp): remove always failing assert
  nodebuilder/tests/swamp/swamp.go
Labels: kind:chore

#3466 fix(nodebuilder/share): Pass `light.Window` to shrex getter construction regardless of node type / pruning mode
  nodebuilder/share/module.go
  nodebuilder/tests/prune_test.go
  share/getters/shrex_test.go
Labels: area:p2p, kind:fix, shrex

#3478 refactor(share): use atomic.Int64 and fix 'racy' bugs
  share/ipld/namespace_data.go
Labels: kind:refactor

#3483 chore(deps): upgrade golangci-lint in ci to 1.59
  .github/workflows/go-ci.yml
  nodebuilder/fraud/lifecycle.go
  share/eds/cache/noop.go
Labels: kind:chore

#3477 chore(das): move jobType declaration closer to consts
  das/worker.go
Labels: kind:chore

#3425 feat(share/eds) Add Accessor test infra
  share/new_eds/accessor.go
  share/new_eds/rsmt2d.go
  share/new_eds/rsmt2d_test.go
  share/new_eds/testing.go
  share/shwap/row_namespace_data.go
Labels: kind:feat, shwap

#3492 chore(share/p2p/discovery): Change success case logging for advertisement to INFO level
  nodebuilder/p2p/misc.go
  share/eds/cache/noop.go
  share/p2p/discovery/discovery.go
Labels: kind:chore

#3497 refactor(testing): replace require.TestingT with testing.TB
  nodebuilder/store_test.go
  share/eds/edstest/testing.go
  share/sharetest/testing.go
Labels: kind:testing

#3484 feat(shwap): Add close once file
  share/new_eds/close_once.go
  share/new_eds/close_once_test.go
Labels: kind:feat, shwap

#3500 ci: remove golangci-lint action warning
  .github/workflows/ci_release.yml
Labels: kind:ci

#3482 feat(shwap): Add ODS file
  go.mod
  share/new_eds/axis_half.go
  share/new_eds/axis_half_test.go
  share/new_eds/rsmt2d_test.go
  share/new_eds/testing.go
  share/shwap/row_namespace_data.go
  share/shwap/sample.go
  store/file/codec.go
  store/file/codec_test.go
  store/file/header.go
  store/file/ods.go
  store/file/ods_test.go
  store/file/square.go
Labels: kind:feat, shwap

#3507 ci: update celestia shared dep to remove node 16 warning
  .github/workflows/ci_release.yml
  .github/workflows/create_release_tracking_epic.yml
  .github/workflows/docker-build-publish.yml
Labels: kind:ci

#3514 test(store): add header de/serialization fuzzing
  store/file/header_test.go
Labels: kind:testing, swamp

#3479 feat(docgen): improve examples
  api/docgen/exampledata/blob.json
  api/docgen/exampledata/blobProof.json
  api/docgen/examples.go
Labels: area:rpc, kind:feat

#3519 refactor: use libhead alias consistently
  nodebuilder/pruner/constructors.go
  pruner/service.go
Labels: kind:refactor

#3525 feat: arabica bootstrappers now dnsaddr multiaddr
  nodebuilder/p2p/bootstrap.go
Labels: kind:misc, external

#3527 chore(deps): upgrade to celestia-app v1.12.0
  .github/workflows/ci_release.yml
  Dockerfile
  README.md
  go.mod
  go.sum
Labels: kind:deps, external

#3421 feat(share): Shwap Bitwap composition
  share/shwap/p2p/bitswap/block.go
  share/shwap/p2p/bitswap/block_fetch.go
  share/shwap/p2p/bitswap/block_fetch_test.go
  share/shwap/p2p/bitswap/block_proto.go
  share/shwap/p2p/bitswap/block_registry.go
  share/shwap/p2p/bitswap/block_store.go
  share/shwap/p2p/bitswap/block_test.go
  share/shwap/p2p/bitswap/cid.go
  share/shwap/p2p/bitswap/pb/bitswap.pb.go
  share/shwap/p2p/bitswap/pb/bitswap.proto
  share/shwap/p2p/bitswap/row_block.go
  share/shwap/p2p/bitswap/row_block_test.go
  share/shwap/p2p/bitswap/row_namespace_data_block.go
  share/shwap/p2p/bitswap/row_namespace_data_block_test.go
  share/shwap/p2p/bitswap/sample_block.go
  share/shwap/p2p/bitswap/sample_block_test.go
  share/shwap/row.go
  share/shwap/row_namespace_data.go
  share/shwap/sample.go
Labels: kind:feat, shwap

#3498 feat(shwap): Add cache file
  core/exchange.go
  core/listener.go
  header/headertest/fraud/testing.go
  nodebuilder/store_test.go
  share/availability/full/availability.go
  share/eds/byzantine/share_proof.go
  share/eds/eds.go
  share/ipld/get.go
  share/ipld/namespace_data.go
  share/ipld/nmt_adder.go
  share/ipld/proofs.go
  share/ipld/proofs_test.go
  share/new_eds/axis_half.go
  share/new_eds/proofs_cache.go
  share/new_eds/proofs_cache_test.go
Labels: kind:feat, shwap

#3522 feat(shwap): add Q1Q4 file
  share/new_eds/testing.go
  store/file/ods.go
  store/file/ods_test.go
  store/file/q1q4_file.go
  store/file/q1q4_file_test.go
Labels: kind:feat, shwap

#3526 fix(nodebuilder/core): non default values from config.toml are written over by flag defaults in specific circumstances
  nodebuilder/core/config.go
  nodebuilder/core/config_test.go
  nodebuilder/core/flags.go
  nodebuilder/core/flags_test.go
Labels: kind:fix
