Repository celestiaorg/celestia-node, pull requests merged in 2024-03, with the labels that each got.

#3165 feat(blob): extend blob struct with index field
  blob/blob.go
  blob/blob_test.go
  blob/helper.go
  blob/parser.go
  blob/service.go
  blob/service_test.go
  nodebuilder/blob/cmd/blob.go
  nodebuilder/tests/blob_test.go
Labels: kind:feat, area:blob

#3228 chore(deps): upgrade to Go 1.22
  .github/workflows/ci_release.yml
  Dockerfile
  README.md
  cmd/cel-shed/eds_store_stress.go
  cmd/flags_misc.go
  go.mod
  go.sum
  nodebuilder/settings.go
Labels: kind:deps, external

#3218 deps: bump go-header
  go.mod
  go.sum
Labels: kind:deps

#3204 fix(blob | nodebuilder/da): Revert custom marshaling for `blob.Proof`
  blob/blob.go
  nodebuilder/da/service.go
Labels: kind:fix, area:api, area:blob

#3012 feat(share/store): Allow Store implementation to choose proof axis for Share
  share/share.go
  share/store/eds_file.go
  share/store/mem_file.go
  share/store/mem_file_test.go
Labels: area:shares, kind:feat

#3013 refactor(share): Move shareWithProof to share pkg
  api/docgen/examples.go
  share/eds/byzantine/bad_encoding.go
  share/eds/byzantine/bad_encoding_test.go
  share/eds/byzantine/byzantine.go
  share/eds/byzantine/share_proof.go
  share/eds/byzantine/share_proof_test.go
  share/ipld/get.go
  share/ipld/get_test.go
  share/share.go
Labels: area:shares, kind:refactor

#3240 refactor: chunk -> share
  das/doc.go
  docs/adr/adr-011-blocksync-overhaul-part-1.md
  docs/adr/adr-012-daser-parallelization.md
  share/ipld/add.go
Labels: kind:refactor, external

#3227 ci(triggers): change release process from tag push to release publish
  .github/workflows/ci_release.yml
Labels: kind:ci

#3197 chore(Makefile): detect and default to make go-install on darwin vs install everywhere else
  Makefile
Labels: kind:misc

#3247 ci(lint): upgrade golangci-lint to 1.56 and fix revive errors that emerged
  .github/workflows/go-ci.yml
  .golangci.yml
  api/docgen/openrpc.go
  cmd/cel-shed/eds_store_stress.go
  cmd/cel-shed/p2p.go
  cmd/config.go
  cmd/docgen/openrpc.go
  cmd/init.go
  cmd/reset_store.go
  cmd/start.go
  nodebuilder/core/module.go
  nodebuilder/das/cmd/das.go
  nodebuilder/header/cmd/header.go
  nodebuilder/node/cmd/node.go
  nodebuilder/node/metrics.go
  nodebuilder/p2p/bitswap.go
  nodebuilder/p2p/cmd/p2p.go
  nodebuilder/p2p/metrics.go
  nodebuilder/share/module.go
  nodebuilder/state/cmd/state.go
  share/eds/cache/metrics.go
  share/eds/metrics.go
  share/p2p/discovery/metrics.go
  share/p2p/peers/metrics.go
  state/metrics.go
Labels: kind:ci

#3254 fix(nodebuilder/blob): use state module instead of the state accessor in the module construction
  nodebuilder/blob/module.go
Labels: kind:fix, area:blob

#3253 refactor(nodebuilder): use external flock library
  go.mod
  libs/fslock/lock_unix.go
  libs/fslock/locker.go
  libs/fslock/locker_test.go
  nodebuilder/config.go
  nodebuilder/init.go
  nodebuilder/init_test.go
  nodebuilder/store.go
Labels: kind:refactor

#3255 refactor(nodebuilder): stick to lock semantics, not file
  nodebuilder/config.go
  nodebuilder/init.go
  nodebuilder/init_test.go
  nodebuilder/store.go
Labels: kind:refactor

#3239 feat(share/availability): persist random samples selection in availability call
  share/availability/light/availability.go
  share/availability/light/availability_test.go
  share/availability/light/sample.go
  share/availability/light/sample_test.go
  share/availability/light/testing.go
Labels: area:shares, kind:feat

#3259 feat: add workdir to dockerfile
  Dockerfile
Labels: external, kind:ci

#3271 deps: bump go-header
  go.mod
  go.sum
Labels: kind:deps

#3222 ci(deps): Bump common ci
  .github/workflows/ci_release.yml
  .github/workflows/docker-build-publish.yml
Labels: external, kind:ci

#3279 fix(ci): specify secrets
  .github/workflows/docker-build-publish.yml
Labels: external, kind:ci

#3150 feat(pruner): Implement `full` and `bridge` node pruning
  cmd/node.go
  cmd/util.go
  header/headertest/testing.go
  nodebuilder/config.go
  nodebuilder/module.go
  nodebuilder/prune/module.go
  nodebuilder/pruner/config.go
  nodebuilder/pruner/constructors.go
  nodebuilder/pruner/flags.go
  nodebuilder/pruner/module.go
  nodebuilder/settings.go
  pruner/archival/pruner.go
  pruner/checkpoint.go
  pruner/find.go
  pruner/full/pruner.go
  pruner/full/window.go
  pruner/light/pruner.go
  pruner/light/window.go
  pruner/metrics.go
  pruner/params.go
  pruner/pruner.go
  pruner/service.go
  pruner/service_test.go
Labels: area:storage, kind:feat
