Repository celestiaorg/celestia-node, pull requests merged in 2024-05, with the labels that each got.

#3351 fix(ci): update from published to released trigger for deployment epic
  .github/workflows/create_release_tracking_epic.yml
Labels: external, kind:ci

#3319 chore(deps): chore: bump to rsmt2d to v0.13.1
  go.mod
  go.sum
Labels: kind:chore

#3372 chore: bump go-libp2p-pubsub
  go.mod
  go.sum
Labels: kind:deps

#3370 fix(pruner/light): Fix light availability window provided
  pruner/full/window_test.go
  pruner/light/window.go
  pruner/light/window_test.go
Labels: area:storage, kind:fix, v0.14.0

#3340 chore(makefile): comment for install-global to clarify linux support only
  Makefile
Labels: kind:misc, external

#3366 chore: bump to app v1.9.0
  go.mod
  go.sum
Labels: kind:deps, external, v0.14.0

#3359 refactor(state): Remove need for core RPC conn and rely only on gRPC for state reads
  go.mod
  go.sum
  nodebuilder/state/core.go
  state/core_access.go
  state/core_access_test.go
  state/helpers.go
  state/integration_test.go
Labels: area:state, kind:refactor, v0.14.0

#3360 chore: add dupword CI && remove repetitive words globally
  .golangci.yml
  share/availability/full/reconstruction_test.go
  share/eds/retriever_quadrant.go
  share/getters/getter_test.go
  share/p2p/peers/manager_test.go
Labels: external, kind:ci

#3348 refactoring(cmd/state): remove submit-tx from cli
  nodebuilder/state/cmd/state.go
Labels: area:state, kind:break!, kind:refactor, area:cli

#3337 chore: fix function names in comment
  core/eds_test.go
  nodebuilder/p2p/network.go
Labels: kind:docs, external

#3389 refactor: add missing stop ticker
  share/eds/store.go
Labels: kind:fix, external

#1524 feat(tracer): Add shutdown hook for tracer
  nodebuilder/settings.go
Labels: area:metrics, kind:chore

#3380 fix(das): Clarify logs for historic headers that are skipped
  das/daser.go
  das/worker.go
Labels: kind:fix, area:das

#3378 chore(nodebuilder/das | pruner): Privatise `samplingWindow` in DAS params, add Duration method to `AvailabilityWindow`
  das/daser.go
  das/daser_test.go
  das/options.go
  nodebuilder/das/constructors.go
  pruner/find.go
  pruner/full/window_test.go
  pruner/light/window_test.go
  pruner/service_test.go
  pruner/window.go
Labels: kind:chore

#3350 ci: generate and store openrpc.json with the tagged release artifacts
  .github/workflows/ci_release.yml
  Makefile
Labels: kind:ci, v0.14.0

#3418 add @cristaloleg to .github/CODEOWNERS
  .github/CODEOWNERS
Labels: kind:chore, kind:ci

#3383 feat(shwap): add shwap types
  Makefile
  share/share.go
  share/shwap/data_id.go
  share/shwap/data_id_test.go
  share/shwap/eds_id.go
  share/shwap/eds_id_test.go
  share/shwap/namespaced_data.go
  share/shwap/pb/shwap.pb.go
  share/shwap/pb/shwap.proto
  share/shwap/row.go
  share/shwap/row_id.go
  share/shwap/row_id_test.go
  share/shwap/sample.go
  share/shwap/sample_id.go
  share/shwap/sample_id_test.go
  share/shwap/share.go
Labels: kind:feat, shwap

#3422 doc: improve godoc for the blob service
  blob/blob.go
  blob/parser.go
  blob/service.go
  blob/service_test.go
Labels: kind:docs, area:blob

#3434 chore(logs): lower bitswap-server verbosity
  logs/logs.go
Labels: kind:chore

#3443 chore(deps): Bump github.com/celestiaorg/nmt from v0.20.0 to v0.21.0
  go.mod
  go.sum
Labels: kind:deps

#3188 feat(p2p/discovery)!: Implement `archival` discovery + syncing of historic blocks and blobs
  das/daser.go
  das/daser_test.go
  nodebuilder/node.go
  nodebuilder/pruner/module.go
  nodebuilder/share/constructors.go
  nodebuilder/share/module.go
  nodebuilder/share/opts.go
  nodebuilder/share/p2p_constructors.go
  nodebuilder/tests/prune_test.go
  share/availability/full/availability.go
  share/availability/full/testing.go
  share/getters/shrex.go
  share/getters/shrex_test.go
  share/p2p/discovery/discovery.go
  share/p2p/discovery/metrics.go
  share/p2p/discovery/options.go
  share/p2p/peers/manager.go
  share/p2p/peers/manager_test.go
  share/p2p/peers/metrics.go
Labels: area:p2p, area:storage, kind:feat, kind:break!, v0.14.0

#3445 refactor(core): remove unused test grpc server
  core/testing_grpc.go
Labels: kind:refactor

#3449 fix(cmd): Add pruner flags to LN as well
  cmd/node.go
Labels: kind:fix, area:cli
