Repository celestiaorg/celestia-node, pull requests merged in 2024-11, with the labels that each got.

#3887 feat(share/availability): Store success results for light availability
  share/availability/light/availability.go
  share/availability/light/availability_test.go
  share/availability/light/sample.go
Labels: kind:feat

#3908 test(swamp): cover v1 blobs in swamp tests
  nodebuilder/tests/blob_test.go
Labels: swamp, kind:misc

#3896 feat(pruner/light): add light pruning for shwap
  nodebuilder/pruner/module.go
  nodebuilder/share/module.go
  pruner/light/pruner.go
  share/availability/light/availability.go
  share/availability/light/availability_test.go
  share/ipld/delete.go
  share/ipld/delete_test.go
Labels: kind:feat

#3902 !refactor: rename GetSharesByNamespace to GetNamespaceData
  api/gateway/share.go
  blob/service.go
  blob/service_test.go
  nodebuilder/da/mocks/api.go
  nodebuilder/share/cmd/share.go
  nodebuilder/share/share.go
  nodebuilder/tests/nd_test.go
  share/availability/light/availability_test.go
  share/shwap/getter.go
  share/shwap/getters/cascade.go
  share/shwap/getters/mock/getter.go
  share/shwap/getters/testing.go
  share/shwap/p2p/bitswap/getter.go
  share/shwap/p2p/shrex/shrex_getter/shrex.go
  share/shwap/p2p/shrex/shrex_getter/shrex_test.go
  store/getter.go
  store/getter_test.go
Labels: kind:break!, kind:refactor, kind:chore

#3914 ci(docker): bump version
  .github/workflows/docker-build-publish.yml
Labels: kind:deps, T:dependencies, external, kind:ci

#3910 deps(go.mod): bump app to arabica tag
  go.mod
  go.sum
Labels: kind:deps

#3920 chore: bump to celestia-app v3.0.0-mocha
  go.mod
  go.sum
Labels: kind:deps, external

#3928 fix(header)!: tendermint compatible json marshall
  api/docgen/exampledata/extendedHeader.json
  header/header.go
Labels: kind:break!, kind:fix, external

#3934 refactor: remove blob size check
  blob/blob.go
Labels: kind:fix, area:blob, external

#3936 fix(core): change fill block mode
  core/exchange_test.go
Labels: kind:fix

#3926 hotfix(core): don't hold on Data
  core/exchange.go
Labels: kind:fix

#3937 fix(p2p): disable quic
  nodebuilder/p2p/addrs.go
  nodebuilder/p2p/host.go
Labels: kind:fix

#3939 chore(deps): temporary fork boxo
  go.mod
  go.sum
  share/shwap/p2p/bitswap/bitswap.go
Labels: kind:chore

#3940 fix(shwap/bitswap): tune bitswap params
  share/shwap/p2p/bitswap/bitswap.go
Labels: kind:fix

#3894 fix(shwap/bitswap): Blockstore.GetSize: getting size with no compute
  share/shwap/p2p/bitswap/block_registry.go
  share/shwap/p2p/bitswap/block_store.go
  share/shwap/p2p/bitswap/block_test.go
  share/shwap/p2p/bitswap/cid.go
  share/shwap/p2p/bitswap/row_block.go
  share/shwap/p2p/bitswap/row_namespace_data_block.go
  share/shwap/p2p/bitswap/sample_block.go
Labels: kind:fix

#3946 fix(shwap/bitswap): update boxo and config
  go.mod
  go.sum
  share/shwap/p2p/bitswap/bitswap.go
Labels: kind:fix

#3948 chore(go.mod): bump boxo fork
  go.mod
  go.sum
Labels: kind:chore

#3944 fix(share/availability/light): Allow retries on ODS size 1
  share/availability/light/availability.go
  share/availability/light/availability_test.go
Labels: area:shares, kind:fix

#3947 perf(shwap/bitswap): add session pools inside Getter
  share/shwap/p2p/bitswap/getter.go
  share/shwap/p2p/bitswap/getter_test.go
Labels: kind:misc

#3962 fix(openrpc-gen): add go-square blob to examples
  api/docgen/examples.go
Labels: documentation, kind:fix, area:api

#3963 fix(.github/workflows): no automatic tagging of releases for CI
  .github/workflows/ci_release.yml
Labels: ci:actions, kind:ci

#3891 refactor(share): GetShare -> GetSamples
  blob/service_test.go
  nodebuilder/share/mocks/api.go
  nodebuilder/share/share.go
  share/availability/light/availability.go
  share/availability/light/availability_test.go
  share/availability/light/sample.go
  share/eds/accessor.go
  share/eds/close_once.go
  share/eds/close_once_test.go
  share/eds/proofs_cache.go
  share/eds/rsmt2d.go
  share/eds/rsmt2d_test.go
  share/eds/testing.go
  share/eds/validation.go
  share/eds/validation_test.go
  share/shwap/getter.go
  share/shwap/getters/cascade.go
  share/shwap/getters/cascade_test.go
  share/shwap/getters/mock/getter.go
  share/shwap/getters/testing.go
  share/shwap/p2p/bitswap/getter.go
  share/shwap/p2p/bitswap/sample_block.go
  share/shwap/p2p/bitswap/sample_block_test.go
  share/shwap/p2p/shrex/shrex_getter/shrex.go
  share/shwap/sample.go
  share/shwap/sample_id.go
  share/shwap/sample_id_test.go
  share/shwap/sample_test.go
  store/cache/accessor_cache_test.go
  store/cache/noop.go
  store/file/codec.go
  store/file/ods.go
  store/file/ods_q4.go
  store/getter.go
  store/getter_test.go
Labels: area:shares, kind:refactor, shwap

#3968 deps(go.mod): bump app
  go.mod
  go.sum
Labels: kind:deps

#3967 fix: jwt token nonce and expiration time
  api/rpc/perms/permissions.go
  api/rpc_test.go
  cmd/auth.go
  cmd/rpc.go
  libs/authtoken/authtoken.go
  nodebuilder/node/admin.go
  nodebuilder/node/cmd/node.go
  nodebuilder/node/node.go
  nodebuilder/tests/helpers_test.go
Labels: kind:fix

#3969 chore(deps): upgrade to celestia-app v3.0.2
  core/eds.go
  go.mod
  go.sum
Labels: kind:deps, external

#3972 fix(goreleaser): tag_sort
  .goreleaser.yaml
Labels: kind:ci

#3915 feat!: adds support for gRPC streaming and removes dependency on RPC
  core/client.go
  core/eds.go
  core/eds_test.go
  core/exchange.go
  core/exchange_test.go
  core/fetcher.go
  core/fetcher_no_race_test.go
  core/fetcher_test.go
  core/header_test.go
  core/listener.go
  core/testing.go
  go.mod
  go.sum
  nodebuilder/config_test.go
  nodebuilder/core/config.go
  nodebuilder/core/config_test.go
  nodebuilder/core/constructors.go
  nodebuilder/core/flags.go
  nodebuilder/core/flags_test.go
  nodebuilder/core/module.go
  nodebuilder/core/opts.go
  nodebuilder/node_bridge_test.go
  nodebuilder/node_test.go
  nodebuilder/state/core.go
  nodebuilder/testing.go
  nodebuilder/tests/fraud_test.go
  nodebuilder/tests/p2p_test.go
  nodebuilder/tests/prune_test.go
  nodebuilder/tests/swamp/swamp.go
  state/core_access.go
Labels: kind:feat, kind:break!, external
