Repository celestiaorg/celestia-node, pull requests merged in 2024-08, with the labels that each got.

#3609 chore(shwap): various improvements
  share/new_eds/validation_test.go
  share/shwap/eds.go
  share/shwap/eds_id.go
  share/shwap/getter.go
  share/shwap/namespace_data.go
  share/shwap/namespace_data_id.go
  share/shwap/p2p/shrex/shrexeds/exchange_test.go
  share/shwap/row_id.go
  share/shwap/row_namespace_data.go
  share/shwap/row_namespace_data_id.go
  share/shwap/sample_id.go
Labels: kind:chore, shwap

#3600 feat(shwap): Update availability to work with shwap
  share/availability/full/availability.go
  share/availability/full/availability_test.go
  share/availability/full/reconstruction_test.go
  share/availability/full/testing.go
  share/availability/light/availability.go
  share/availability/light/availability_test.go
  share/availability/light/testing.go
  share/availability/test/corrupt_data.go
  share/ipld/corrupted_data_test.go
  share/shwap/getters/cascade.go
  share/shwap/p2p/bitswap/getter.go
Labels: kind:feat, shwap

#3613 feat(shwap): add shwap to blob module
  blob/service.go
  blob/service_test.go
Labels: kind:feat, shwap

#3614 feat(shwap): update daser for shwap
  das/coordinator.go
  das/coordinator_test.go
  das/daser.go
  das/daser_test.go
  das/worker.go
  header/headertest/fraud/testing.go
Labels: kind:feat, shwap

#3604 testing(header): extend `ExtendedHeader.Verify` test with older headers
  header/headertest/verify_test.go
Labels: kind:testing

#3560 feat(modp2p): websocket transport with TLS
  nodebuilder/p2p/addrs.go
  nodebuilder/p2p/config.go
  nodebuilder/p2p/host.go
  nodebuilder/p2p/misc.go
  nodebuilder/p2p/module.go
  nodebuilder/p2p/pubsub.go
  nodebuilder/p2p/resources.go
  nodebuilder/p2p/routing.go
  nodebuilder/p2p/tls.go
Labels: kind:feat, v0.15.0

#3591 fix(share/getters): set minTimeout
  share/getters/cascade.go
  share/getters/cascade_test.go
Labels: area:shares, kind:fix

#3624 fix(libs/utils): rely on DNS for rpc/grpc requests to core
  libs/utils/address.go
  libs/utils/address_test.go
  nodebuilder/core/config.go
  nodebuilder/core/config_test.go
Labels: kind:fix, v0.15.0

#3627 deps: bump libp2p and enable WebRTC
  go.mod
  go.sum
  nodebuilder/p2p/config.go
  nodebuilder/p2p/host.go
Labels: kind:deps, v0.15.0

#3610 fix(blob)!: update the blob.Proof to return a proof to the data root
  api/docgen/exampledata/blobProof.json
  blob/blob.go
  blob/helper.go
  blob/parser.go
  blob/service.go
  blob/service_test.go
  go.mod
  go.sum
  share/eds/edstest/testing.go
Labels: kind:break!, kind:fix, external

#3631 deps: bump libp2p(again)
  go.mod
  go.sum
Labels: kind:deps

#3615 feat(shwap): Add caching to blockstore
  store/cache/accessor_cache.go
  store/cache/doublecache.go
  store/metrics.go
  store/store.go
  store/store_cache.go
  store/store_cache_test.go
  store/store_options.go
  store/store_test.go
Labels: kind:feat, shwap

#3536 feat(shwap/bitswap): Shwap optimized Bitswap constructors
  go.mod
  share/shwap/p2p/bitswap/bitswap.go
  share/shwap/p2p/bitswap/block_fetch.go
  share/shwap/p2p/bitswap/block_fetch_test.go
Labels: shwap

#3638 feat(shwap): Improve eds store cache refcounter forgot Close() protection
  store/cache/accessor_cache.go
  store/store.go
  store/store_cache_test.go
Labels: kind:feat, shwap

#3640 chore: improve Make help command
  Makefile
Labels: external, kind:chore

#3589 refactor(header): `Validate` should check that the raw header's app version is not greater than latest app version
  blob/commitment_proof.go
  blob/helper_test.go
  blob/service.go
  core/header_test.go
  go.mod
  go.sum
  header/header.go
  header/headertest/validate_test.go
  nodebuilder/blobstream/module.go
Labels: area:header, area:core_and_app, kind:chore, v0.16.0

#3568 misc(ci): detect breaking change to any .proto files or config fields in nodebuilder/**/config.go and add kind:break!
  .github/workflows/labels.yml
  Makefile
Labels: kind:ci

#3564 config(issues): extend bug report template to request DASer state for stuck nodes
  .github/ISSUE_TEMPLATE/bug-report.yml
Labels: kind:misc

#3657 fix(shwap/cahce): use local copy of axis in proofs cache
  share/new_eds/proofs_cache.go
Labels: kind:fix, shwap

#3641 fix(p2p): couple bitswap client and server
  nodebuilder/p2p/bitswap.go
Labels: kind:fix

#3659 feat: mocha update DNS of BN bootstrapper
  nodebuilder/p2p/bootstrap.go
Labels: kind:misc, external

#3660 ci(CODEOWNERS): remove @ramin
  .github/CODEOWNERS
Labels: kind:ci

#3663 fix(nodebuilder/state): overwrite state flags only if they were passed explicitly
  nodebuilder/state/flags.go
Labels: kind:fix

#3667 ci: fix goreleaser check deprecation warning
  .goreleaser.yaml
Labels: external, kind:ci

#3642 fix(store/cache): force close Accessor if not closed within timeout
  share/eds/cache/accessor_cache.go
Labels: kind:fix

#3671 deps(go.mod): bump boxo + libp2p
  go.mod
  go.sum
Labels: kind:deps

#3634 fix(share): return fixed data size in blockstore
  share/eds/blockstore.go
  share/ipld/nmt.go
Labels: kind:fix

#3677 chore(ci): add lint imports ci action
  .github/workflows/go-ci.yml
  share/eds/blockstore.go
Labels: kind:chore

#3678 chore(lint): bump golang-ci lint to 1.60
  .github/workflows/go-ci.yml
  .golangci.yml
  core/exchange.go
  nodebuilder/rpc/flags_test.go
  share/eds/retriever_test.go
  share/eds/utils.go
  share/getters/getter_test.go
  share/ipld/get_shares_test.go
Labels: kind:chore

#3676 chore: bump bump go to 1.23
  .github/workflows/ci_release.yml
  Dockerfile
  README.md
  go.mod
  go.sum
Labels: kind:chore

#3691 fix(store/files): ODSQ4 Closing audit
  store/file/ods_q4.go
Labels: kind:fix, shwap

#3693 perf(store/sync): avoid syncing files
  store/file/ods.go
  store/file/q4.go
Labels: kind:fix, shwap, performance

#3697 fix(shwap): io.ReadFull for NamespaceDataID
  share/shwap/namespace_data_id.go
Labels: kind:fix, shwap

#3699 fix(share/discovery): fix TestDiscovery test
  share/p2p/discovery/discovery_test.go
Labels: kind:testing, kind:fix

#3698 chore(deps): bump go-libp2p-kad-dht to v0.26.1
  go.mod
  go.sum
Labels: kind:deps

#3674 chore!: bump celestia-app to v2.1.2
  go.mod
  go.sum
  state/core_access.go
Labels: kind:deps, kind:break!, external

#3703 refactor(share/bitswap): remove feature flag for bitswap fix
  share/eds/blockstore.go
Labels: kind:refactor
