Repository celestiaorg/celestia-node, pull requests merged in 2025-06, with the labels that each got.

#4293 deps(go.mod): bump app arabica
  go.mod
  go.sum
Labels: kind:deps

#4302 chore: removing the bootstrapper 3 and 4 from lunar
  nodebuilder/p2p/bootstrap.go
Labels: kind:misc, for next release

#4312 bump go version
  go.mod
Labels: kind:fix

#4156 feat!(share/shwap): implement get range request over shwap
  nodebuilder/share/mocks/api.go
  nodebuilder/share/share.go
  nodebuilder/tests/share_test.go
  share/availability/light/availability_test.go
  share/eds/accessor.go
  share/eds/axis_half.go
  share/eds/close_once.go
  share/eds/close_once_test.go
  share/eds/proofs_cache.go
  share/eds/proofs_cache_test.go
  share/eds/rsmt2d.go
  share/eds/testing.go
  share/eds/validation.go
  share/extend.go
  share/shwap/getter.go
  share/shwap/getters/cascade.go
  share/shwap/getters/mock/getter.go
  share/shwap/getters/testing.go
  share/shwap/p2p/bitswap/getter.go
  share/shwap/p2p/bitswap/range_namespace_data_block.go
  share/shwap/p2p/bitswap/range_namespace_data_block_test.go
  share/shwap/p2p/shrex/shrex_getter/shrex.go
  share/shwap/p2p/shrex/shrexsub/pb/notification.pb.go
  share/shwap/pb/shwap.pb.go
  share/shwap/pb/shwap.proto
  share/shwap/proof.go
  share/shwap/range_namespace_data.go
  share/shwap/range_namespace_data_id.go
  share/shwap/range_namespace_data_id_test.go
  share/shwap/range_namespace_data_test.go
  store/cache/accessor_cache_test.go
  store/cache/noop.go
  store/file/ods.go
  store/file/ods_q4.go
  store/getter.go
Labels: area:shares, kind:feat, kind:break!

#4265 feat(api): Implement Celestia Client Library v0
  api/client/client.go
  api/client/client_test.go
  api/client/example/example.go
  api/client/go.mod
  api/client/go.sum
  api/client/grpc.go
  api/client/keyring.go
  api/client/read_client.go
  api/client/readme.md
  api/client/wrappers.go
Labels: kind:feat, area:api

#4369 deps(go.mod): Bump app (#4363) -- `arabica`
  Dockerfile
  cmd/cel-key/main.go
  go.mod
  go.sum
  nodebuilder/header/module_test.go
  state/core_access.go
Labels: kind:deps

#4318 feat(api): Celestia client lib (v4 migration)
  api/client/client.go
  api/client/client_test.go
  api/client/example/example.go
  api/client/grpc.go
  api/client/keyring.go
  api/client/read_client.go
  api/client/readme.md
  api/client/wrappers.go
Labels: kind:feat, area:api

#4371 deps(go.mod): roll back go-header release
  go.mod
  go.sum
Labels: kind:deps

#4368 deps(go.mod): Bump app mocha
  go.mod
  go.sum
Labels: kind:deps

#4372 deps(go.mod): Bump app --> `mocha`
  go.mod
  go.sum
Labels: kind:deps
