Repository celestiaorg/celestia-node, pull requests merged in 2025-09, with the labels that each got.

#4511 feat(nodebuilder): Allow disabling DASer
  nodebuilder/das/config.go
  nodebuilder/das/module.go
Labels: kind:feat

#4249 shwap!(shrex): unify shrex-nd and shrex-eds
  logs/logs.go
  nodebuilder/config_test.go
  nodebuilder/share/config.go
  nodebuilder/share/module.go
  nodebuilder/share/opts.go
  nodebuilder/tests/prune_test.go
  nodebuilder/tests/shrex_test.go
  share/eds/accessor.go
  share/eds/close_once.go
  share/eds/close_once_test.go
  share/eds/proofs_cache.go
  share/eds/rsmt2d.go
  share/eds/validation.go
  share/shwap/accessor.go
  share/shwap/axis_half.go
  share/shwap/axis_half_test.go
  share/shwap/eds.go
  share/shwap/eds_id.go
  share/shwap/namespace_data.go
  share/shwap/namespace_data_id.go
  share/shwap/p2p/bitswap/range_namespace_data_block.go
  share/shwap/p2p/bitswap/row_block.go
  share/shwap/p2p/bitswap/row_namespace_data_block.go
  share/shwap/p2p/bitswap/sample_block.go
  share/shwap/p2p/shrex/client.go
  share/shwap/p2p/shrex/errors.go
  share/shwap/p2p/shrex/exchange_test.go
  share/shwap/p2p/shrex/metrics.go
  share/shwap/p2p/shrex/middleware.go
  share/shwap/p2p/shrex/params.go
  share/shwap/p2p/shrex/request.go
  share/shwap/p2p/shrex/server.go
  share/shwap/p2p/shrex/shrex_getter/shrex.go
  share/shwap/p2p/shrex/shrex_getter/shrex_test.go
  share/shwap/p2p/shrex/shrexeds/client.go
  share/shwap/p2p/shrex/shrexeds/doc.go
  share/shwap/p2p/shrex/shrexeds/exchange_test.go
  share/shwap/p2p/shrex/shrexeds/params.go
  share/shwap/p2p/shrex/shrexeds/server.go
  share/shwap/p2p/shrex/shrexnd/client.go
  share/shwap/p2p/shrex/shrexnd/doc.go
  share/shwap/p2p/shrex/shrexnd/params.go
  share/shwap/p2p/shrex/shrexnd/server.go
  share/shwap/row_id.go
  share/shwap/row_namespace_data_id.go
  share/shwap/sample_id.go
  store/cache/accessor_cache_test.go
  store/cache/noop.go
  store/file/ods.go
  store/file/ods_q4.go
  store/file/q4.go
  store/file/square.go
Labels: kind:break!, kind:refactor

#4517 deps(nodebuilder/tests/tastora): fix go mod
  nodebuilder/tests/tastora/go.mod
  nodebuilder/tests/tastora/go.sum
Labels: kind:deps

#4522 chore: fix Go init order + tidy up flags
  cmd/cel-shed/header.go
Labels: external, kind:chore

#4524 config(nodebuilder/header): bumps go-header, removes trustingPeriod
  go.mod
  go.sum
  nodebuilder/config_test.go
  nodebuilder/header/config.go
  nodebuilder/header/constructors.go
  nodebuilder/header/module_test.go
  nodebuilder/tests/tastora/go.mod
  nodebuilder/tests/tastora/go.sum
Labels: area:config, kind:deps

#4536 fix(share/shwap): parallelise namespace data collection
  share/shwap/namespace_data_id.go
Labels: kind:fix, shwap

#4570 chore: use arabica tag
  go.mod
  go.sum
  nodebuilder/tests/tastora/go.mod
  nodebuilder/tests/tastora/go.sum
Labels: kind:deps, comrade

#4589 chore: bump go-header
  go.mod
  go.sum
Labels: kind:chore

#4591 chore: bump go-header for tastora
  nodebuilder/tests/tastora/go.mod
  nodebuilder/tests/tastora/go.sum
Labels: kind:chore
