Repository celestiaorg/celestia-node, pull requests merged in 2025-05, with the labels that each got.

#4230 fix(makefile): ensure correct semantic version is shown for branches
  Makefile
Labels: kind:fix, external

#4253 docs(README): add supported archs
  README.md
Labels: kind:docs

#4268 chore(deps): upgrade to v4.0.0-arabica
  go.mod
  go.sum
Labels: kind:deps, external

#4217 deps!: bump go-header v0.6.6 and go-fraud v0.2.3
  .github/workflows/ci_release.yml
  Dockerfile
  README.md
  go.mod
  go.sum
  nodebuilder/header/module_test.go
  nodebuilder/tests/swamp/swamp_tx.go
Labels: kind:deps, kind:break!

#4272 chore(CODEOWNERS): remove @cristaloleg
  .github/CODEOWNERS
Labels: kind:chore

#4275 deps(go.mod): bump app
  go.mod
  go.sum
Labels: kind:deps

#4259 chore: magic env variable doc update
  nodebuilder/p2p/flags.go
Labels: external, kind:chore
