Repository celestiaorg/celestia-node, pull requests merged in 2025-01, with the labels that each got.

#4029 fix(nodebuilder/da): remove random print
  nodebuilder/da/service.go
Labels: kind:misc

#4002 feat(modshare): implement GetRow
  nodebuilder/share/mocks/api.go
  nodebuilder/share/share.go
  share/availability/light/availability_test.go
  share/shwap/getter.go
  share/shwap/getters/cascade.go
  share/shwap/getters/mock/getter.go
  share/shwap/getters/testing.go
  share/shwap/p2p/bitswap/getter.go
  share/shwap/p2p/shrex/shrex_getter/shrex.go
  share/shwap/row.go
  share/shwap/row_test.go
  store/getter.go
  store/getter_test.go
Labels: kind:feat, shwap

#4039 Revert "fix(p2p): disable quic (#3937)"
  nodebuilder/p2p/addrs.go
  nodebuilder/p2p/host.go
Labels: area:p2p, kind:fix

#3989 feat(modp2p): Ping and ConnectionState APIs
  nodebuilder/p2p/cmd/p2p.go
  nodebuilder/p2p/mocks/api.go
  nodebuilder/p2p/p2p.go
  nodebuilder/p2p/p2p_test.go
Labels: area:p2p, kind:feat

#4028 feat(share/availability/full): Introduce Q4 trimming for archival nodes
  nodebuilder/pruner/migration_utils.go
  nodebuilder/pruner/migration_utils_test.go
  nodebuilder/pruner/module.go
  nodebuilder/share/module.go
  nodebuilder/tests/prune_test.go
  pruner/archival/pruner.go
  pruner/checkpoint.go
  pruner/full/pruner.go
  pruner/service.go
  pruner/service_test.go
  share/availability/full/availability.go
  share/availability/full/utils.go
  share/availability/full/utils_test.go
Labels: area:storage, kind:feat

#4024 chore(deps): upgrade celestia-app
  go.mod
  go.sum
Labels: external, kind:chore

#3741 feat: lunar use dnsaddr
  nodebuilder/p2p/bootstrap.go
Labels: kind:misc, external

#4052 fix(share/shwap/p2p/bitswap): set archivalPool ctx
  share/shwap/p2p/bitswap/getter.go
Labels: kind:fix

#3998 feat!(core): remove dependency of RPC in favour of gRPC
  core/client.go
  core/eds.go
  core/eds_test.go
  core/exchange.go
  core/exchange_test.go
  core/fetcher.go
  core/fetcher_no_race_test.go
  core/fetcher_test.go
  core/header_test.go
  core/listener.go
  core/testing.go
  go.mod
  go.sum
  nodebuilder/config_test.go
  nodebuilder/core/config.go
  nodebuilder/core/config_test.go
  nodebuilder/core/constructors.go
  nodebuilder/core/flags.go
  nodebuilder/core/flags_test.go
  nodebuilder/core/module.go
  nodebuilder/core/opts.go
  nodebuilder/module.go
  nodebuilder/node_bridge_test.go
  nodebuilder/node_test.go
  nodebuilder/state/core.go
  nodebuilder/state/module.go
  nodebuilder/testing.go
  nodebuilder/tests/fraud_test.go
  nodebuilder/tests/p2p_test.go
  nodebuilder/tests/prune_test.go
  nodebuilder/tests/swamp/swamp.go
  state/core_access.go
  state/core_access_test.go
  state/integration_test.go
Labels: area:core_and_app, kind:break!, kind:misc

#4056 deps(go.mod): bump app
  go.mod
  go.sum
Labels: kind:deps

#4059 misc!(flags): rename core.grpc.port to core.port
  nodebuilder/core/flags.go
  nodebuilder/core/flags_test.go
Labels: kind:break!, kind:misc

#4061 chore(ci): fix job name
  .github/workflows/integration-tests.yml
Labels: kind:chore

#4053 misc(state/core_accessor): add retry logic for creating a txClient
  state/core_access.go
  state/core_access_test.go
Labels: kind:misc

#4060 deps(go.mod): bump go-header v0.6.4
  go.mod
  go.sum
Labels: kind:deps

#4062 deps(go.mod): bump quic-go v0.49.0
  go.mod
  go.sum
Labels: kind:deps

#4036 test(swamp/share): cover share module with swamp tests
  .github/workflows/integration-tests.yml
  blob/helper.go
  nodebuilder/tests/blob_test.go
  nodebuilder/tests/share_test.go
  share/shwap/sample.go
Labels: area:shares, kind:testing, swamp

#4064 fix(nodebuilder/pruner): Change archival mode warning message
  nodebuilder/pruner/flags.go
Labels: kind:misc

#4035 feat(store): Add HasQ4ByHash method on store
  core/exchange_test.go
  core/listener_test.go
  store/store.go
  store/store_test.go
Labels: area:core_and_app, kind:testing
