Repository celestiaorg/celestia-node, pull requests merged in 2025-04, with the labels that each got.

#4192 chore: fix formatting
  Makefile
  nodebuilder/tests/blob_test.go
Labels: kind:chore

#4200 chore(nodebuilder): add ZKV mocha bootstrap node
  nodebuilder/p2p/bootstrap.go
Labels: external, kind:chore

#4201 feat(shwap/bitswap): disable session pruning with env var
  share/shwap/p2p/bitswap/getter.go
Labels: kind:feat

#4186 fix(state)!: Fix gas price and gas usage estimation in `CoreAccessor`
  go.mod
  go.sum
  nodebuilder/core/config.go
  nodebuilder/core/constructors.go
  nodebuilder/core/flags.go
  nodebuilder/state/config.go
  nodebuilder/state/core.go
  nodebuilder/state/flags.go
  nodebuilder/state/module.go
  state/core_access.go
  state/core_access_test.go
  state/estimate.go
  state/estimate_test.go
  state/estimator.go
  state/estimator_test.go
  state/integration_test.go
  state/option.go
  state/tx_config.go
Labels: area:state, kind:break!, kind:fix

#4091 feat!(eds): make Size method return error
  share/eds/accessor.go
  share/eds/close_once.go
  share/eds/close_once_test.go
  share/eds/proofs_cache.go
  share/eds/rsmt2d.go
  share/eds/testing.go
  share/eds/validation.go
  store/cache/accessor_cache_test.go
  store/cache/noop.go
  store/file/ods.go
  store/file/ods_q4.go
Labels: kind:feat, kind:break!, external

#4204 chore(bootstrappers): rename bootstrappers
  nodebuilder/p2p/bootstrap.go
Labels: external, kind:chore

#4182 feat(nodebuilder/p2p): If node is a bootstrapper, automatically initiate connection to other hardcoded bootstrappers for the given network
  nodebuilder/p2p/bootstrap.go
  nodebuilder/p2p/module.go
Labels: kind:feat

#4209 fix: comment string for `--core.xtoken.path`
  nodebuilder/core/flags.go
Labels: documentation, kind:fix

#4211 fix!(store/metrics): fix metrics prefix
  store/cache/metrics.go
Labels: kind:break!, kind:fix

#4220 deps(go.mod): bump app
  go.mod
  go.sum
  state/core_access.go
Labels: kind:deps

#4223 deps(go.mod): bump app
  go.mod
  go.sum
Labels: kind:deps

#4231 fix(p2p/discovery,core/listener): fix timer deadlock
  core/listener.go
  share/shwap/p2p/discovery/discovery.go
Labels: bug, kind:fix

#4235 fix(swamp): collect submitted heights in FillBlocks
  nodebuilder/tests/fraud_test.go
  nodebuilder/tests/nd_test.go
  nodebuilder/tests/prune_test.go
  nodebuilder/tests/reconstruct_test.go
  nodebuilder/tests/swamp/swamp_tx.go
  nodebuilder/tests/sync_test.go
Labels: swamp, kind:fix

#4250 misc(.gitignore): ignore go.work.sum
  .gitignore
Labels: kind:misc

#4248 refactor(nodebuilder): Deprecation of Full Node Support
  cmd/node.go
Labels: kind:misc
