Repository celestiaorg/celestia-node, pull requests merged in 2025-07, with the labels that each got.

#4381 chore(node/tests): fix and cleanup swamp tests
  .golangci.yml
  nodebuilder/tests/api_test.go
  nodebuilder/tests/blob_test.go
  nodebuilder/tests/da_test.go
  nodebuilder/tests/fraud_test.go
  nodebuilder/tests/helpers_test.go
  nodebuilder/tests/nd_test.go
  nodebuilder/tests/p2p_test.go
  nodebuilder/tests/prune_test.go
  nodebuilder/tests/reconstruct_test.go
  nodebuilder/tests/share_test.go
  nodebuilder/tests/swamp/swamp.go
  nodebuilder/tests/sync_test.go
  share/shwap/p2p/shrex/shrex_getter/shrex.go
Labels: swamp, kind:chore

#4385 deps(go.mod): bump app `mocha`
  go.mod
  go.sum
Labels: kind:deps

#4388 fix: fix lint
  .golangci.yml
Labels: kind:fix

#4391 chore(deps): upgrade to app v4.0.9-arabica
  go.mod
  go.sum
Labels: kind:deps, external

#4325 refactor!(share/shwap): rework range namespace data
  .golangci.yml
  nodebuilder/share/get_range_result.go
  nodebuilder/share/mocks/api.go
  nodebuilder/share/share.go
  nodebuilder/tests/share_test.go
  share/availability/light/availability_test.go
  share/eds/accessor.go
  share/eds/close_once.go
  share/eds/close_once_test.go
  share/eds/proof.go
  share/eds/proofs_cache.go
  share/eds/rsmt2d.go
  share/eds/testing.go
  share/eds/validation.go
  share/shwap/getter.go
  share/shwap/getters/cascade.go
  share/shwap/getters/mock/getter.go
  share/shwap/getters/testing.go
  share/shwap/p2p/bitswap/getter.go
  share/shwap/p2p/bitswap/range_namespace_data_block.go
  share/shwap/p2p/bitswap/range_namespace_data_block_test.go
  share/shwap/p2p/shrex/shrex_getter/shrex.go
  share/shwap/pb/shwap.pb.go
  share/shwap/pb/shwap.proto
  share/shwap/proof.go
  share/shwap/range_namespace_data.go
  share/shwap/range_namespace_data_id.go
  share/shwap/range_namespace_data_id_test.go
  share/shwap/range_namespace_data_test.go
  share/shwap/sample_id.go
  store/cache/accessor_cache_test.go
  store/cache/noop.go
  store/file/ods.go
  store/file/ods_q4.go
  store/getter.go
Labels: kind:break!, kind:refactor

#4396 deps(go.mod): bump tendermint replace
  go.mod
  go.sum
Labels: kind:deps, external

#4410 deps(go.mod): Bump app to mainnet
  go.mod
  go.sum
Labels: kind:deps, external

#4429 fix(test/blob): fix flaky blob test
  blob/service_test.go
Labels: kind:testing, external

#4120 refactor(api)!: removing gateway
  api/gateway/availability.go
  api/gateway/bindings.go
  api/gateway/bindings_test.go
  api/gateway/config.go
  api/gateway/handler.go
  api/gateway/header.go
  api/gateway/health.go
  api/gateway/middleware.go
  api/gateway/server.go
  api/gateway/server_test.go
  api/gateway/share.go
  api/gateway/share_test.go
  api/gateway/state.go
  api/gateway/util.go
  api/gateway/util_test.go
  cmd/node.go
  cmd/util.go
  docker/entrypoint.sh
  go.mod
  nodebuilder/config.go
  nodebuilder/config_test.go
  nodebuilder/gateway/config.go
  nodebuilder/gateway/config_test.go
  nodebuilder/gateway/constructors.go
  nodebuilder/gateway/defaults.go
  nodebuilder/gateway/defaults_test.go
  nodebuilder/gateway/flags.go
  nodebuilder/gateway/flags_test.go
  nodebuilder/gateway/module.go
  nodebuilder/module.go
  nodebuilder/node.go
Labels: kind:break!, area:api, external

#4430 fix!(blobstream): change DataRootTupleInclusionProof type
  nodebuilder/blobstream/data_root_tuple_root.go
  nodebuilder/blobstream/mocks/api.go
  nodebuilder/blobstream/service.go
Labels: kind:break!, kind:fix

#4270 chore(bootstrapers): add 01node mainnet bootstrap node
  nodebuilder/p2p/bootstrap.go
Labels: external, kind:chore

#4303 refactor(nodebuilder/pruner)!: Remove --experimental-pruning
  nodebuilder/pruner/config.go
  nodebuilder/pruner/flags.go
Labels: kind:break!

#4421 test: use tastora docker types instead of interface types
  nodebuilder/tests/tastora/framework.go
Labels: kind:testing, external

#4443 deps(go.mod)!: Bump app to v5
  api/client/client_test.go
  api/client/keyring.go
  blob/blob.go
  blob/commitment_proof.go
  blob/repro_test.go
  blob/service.go
  blob/service_test.go
  cmd/cel-key/main.go
  cmd/start.go
  core/eds.go
  core/eds_test.go
  core/exchange_test.go
  core/header_test.go
  core/testing.go
  go.mod
  go.sum
  header/header.go
  header/headertest/fraud/testing.go
  header/headertest/testing.go
  header/headertest/validate_test.go
  header/pb/extended_header.pb.go
  header/serde.go
  libs/keystore/map_keystore.go
  nodebuilder/da/service.go
  nodebuilder/init.go
  nodebuilder/init_test.go
  nodebuilder/tests/da_test.go
  nodebuilder/tests/swamp/config.go
  nodebuilder/tests/swamp/swamp.go
  nodebuilder/tests/swamp/swamp_tx.go
  share/eds/byzantine/bad_encoding.go
  share/eds/byzantine/bad_encoding_test.go
  share/eds/edstest/testing.go
  share/eds/proof.go
  share/eds/proofs_cache.go
  share/eds/retriever.go
  share/eds/retriever_no_race_test.go
  share/eds/rsmt2d.go
  share/empty.go
  share/ipld/add.go
  share/ipld/get_shares_test.go
  share/root.go
  share/share.go
  share/shwap/getters/testing.go
  share/shwap/p2p/bitswap/getter.go
  share/shwap/row.go
  share/shwap/row_namespace_data.go
  share/shwap/sample.go
  state/core_access.go
  state/core_access_test.go
  state/estimate.go
  state/estimate_test.go
  state/integration_test.go
  state/tx_config.go
Labels: kind:deps, kind:break!, external

#4435 fix!(blobstream): change GetDataRootTupleRoot return type
  nodebuilder/blobstream/blobstream.go
  nodebuilder/blobstream/mocks/api.go
  nodebuilder/blobstream/service.go
  nodebuilder/blobstream/service_test.go
Labels: kind:break!, external, area:blobstream

#4445 backport app bump to `arabica`
  go.mod
  go.sum
Labels: kind:deps, external

#4343 misc(core): add eds size to store log
  core/eds.go
Labels: kind:misc

#4441 test: tastora remove fullnode and rely on bridge and light nodes only
  nodebuilder/tests/tastora/README.md
  nodebuilder/tests/tastora/blob_test.go
  nodebuilder/tests/tastora/config.go
  nodebuilder/tests/tastora/framework.go
Labels: kind:testing, external

#4450 chore(deps): upgrade to app v5.0.1
  go.mod
  go.sum
  nodebuilder/tests/tastora/go.mod
  nodebuilder/tests/tastora/go.sum
Labels: kind:deps, external

#4451 chore(deps): upgrade to app v5.0.1 (#4450)
  go.mod
  go.sum
Labels: kind:deps, external

#4428 fix(api/header)!: tendermint compatible json marshall (#3928)
  api/docgen/exampledata/extendedHeader.json
  header/header.go
Labels: kind:break!, area:api, external

#4431 perf(api/da): request all blobs once in da.Get
  nodebuilder/da/service.go
Labels: area:api, external, kind:perf

#4447 chore(lint): fmt to tidy tastora go.mod
  Makefile
Labels: external, kind:chore
