Repository celestiaorg/celestia-node, pull requests merged in 2025-02, with the labels that each got.

#4088 chore: bump app to v3.3.1-arabica
  go.mod
  go.sum
Labels: kind:deps

#4097 fix(test/swamp): fix TestConvertFromArchivalToPruned
  nodebuilder/tests/prune_test.go
Labels: kind:testing, swamp

#4096 fix(core/fetcher): resubscribe if consensus node goes offline
  core/fetcher.go
  core/fetcher_test.go
Labels: kind:fix

#4095 deps(go.mod): mocha bump for app
  go.mod
  go.sum
Labels: kind:deps

#4099 deps(go.mod): bump app
  go.mod
  go.sum
Labels: kind:deps

#4011 docs: fix broken link
  docs/adr/adr-010-incentivized-testnet-monitoring.md
Labels: kind:docs, external

#4107 fix: cli with malformed height
  nodebuilder/blob/cmd/blob.go
Labels: kind:fix, external, area:cli

#4115 fix(docgen): add network.Direction
  api/docgen/examples.go
Labels: kind:fix

#4117 fix(share/peer-manager): fix potential nil dereference in peer manager
  share/shwap/p2p/shrex/peers/manager.go
Labels: kind:fix

#4133 improvement(core): increase message size to 64Mb
  nodebuilder/core/constructors.go
Labels: area:core_and_app, kind:misc

#4116 chore(ci): fail openrpc-gen if error
  .github/workflows/ci_release.yml
Labels: kind:chore

#3862 feat(shwap/bitswap): add blockstore metrics
  nodebuilder/settings.go
  nodebuilder/share/bitswap.go
  nodebuilder/share/module.go
  nodebuilder/share/opts.go
  share/shwap/p2p/bitswap/blockstore_metrics.go
Labels: kind:feat, area:metrics
