Repository celestiaorg/celestia-node, pull requests merged in 2025-03, with the labels that each got.

#4113 chore(go.mod): bump libp2p deps
  go.mod
  go.sum
Labels: kind:chore

#4150 fix(shwap/discovery): increase DHT refresh interval to default 10mins
  share/shwap/p2p/discovery/dht.go
Labels: kind:fix

#4157 Fix broken link(s) to node requirements in readme.
  README.md
Labels: kind:docs

#4161 deps(go.mod): bump app
  go.mod
  go.sum
Labels: kind:deps

#4159 refactor: replace golang.org/x/exp with stdlib
  go.mod
  nodebuilder/tests/swamp/swamp.go
Labels: kind:refactor, external

#4144 feat: Add Binary Builders mocha-4 bootstrapper
  nodebuilder/p2p/bootstrap.go
Labels: kind:misc, external

#4114 chore(go.mod): bump boxo fork
  go.mod
  go.sum
  share/availability/light/availability_test.go
  share/availability/test/testing.go
  share/shwap/p2p/bitswap/bitswap.go
  share/shwap/p2p/bitswap/block_fetch_test.go
Labels: kind:chore

#4164 feat(modp2p): reachability check
  nodebuilder/p2p/host.go
  nodebuilder/p2p/module.go
  nodebuilder/p2p/reachability.go
Labels: kind:feat

#4167 deps(go.mod): app bump to mocha
  go.mod
  go.sum
Labels: kind:deps

#4149 perf(header): MsgID func only needs to unmarshal Commit from ExtendedHeader
  header/headertest/serde_test.go
  header/serde.go
Labels: area:header, kind:misc, performance

#4174 deps(go.mod): bump app
  go.mod
  go.sum
Labels: kind:deps

#4175 deps(go.mod): bump app
  go.mod
  go.sum
Labels: kind:deps

#4160 refactor: replace custom appendTo methods with `encoding.AppendBinary`
  share/shwap/eds_id.go
  share/shwap/namespace_data_id.go
  share/shwap/row_id.go
  share/shwap/row_namespace_data_id.go
  share/shwap/sample_id.go
Labels: kind:refactor, external

#4136 fix: use a more straightforward return value
  share/shwap/share.go
Labels: kind:fix, external

#4168 feat(state/core_accessor): add fee estimator
  api/docgen/examples.go
  go.mod
  go.sum
  libs/utils/address.go
  nodebuilder/core/config.go
  nodebuilder/core/flags.go
  nodebuilder/state/cmd/state.go
  nodebuilder/state/core.go
  nodebuilder/state/module.go
  state/core_access.go
  state/core_access_test.go
  state/estimator.go
  state/estimator_test.go
  state/integration_test.go
  state/tx_config.go
Labels: area:state, kind:feat

#4183 refactor(all): modernized code with built-in func
  api/gateway/bindings_test.go
  das/state.go
  nodebuilder/node/type.go
  nodebuilder/store.go
  nodebuilder/tests/swamp/swamp.go
Labels: kind:refactor, external

#4184 refactor: use `time.DateTime` constant from standard library
  nodebuilder/p2p/cmd/p2p.go
Labels: kind:refactor, external

#4187 chore(deps): upgrade to go-square v2.2.0
  go.mod
  go.sum
Labels: kind:deps, external, kind:chore

#4179 chore(nodebuilder): add 01node bootstrap testnet node
  nodebuilder/p2p/bootstrap.go
Labels: kind:misc, external
