Repository celestiaorg/celestia-node, pull requests merged in 2025-08, with the labels that each got.

#4427 feat(share/availability)!: lower sampling window to 7 days
  nodebuilder/pruner/module.go
  share/availability/light/availability.go
  share/availability/window.go
  share/availability/window_test.go
Labels: kind:break!, external

#4471 chore: update warning text on pruned -> archival conversion
  share/availability/full/availability.go
Labels: kind:chore

#4470 docs(api/da): doc and deprecate DA API
  api/docgen/openrpc.go
  api/rpc_test.go
  nodebuilder/da/da.go
  nodebuilder/da/service.go
  nodebuilder/default_services.go
  nodebuilder/node.go
  nodebuilder/rpc/constructors.go
Labels: kind:misc

#4472 fix(cmd/celestia): parse only store determination flags for auxiliary commands
  cmd/auth.go
  cmd/config.go
  cmd/init.go
  cmd/node.go
  cmd/reset_store.go
  cmd/start.go
  cmd/util.go
Labels: kind:fix, area:cli

#4481 !fix(api/share) use height in Samples method
  nodebuilder/share/share.go
Labels: kind:break!, area:api

#4504 feat(config): adding a bool flag to enable/disable bitswap
  nodebuilder/config_test.go
  nodebuilder/share/config.go
  nodebuilder/share/constructors.go
Labels: area:config, kind:feat

#4506 chore: backport bitswap changes
  cmd/flags_misc.go
  go.mod
  go.sum
  nodebuilder/tests/tastora/go.mod
  nodebuilder/tests/tastora/go.sum
  share/shwap/p2p/bitswap/bitswap.go
  share/shwap/p2p/bitswap/blockstore_metrics.go
Labels: kind:chore
